<?php
/*
key => : separated values // accent meaning
*/
$romaji_kanji = array(
'aa'=>'*ああ', // ➀ like that, that much
'abiru'=>'*浴[あ]びる', // ⓪ take a shower
'abunai'=>'*危[あぶ]ない', // ⓪ dangerous
'abura'=>'*油[あぶら]', // ⓪ oil
'acchi'=>'*あっち', // ➂ other side, over there casual
'achikochi'=>'*あちこち', // ➁ち➁ all over, here and there
'achira'=>'*あちら', // ⓪ over there, that way
'adana'=>'*あだ名[な]', // ⓪ nickname
'adobaisu'=>'*アドバイス', // ➁ドバ➁ advice
'agaru'=>'*上[あ]がる', // ⓪ get nervous, go up, increase (in quality or quantity), go up, rise (physical movement)
'ageru'=>'*上[あ]げる', // ⓪ raise, lift, give, offer
'ago'=>'*顎[あご]', // ➂ jaw, chin
'ai'=>'*愛[あい]', // ➀ love
'aida'=>'*間[あいだ]', // ⓪ interval, space between things
'aidea'=>'*アイデア', // ➁イデ➁ idea
'aidoru'=>'*アイドル', // ➀ idol
'aikawarazu'=>'*相[あい]変[か]わらず', // ⓪ as usual, as before, still
'aimai'=>'*曖[あい]昧[まい]', // ⓪ ambiguous, vague
'aimasu'=>'*会[あ]います', // 

'ainiku'=>'*あいにく', // ⓪生憎 unfortunately, we are afraid that
'airon'=>'*アイロン', // ⓪ iron (for clothes)
'aisatsu'=>'*挨[あい]拶[さつ]', // ➀ greet, greeting
'aisu'=>'*アイス', // ➀ ice cream (for short)
'aisukoohii'=>'*アイスコーヒー', // ア➁イスコーヒ➁ー iced coffee
'aisukuriimu'=>'*アイスクリーム', // ア➁イスクリ➁ーム ice cream
'aisuru'=>'*愛[あい]する', // あ➁いす➁る love, care for
'aite'=>'*相[あい]手[て]', // ➂ opponent, the other party
'aji'=>'*味[あじ]', // ⓪ taste, flavor
'aka'=>'*赤[あか]', // ➀ red color
'akachan'=>'*赤[あか]ちゃん', // baby (colloquial)
'akai'=>'*赤[あか]い', // ➂ red
'akaji'=>'*赤[あか]字[じ]', // ⓪ deficit, in the red
'akanbou'=>'*赤[あか]ん坊[ぼう]', // ⓪ (human) baby
'akarui'=>'*明[あか]るい', // ⓪ bright, cheerful
'akeru'=>'*開[あ]ける', // ⓪ open, unlock doors, windows, etc.
'aki'=>'*秋[あき]', // ➀ autumn, fall
'akiraka'=>'*明[あき]らか', // あ➁き➁らか clear, obvious
'akirameru'=>'*諦[あきら]める', // あ➁きらめ➁る abandon, give up
'akireru'=>'*呆[あき]れる', // ⓪ be amazed at, be stunned by (something negative)
'aku'=>'*空[あ]く', // ⓪ become available or vacant
'akubi'=>'*欠伸[あくび]', // ⓪ yawn
'akusesarii'=>'*アクセサリー', // ➀ accessories, jewelry
'akushu'=>'*握[あく]手[しゅ]', // ➀ handshake
'amai'=>'*甘[あま]い', // ⓪ sweet
'amachua'=>'*アマチュア', // ⓪ amateur
'amari'=>'*余[あま]り', // ➂ not much
'amaru'=>'*余[あま]る', // あ➁ま➁る remain, be in excess
'ame'=>'*雨[あめ]:飴[あめ]', // ➀ rain ⓪ 飴
'amerika'=>'*アメリカ', // ⓪
'amerikajin'=>'*アメリカ人[じん]', // ア➁メリカ➁人
'amayakasu'=>'*甘[あま]やかす', // あ➁まやか➁す be indulgent to, spoil
'an'=>'*案[あん]', // ➀ plan, idea, proposal
'ana'=>'*穴[あな]', // ➂ hole, deficit, vacancy, flaw
'anata'=>'*あなた', // 貴方 あ➁な➁た you
'anaunsaa'=>'*アナウンサー', // ア➁ナウ➁ンサー announcer
'ane'=>'*姉[あね]', // ⓪ 姐 speaker’s own older sister
'ani'=>'*兄[あに]', // ➀ speaker’s own older brother
'ankeeto'=>'*アンケート', // ➀ questionnaire
'ankeetochousa'=>'*アンケート調[ちょう]査[さ]', // ア➁ンケートちょ➁うさ
'ankeetokekka'=>'*アンケート結[けっ]果[か]', // ア➁ンケートけ➁っか
'anmari'=>'*余[あんま]り', // ➂ (not) that much, (not) so much, => 余[あま]り
'anna'=>'*あんな', // ⓪ such; that sort of; that kind of; like that
'ano'=>'*あの', // ⓪ that; say, well, um, er
'anou'=>'*あのう', // ⓪ say, well, um, er
'anohito'=>'*あの人[ひと]', // あ➁の➁ひと
'anokata'=>'*あの方[かた]', // ③
'anzen'=>'*安[あん]全[ぜん]', // ⓪ safety, security
'annai'=>'*案[あん]内[ない]', // あ➁んな➁い guide, guidance
'annani'=>'*あんなに', // that much, such, so, to that extent
'anshin'=>'*安[あん]心[しん]', // ⓪ peace of mind, relief
'antei'=>'*安[あん]定[てい]', // ⓪ stability, composure
'anzen'=>'*安[あん]全[ぜん]', // ⓪ safety, security
'ao'=>'*青[あお]', // ➀ blue, green
'aoi'=>'*青[あお]い', // あ➁お➁い blue
'aojiroi'=>'*青[あお]白[じろ]い', // あ➁おじろ➁い pale
'aozora'=>'*青[あお]空[ぞら]', // あ➁おぞ➁ら blue sky
'apaato'=>'*アパート', // ア➁パ➁ート apartment, flat
'appu'=>'*アップ', // ➀ close-up
'ara'=>'*あら', // ➀ (female) oh! ah! oh no
'araimono'=>'*洗[あら]い物[もの]', // ⓪ dishes to be washed, laundry
'arata'=>'*新[あら]た', // ➀ new, fresh
'arau'=>'*洗[あら]う', // ➀ wash
'arawareru'=>'*現[あらわ]れる', // あ➁らわれ➁る appear, emerge
'arayuru'=>'*あらゆる', // ➁ all; every
'are'=>'*あれ', // ⓪ that over there
'arekore'=>'*あれこれ', // あ➁れ➁これ this and that, one thing or another
'ari'=>'*蟻[あり]', // ⓪ ant
'arigatou'=>'*ありがとう', // あ➁り➁がとう
'arigatougozaimasu'=>'*ありがとうございます',
'arimasen'=>'*ありません', // 
'aru'=>'*有[あ]る:在[あ]る', // ➀ exist, there is
'arubaito'=>'*アルバイト', // ア➁ルバ➁イト part-time job
'arubamu'=>'*アルバム', // ⓪ album
'arukooru'=>'*アルコール', // ⓪ alcohol, alcoholic beverage
'arukimasu'=>'*歩[ある]きます', // walk, go on foot
'aruku'=>'*歩[ある]く', // あ➁る➁く walk, go on foot
'asa'=>'*朝[あさ]', // ➀ morning
'asagohan'=>'*朝[あさ]ご飯[はん]', // あ➁さご➁はん breakfast
'asai'=>'*浅[あさ]い', // ⓪ shallow, superficial
'asatte'=>'*明[あ]後日[さって]', // ➁さ➁
'ase'=>'*汗[あせ]', // ➀ sweat
'aseru'=>'*焦[あせ]る', // あ➁せ➁る feel pressured, feel hurried
'ashi'=>'*足[あし]', // ➂ leg, foot
'ashikubi'=>'*足[あし]首[くび]', // あ➁し➁くび ankle
'ashimoto'=>'*足[あし]元[もと]', // あ➁しも➁と step, under foot
'ashita'=>'*明[あ]日[した]', // ➂ tomorrow
'asobi'=>'*遊[あそ]び', // ⓪ play, amusement
'asobinin'=>'*遊[あそ]び人[にん]', // ⓪ playboy, gambler
'asobu'=>'*遊[あそ]ぶ', // ⓪ play
'asoko'=>'*あそこ', // ⓪ over there
'assari'=>'*あっさり', // あ➁っさ➁り bluntly, easily, flatly
'asu'=>'*明[あ]日[す]', // ➂ tomorrow (rather formal)
'ataeru'=>'*与[あた]える', // ⓪ give (formal)
'atama'=>'*頭[あたま]', // ➂ head
'atarashii'=>'*新[あたら]しい', // あ➁たらし➁い new
'atari'=>'*辺[あたり]', // ➀ vicinity, neighbourhood
'atarimae'=>'*当[あ]たり前[まえ]', // ⓪ no wonder, natural
'ataru'=>'*当[あ]たる', // ⓪ go straight and hit, strike
'atatakai'=>'*暖[あたた]かい', // あ➁たたか➁い warm
'atatamaru'=>'*暖[あたた]まる', // あ➁たたま➁る get warm
'atatameru'=>'*暖[あたた]める', // あ➁たため➁る warm (something) up
'atena'=>'*宛[あて]名[な]', // ⓪ name of recipient, addressee
'atesaki'=>'*宛[あて]先[さき]', // ⓪ recipient’s address
'atesakihenkou'=>'*あて先[さき]変[へん]更[こう]', // (computing) redirection
'ato'=>'*後[あと]', // ➀ after, behind, remainder
'atokatazuke'=>'*後[あと]片[かた]付[づ]け', // あ➁とか➁たづけ cleaning up
'atomodori'=>'*後[あと]戻[もど]り', // あ➁とも➁どり turning back, retreat
'atsui'=>'*厚[あつ]い:暑[あつ]い:熱[あつ]い', // ⓪ thick, bulky; あ➁つ➁い hot of weather, hot to touch
'atsukau'=>'*扱[あつか]う', // ⓪ handle, deal with
'atsumaru'=>'*集[あつ]まる', // あ➁つま➁る gather, be collected
'atsumeru'=>'*集[あつ]める', // あ➁つめ➁る collect, gather
'atsusa'=>'*厚[あつ]さ:暑[あつ]さ', // ⓪ thickness; ➀ heat
'atsusaatari'=>'*暑[あつ]さあたり', // あ➁つさ'あ➁たり heatstroke
'au'=>'*会[あ]う:合[あ]う:遭[あ]う:遇[あ]う', // ➀ meet; ➀ fit, match; ➀ meet, encounter, get caught in
'awaseru'=>'*合[あ]わせる', // あ➁わせ➁る match (something), adapt (oneself)
'awatadashii'=>'*慌[あわ]ただしい', // あ➁わただし➁い busy and hurried, rapid, sudden
'awateru'=>'*慌[あわ]てる', // ⓪ be flustered, be in a hurry
'ayamaru'=>'*謝[あやま]る', // あ➁やま➁る apologize, decline, be at a loss
'ayashii'=>'*怪[あや]しい', // ⓪ suspicious, dubious
'azukaru'=>'*預[あず]かる', // あ➁ずか➁る take care of, keep
'azukeru'=>'*預[あず]ける', // あ➁ずけ➁る deposit, leave (something) with (someone)
'ba'=>'*ば:場[ば]', // if...then...; occasion, situation
'baagen'=>'*バーゲン', // ➀ bargain sale
'baai'=>'*場[ば]合[あい]', // ⓪ situation, case
'baba'=>'*ばば', // ➀ 婆
'baggu'=>'*バッグ', // ➀ bag
'bai'=>'*倍[ばい]', // ➀ double, times
'baiku'=>'*バイク', // ➀ motorcycle
'baiorin'=>'*バイオリン', // ⓪ violin
'baiten'=>'*売[ばい]店[てん]', // ⓪ booth, kiosk, shop, store
'baito'=>'*バイト', // ⓪ part-time job
'bajji'=>'*バッジ', // ➀ badge
'baka'=>'*馬[ば]鹿[か]', // ➀ foolish, stupid
'bakku'=>'*バック', // ➀ back, reverse
'ban'=>'*晩[ばん]:番[ばん]', // evening; one’s turn, watch
'banana'=>'*バナナ', // ➀ banana
'bangou'=>'*番[ばん]号[ごう]', // ➁んご➁ assigned number
'bangumi'=>'*番[ばん]組[ぐみ]', // ⓪ program
'Bara'=>'*薔[ば]薇[ら]:輩[ばら]', // ⓪ rose
'barabara'=>'*ばらばら:バラバラ', // ➀ scattered, disperse; separately, discretely
'baransu'=>'*バランス', // ⓪ balance
'bareehooru'=>'*バレーボール', // ➁レーボ➁ volleyball
'basho'=>'*場[ば]所[しょ]', // ⓪ place, space
'basu'=>'*バス', // ➀ bus
'basukettobo-ru'=>'*バスケットボール', // ➁スケットボ➁ basketball
'basutei'=>'*バス停[てい]', // ⓪ bus stop
'bata-'=>'*バター', // ➀ butter
'batsu'=>'*バツ', // ➀ cross, x-mark (on errors, mistakes etc.)
'beddo'=>'*ベッド', // ➀ bed
'ben'=>'*便[べん]', // ➀ convenience, service, facility, accommodation; excreta (esp. faeces), excrement, stool
'bengoshi'=>'*弁[べん]護[ご]士[し]', // ➁んご➁ lawyer, attorney
'benkyou'=>'*勉[べん]強[きょう]', // study
'benkyoushimasu'=>'*勉[べん]強[きょう]します', // study
'benkyousuru'=>'*勉[べん]強[きょう]する', // study
'benri'=>'*便[べん]利[り]', // ➀ convenience
'bentou'=>'*弁[べん]当[とう]', // ➁んと➁ boxed lunch
'beru'=>'*ベル', // ➀ bell
'beruto'=>'*ベルト', // ⓪ belt
'besuto'=>'*ベスト', // ➀ best
'betabeta'=>'*べたべた:ベタベタ', // ➀ stick together, sticky
'betsu'=>'*別[べつ]', // ⓪ another, different
'betsubetsu'=>'*別[べつ]々[べつ]', // ⓪ separately
'betsuni'=>'*別[べつ]に', // ⓪ not particularly, not really
'betsuniiikedo'=>'別にいいけど', // I don't care; fine, whatever; that's okay; sure, go ahead
'bideo'=>'*ビデオ', // ➀ video
'biichi'=>'*ビーチ', // ➀ beach
'biiru'=>'*ビール', // ➀ beer
'bijin'=>'*美[び]人[じん]', // ➀ beautiful woman
'bijinesu'=>'*ビジネス', // ➀ business
'bijutsukan'=>'*美[び]術[じゅつ]館[かん]', // ➁じゅつ➁ ➁じゅ➁ art museum
'bikkurisuru'=>'*吃[びっ]驚[くり]する', // ➁っく➁ be surprised, be startled (casual)
'bin'=>'*瓶[びん]:便[びん]', // ➂ bottle; flight, mail, opportunity
'binbou'=>'*貧[びん]乏[ぼう]', // ➀ poverty, destitution
'biniiru'=>'*ビニール', // ➁ニ➁ vinyl, plastic
'biru'=>'*ビル', // ➀ building
'bishobisho'=>'*びしょびしょ', // ➀ soaking wet, soaked, pitsch-patsch
'bisshori'=>'*びっしょり', // ➁っしょ➁ drenched, soaked
'biza'=>'*ビザ', // ➀ visa
'boifurendo'=>'*ボーイフレンド', // ➁ーイフレ➁ boyfriend
'boki'=>'*簿[ぼ]記[き]', // ➀
'boku'=>'*僕[ぼく]', // ➀⓪ I, me usually used by young males
'bonyari'=>'*ぼんやり', // ➁んや➁ vacantly, absent-mindedly
'booru'=>'*ボール', // ⓪ ball
'boorupen'=>'*ボールペン',// ⓪ ballpoint pen
'boorubako'=>'*ボール箱[ばこ]', // ⓪ carton, cardboard box
'booto'=>'*ボート', // ➀ light boat, small craft
'boryuumu'=>'*ボリューム', // ⓪ volume
'botan'=>'*ボタン:牡[ぼ]丹[たん]', // ⓪ button
'boueki'=>'*貿[ぼう]易[えき]', // ⓪ (export and import) trade
'bounenkai'=>'*忘[ぼう]年[ねん]会[かい]', // ➁うね➁ year-end party
'bouryoku'=>'*暴[ぼう]力[りょく]', // ➀ violence, force
'boushi'=>'*帽[ぼう]子[し]', // ⓪ hat, cap
''=>'*ぶ:部[ぶ]', // dept, club, team, 
'bubun'=>'*部[ぶ]分[ぶん]', // ➀ part, section
'buchou'=>'*部[ぶ]長[ちょう]', // ⓪ department head
'buchou'=>'*部[ぶ]長[ちょう]付[づき]', // ⓪ assistant (to general manager)
'budou'=>'*ぶどう[]', // grapes
'buhin'=>'*部[ぶ]品[ひん]', // ⓪ parts; accessories; components
'bun'=>'*分[ぶん]:文[ぶん]', // amount, share; sentence, statement
'bunbougu'=>'*文[ぶん]房[ぼう]具[ぐ]', // ➁んぼ➁ stationery, writing materials
'bunka'=>'*文[ぶん]化[か]', // ➀ culture
'bunkei'=>'*文[ぶん]型[けい]', // ⓪
'bunrui'=>'*分[ぶん]類[るい]', // ⓪
'bunseki'=>'*分[ぶん]析[せき]', // ⓪ analysis
'bunshou'=>'*文[ぶん]章[しょう]', // ➀ sentence, writing
'bunya'=>'*分[ぶん]野[や]', // ➀ field, area， division
'burabura'=>'*ぶらぶら', // ➀ wander, walk around, dangling, swinging, lazily
'burasagaru'=>'*ぶら下[さ]がる', // ⓪ hang down, dangle
'burashi'=>'*ブラシ', // ➀ brush
'burausu'=>'*ブラウス', // ➁ラ➁ blouse
'buruburu'=>'*ぶるぶる', //  ➀ shivering, trembling
'buta'=>'*豚[ぶた]', // ⓪ pig, pork
'butai'=>'*舞[ぶ]台[たい]', // ➀ stage, setting
'butaniku'=>'*豚[ぶた]肉[にく]', // ⓪ pork
'butsubutsu'=>'*物[ぶつ]々[ぶつ]', // ⓪ in a mutter, mumble, grunt
'butsukaru'=>'*ぶつかる', // ⓪ hit, bump into
'buumu'=>'*ブーム', // ➀ boom, fad, 
'byouin'=>'*病[びょう]院[いん]', // ⓪ hospital
'byouin'=>'*美[び]容[よう]院[いん]', // ➁よ➁ hair salon
'byouki'=>'*病[びょう]気[き]', // ⓪ illness
'byounin'=>'*病[びょう]人[にん]', // ⓪ sick person, patient
'cha'=>'*茶[ちゃ]', // tea
'chairo'=>'*茶[ちゃ]色[いろ]', // ⓪ brown
'chan'=>'*ちゃん',
'channeru'=>'*チャンネル', // ⓪ channel
'chansu'=>'*チャンス', // ➀ chance
'chanto'=>'*ちゃんと', // ⓪ correctly, properly, seriously, quickly
'chanto'=>'*チャント', // ➀ chant
'chawan'=>'*茶[ちゃ]碗[わん]', // ⓪ rice bowl
'chawanmushi'=>'*茶[ちゃ]碗[わん]蒸[む]し', // ⓪ savoury steamed egg custard with chicken, mushrooms, etc.
'chenji'=>'*チェンジ', // ➀ change, exchange
'chi'=>'*ち:地[ち]:血[ち]', // ground, place; blood (colloquial)
'chichi'=>'*父[ちち]', // ➂ speaker’s father
'chichioya'=>'*父[ちち]親[おや]', // ⓪ father
'chigai'=>'*違[ちが]い', // ⓪ difference, mistake
'chigaimasu'=>'*違[ちが]います', // That's wrong
'chigau'=>'*違[ちが]う', // ➁が➁ differ, be wrong
'chihou'=>'*地[ち]方[ほう]', // ➁ほ➁ local region
'chiiki'=>'*地[ち]域[いき]', // ➀ region, area
'chiimu'=>'*チーム', // ➀ team
'chiisai'=>'*小[ちい]さい', // ➁いさ➁ small
'chiisana'=>'*小[ちい]さな', // ➀ small
'chiizu'=>'*チーズ', // ➀ cheese
'chika'=>'*地[ち]下[か]', // ➀➂ underground
'chikaduku'=>'*近[ちか]付[づ]く', // ➁かづ➁ approach, come close
'chikai'=>'*近[ちか]い', // ➁か➁ near, close
'chikaku'=>'*近[ちか]く', // ➁か➁ in the near future, before long, near, close to
'chikamichi'=>'*近[ちか]道[みち
]', // ➁か➁ shortcut
'chikara'=>'*力[ちから]', // ➂ strength, power
'chikatetsu'=>'*地[ち]下[か]鉄[てつ]', // ⓪ subway
'chikatetsudou'=>'*地[ち]下[か]鉄[てつ]道[どう]', // ➁かて➁ subway
'chikayoru'=>'*近[ちか]寄[よ]る', // ➁かよ➁ go near, approach
'chiketto'=>'*チケット', // ➁ケ➁ ticket (loan word)
'chikoku'=>'*遅[ち]刻[こく]', // ⓪ tardiness, lateness
'chikyuu'=>'*地[ち]球[きゅう]', // ⓪ the earth
'chirakaru'=>'*散[ち]らかる', // ⓪ be in a mess, lie scattered
'chirakasu'=>'*散[ち]らかす', // make a mess, scatter around
'chiryou'=>'*治[ち]療[りょう]', // ⓪ medical treatment
'chiisai'=>'*小[ちい]さい', // ➁いさ➁ small
'chishiki'=>'*知[ち]識[しき]', // ➀ knowledge
'chishikijin'=>'*知[ち]識[しき]人[じん]', // ➁しき➁ intellectual
'chittomo'=>'*些[ちっ]とも', // ➁っと➁ not at all
'chizu'=>'*地[ち]図[ず]', // ➀ map, atlas
'chokin'=>'*貯[ちょ]金[きん]', // ⓪ savings, deposit
'chokoreeto'=>'*チョコレート:チョコ', // ➁コレ➁
'chokugo'=>'*直[ちょく]後[ご]', // ⓪ immediately following
'chokusetsu'=>'*直[ちょく]接[せつ]', // ⓪ directly
'chosha'=>'*著[ちょ]者[しゃ]', // ➀ author, writer
'chotto'=>'*ちょっと', // just a moment, just a little
'chou'=>'*朝[ちょう]:兆[ちょう]', // ➀ dynasty, period
'chou'=>'*長[ちょう]:蝶[ちょう]', // ➀ head; chief; leader; elder
'chouon'=>'*長[ちょう]音[おん]', // ➀ 
'chousen'=>'*朝[ちょう]鮮[せん]', // ちょ➁うせ➁ん
'choudo'=>'*ちょうど', // ⓪ 丁度、恰度 just, exactly
'choujo'=>'*長[ちょう]女[じょ]', // ➀ eldest daughter
'choukan'=>'*朝[ちょう]刊[かん]', // ⓪ morning edition paper
'chouki'=>'*長[ちょう]期[き]', // ➀ long period
'chounan'=>'*長[ちょう]男[なん]', // ➀ eldest son
'chousei'=>'*調[ちょう]整[せい]', // ⓪ regulation, adjustment
'chouseisuru'=>'*調[ちょう]整[せい]する', // ⓪
'choushoku'=>'*朝[ちょう]食[しょく]', // ⓪ breakfast
'chuu'=>'*中[ちゅう]', // ➀ middle, medium size
'chuudoku'=>'*中[ちゅう]毒[どく]', // ➀ poisoning, addiction
'chuugakkou'=>'*中[ちゅう]学[がっ]校[こう]', // ➁うが➁ junior high school
'chuugaku'=>'*中[ちゅう]学[がく]', // ➀  junior high
'chuugakusei'=>'*中[ちゅう]学[がく]生[せい]', // ➁うが➁ junior high school student
'chuugoku'=>'*中[ちゅう]国[ごく]', // ➀ China
'chuugokujin'=>'*中[ちゅう]国[ごく]人[じん]', // ➁うごく➁ Chinese
'chuui'=>'*注[ちゅう]意[い]', // ➀ attention, care
'chuukyuu'=>'*中[ちゅう]級[きゅう]', // ⓪ middle-class, intermediate
'chuumoku'=>'*注[ちゅう]目[もく]', // ⓪ attention, notice
'chuumokuohiku'=>'*注[ちゅう]目[もく]を引[ひ]く',
'chuumokudo'=>'*注[ちゅう]目[もく]度[ど]',
'chuumon'=>'*注[ちゅう]文[もん]', // ⓪ order, request; annotation
'chuuou'=>'*中[ちゅう]央[おう]', // ➁うお➁ center, middle
'chuusha'=>'*注[ちゅう]射[しゃ]', // ⓪ injection, shot
'chuusha'=>'*駐[ちゅう]車[しゃ]', // ⓪ parking 
'chuushaihan'=>'*駐[ちゅう]車[しゃ]違[い]反[はん]', // ➁うしゃい➁ parking violation
'chuushakinshi'=>'*駐[ちゅう]車[しゃ]禁[きん]止[し]', // 禁止 ⓪
'chuushajou'=>'*駐[ちゅう]車[しゃ]場[じょう]', // ⓪ parking area, parking lot
'chuushi'=>'*中[ちゅう]止[し]', // ⓪ suspension, cancellation
'chuushin'=>'*中[ちゅう]心[しん]', // ⓪ center (of a circle, etc.), core
'chuushoku'=>'*昼[ちゅう]食[しょく]', // ⓪ lunch
'chuushouteki'=>'*抽[ちゅう]象[しょう]的[てき]', // ⓪ abstract
'dabudabu'=>'*だぶだぶ', // ⓪ baggy, too big
'da'=>'*だ', // ⓪
'dai'=>'*大[だい]:第[だい]:台[だい]',
'daibu'=>'*大[だい]分[ぶ]', // ⓪ greatly, fairly, highly
'daidokoro'=>'*台[だい]所[どころ]', // ⓪ kitchen, financial situation
'daidokoroyohin'=>'*台[だい]所[どころ]用[よう]品[ひん]', // kitchen utensils
'daigaku'=>'*大[だい]学[がく]', // ⓪ university, college
'daigakuin'=>'*大[だい]学[がく]院[いん]', // ➁ graduate school
'daigakusei'=>'*大[だい]学[がく]生[せい]', // ➁ university student
'daihyou'=>'*代[だい]表[ひょう]', // ⓪ representative
'daiji'=>'*大[だい]事[じ]', // ➀ importance; important, valuable
'daijin'=>'*大[だい]臣[じん]', // ➀ (cabinet) minister
'daijoubu'=>'*大[だい]丈[じょう]夫[ぶ]', // ➁いじょ➁ all right, OK
'daikirai'=>'*大[だい]嫌[きら]い', // ➀ hating, strongly disliking
'daikon'=>'*大[だい]根[こん]', // ⓪ oriental radish
'daisuki'=>'*大[だい]好[す]き', // ➀ like something a lot
'daitai'=>'*大[だい]体[たい]', // ⓪ about, anyway, generally
'Daitouryou'=>'*大[だい]統[とう]領[りょう]', // ➁いと➁ president (of a country)
'dame'=>'*駄[だ]目[め]', // ➂ no good, broken
'danbou'=>'*暖[だん]房[ぼう]', // ⓪ heating
'dandan'=>'*段々[だんだん]', // ➀ gradually, little by little
'dankai'=>'*段[だん]階[かい]', // ⓪ stage, phase
'dansei'=>'*男[だん]性[せい]', // ⓪ male, man
'dansu'=>'*ダンス', // dance, dancing (loan word)
'dantai'=>'*団[だん]体[たい]', // ⓪ group, organization
'darashinai'=>'*だらしない', // ➁ untidy, sloppy
'dare'=>'*誰[だれ]', // ➀ who
'dareka'=>'*誰[だれ]か', // ➀ someone
'darui'=>'*だるい', // ➁ 怠い feel run-down, weary, sluggish
'dasu'=>'*出[だ]す', // ➀ take out
'deeto'=>'*デート', // date, romantic meeting
'deau'=>'*出[で]会[あ]う', // ➁ meet, encounter
'deeta'=>'*データ', // ➀ data
'deguchi'=>'*出[で]口[ぐち]', // ➀ exit
'deiriguchi'=>'*出[で]入[い]り口[ぐち]', // ➁いり➁ doorway, gateway
'dekakeru'=>'*出[で]かける', // ⓪ go out, leave home
'dekiru'=>'*できる', // ➁ can do, be good at, be possible
'dekirudake'=>'*できるだけ', // as (much) as possible
'dekoboko'=>'*でこぼこ', // ⓪ 凸凹 unevenness, bumpiness
'denchi'=>'*電[でん]池[ち]', // ➀ battery
'dengon'=>'*伝[でん]言[ごん]', // ⓪ message
'dengon'=>'*伝[でん]言[ごん]板[ばん]', // ⓪ message board
'denki'=>'*電[でん]気[き]', // ➀ electricity, electric light
'densha'=>'*電[でん]車[しゃ]', // ⓪ train
'denshi'=>'*電[でん]子[し]', // ➀ electron, electronic
'dentou'=>'*伝[でん]統[とう]', // ⓪ tradition
'denwa'=>'*電[でん]話[わ]', // ⓪ telephone, phone call
'denwabangou'=>'*電[でん]話[わ]番[ばん]号[ごう]', // ➁ telephone number
'denwabangou'=>'*電[でん]話[わ]番[ばん]号[ごう]簿[ぼ]', // ➁ telephone book
'denwachou'=>'*電[でん]話[わ]帳[ちょう]', // ⓪ telephone book
'depaato'=>'*デパート', // ➁パ➁ department store (loan word)
'dekiru'=>'*出[で]来[き]る', // ➁
'deru'=>'*出[で]る', // go out, leave
'deshita'=>'*でした',
'desu'=>'*です',
'desuka'=>'*ですか',
'desuku'=>'*デスク', // ➀
'dezaato'=>'*デザート', // ➁ザ➁ dessert
'dezain'=>'*デザイン', // ➁ザ➁ design
'do'=>'*土[ど]', // ➀
'doa'=>'*ドア', // door loan word
'docchi'=>'*どっち', // ➀ which casual
'dochira'=>'*どちら', // ➀ which
'Dokidoki'=>'*どきどき', // ➀ feel excited, feel nervous
'dokitto'=>'*どきっと', // ➁き➁ surprised, shocked
'doko'=>'*どこ', // ➀ where
'doku'=>'*どく', // ⓪ 退く get out of the way, step aside
'dokuritsu'=>'*独[どく]立[りつ]', // ⓪ independence, self-reliance
'dokusha'=>'*読[どく]者[しゃ]', // ➀ reader
'dokushin'=>'*独[どく]身[しん]', // ⓪ single, unmarried
'dokusho'=>'*読[どく]書[しょ]', // ➀ reading books
'donata'=>'*どなた', // ➀ who
'dondon'=>'*どんどん', // ➀ knock, bang, quickly, rapidly
'dono'=>'*何[ど]の', // ➀ which 何の銀行
'doraibu'=>'*ドライブ', // ➁ drive 
'dorama'=>'*ドラマ', // ➀ drama
'dore'=>'*どれ', // ➀ what, which
'doresu'=>'*ドレス', // ➀ formal dress
'dorobou'=>'*泥[どろ]', // ➂ mud, dirt, thief, Android 
'dorobou'=>'*泥[どろ]棒[ぼう]', // ⓪ thief, burglar
'doru'=>'*ドル', // ➀ dollar
'doryoku'=>'*努[ど]力[りょく]', // ➀ endeavor, effort
'dodai'=>'*土[ど]台[だい]', // ⓪ foundation, base; basis; from the beginning; from the outset; by nature
'dou'=>'*どう', // ➀ how, what
'doubutsu'=>'*動[どう]物[ぶつ]', // ⓪ animal
'doubutsuen'=>'*動[どう]物[ぶつ]園[えん]', // ➁ zoo
'doujou'=>'*同[どう]情[じょう]', // ⓪ sympathy, compassion
'doumo'=>'*どうも', // ➀ for no special reason, somehow; Bitte sehr!
'dounika'=>'*どうにか', // ➀ somehow
'dounikakounika'=>'*どうにかこうにか', // ➁うにかこ➁ somehow
'douri'=>'*通[どお]り', // ➂ street, road, avenue, thoroughfare
'douryou'=>'*同[どう]僚[りょう]', // ⓪
'douro'=>'*道[どう]路[ろ]', // ➀ road
'douse'=>'*どうせ', // ⓪ anyway
'doushi'=>'*動[どう]詞[し]', // ⓪
'doushite'=>'*どうして', // ➀ 如何して how come
'doushitemo'=>'*どうしても', // ➁うして➁ by any means, really
'douyatte'=>'*どうやって', // how

'douyou'=>'*同[どう]様[よう]', // ⓪ similar, the same as
'douzo'=>'*どうぞ', // ➀ please, here you are
'doyoubi'=>'*土[ど]曜[よう]日[び]', // ➁ Saturday
'douzoyoroshiku'=>'*どうぞよろしく:どうぞよろしくお願い[おねがい]', // please to meet you; please be nice to me
'e'=>'*絵', // ➀ picture, painting
'eakon'=>'*エアコン', // ⓪ air-conditioning, air conditioner
'eameeru'=>'*エアメール', // ➁アメ➁ airmail
'ebi'=>'*えび', // ⓪ 海老，蝦 shrimp, prawn, lobster
'enoku'=>'*絵[え]の具[ぐ]', // ⓪ paint; coloring materials; colors; colours
'ee'=>'*ええ', // ➀
'egaku'=>'*描[えが]く', // ➁ depict, draw
'ehagaki'=>'*絵[え]葉[は]書[がき]', // ➁は➁ picture postcard
'eiga'=>'*映[えい]画[が]', // ➀ movie
'eigakan'=>'*映[えい]画[が]館[かん]', // ➁いが➁ movie theater
'eigo'=>'*英[えい]語[ご]', // ⓪ English
'eigyou'=>'*営[えい]業[ぎょう]', // ⓪ business, sales
'eikyou'=>'*影[えい]響[きょう]', // ⓪ influence, effect
'eki'=>'*駅[えき]', // ➀ train station
'ekiin'=>'*駅[えき]員[いん]', // ➁ station attendant
'ekimae'=>'*駅[えき]前[まえ]', // ➁ in front of the station
'ekimaedoori'=>'*駅[えき]前[まえ]通[どお]り', // ➁きまえど➁ street in front of station
'ekimaehiroba'=>'*駅[えき]前[まえ]広[ひろ]場[ば]', // ➁きまえひ➁ station square; station plaza
'en'=>'*円[えん]', // ➀ circle, Japanese yen
'endaka'=>'*円[えん]高[だか]', // ⓪ strong yen
'enerugii'=>'*エネルギー', // ➁ energy
'enjin'=>'*エンジン', // ➀ engine
'enjinia'=>'*エンジニア', // エ➁ンジ➁ニア
'enjiniaringu'=>'*エンジニアリング', // エ➁ンジニ➁アリング
'enpitsu'=>'*鉛[えん]筆[ぴつ]', // ⓪ 
'enryo'=>'*遠[えん]慮[りょ]', // ⓪ restraint, hold back, modesty; declining; forethought
'ensou'=>'*演[えん]奏[そう]', // ⓪ musical performance
'erabu'=>'*選[えら]ぶ', // ➁ choose, elect
'erai'=>'*偉[えら]い', // ➁ great, eminent; awful, terrible; tough
'erebeetaa'=>'*エレベーター', // ➁レベ➁ elevator
'eru'=>'*得[え]る', // ➀ obtain, gain; understand,
'esukareetaa'=>'*エスカレ─タ─',
'fan'=>'*ファン', // ➀ fan, admirer
'fasshon'=>'*ファッション', // ➀ fashion
'fooku'=>'*フォーク', // ➀ fork
'fuan'=>'*不[ふ]安[あん]', // ⓪ uneasy, worried
'fuben'=>'*不[ふ]便[べん]', // ➀ inconvenient
'fudan'=>'*普[ふ]段[だん]', // ➀ usual, ordinary
'fudan'=>'*普[ふ]段[だん]着[ぎ]', // ➁ everyday clothes; ordinary clothes; casual wear; informal dress
'fudousanya'=>'*不[ふ]動[どう]産[さん]]', // ➁ど➁ real estate agent, realtor
'fudousanya'=>'*不[ふ]動[どう]産[さん]屋[や]', // ⓪ real estate agent, realtor
'fueru'=>'*増[ふ]える', // ➁ increase, accrue
'firumu'=>'*フィルム', // ➀ also フイルム film
'fuji'=>'*富[ふ]士[じ]', // ➀ 
'fujidaigaku'=>'*富[ふ]士[じ]大[だい]学[がく]',
'fukai'=>'*深[ふか]い', // ➁ deep, profound
'fukasa'=>'*深[ふか]さ', // ➁ depth, profundity
'fukushuu'=>'*復[ふく]習[しゅう]', // ⓪ review
'fukuzatsu'=>'*複[ふく]雑[ざつ]', // ⓪ complicated, intricate
'fukanou'=>'*不[ふ]可[か]能[のう]', // ➁ impossible
'fukanou'=>'*不[ふ]可[か]能[のう]性[せい]', // ⓪ impossibility
'fukou'=>'*不[ふ]幸[こう]', // ➁ unhappiness, misfortune
'fuku'=>'*吹[ふ]く:拭[ふ]く:服[ふく]', // ➀:⓪:➂ blow, play (a wind instrument); to wipe, to dry; clothes
'fukumeru'=>'*含[ふく]める', // ➁ include
'fukumu'=>'*含[ふく]む', // ➁ contain, include
'fukuro'=>'*袋[ふくろ]', // ➂ bag, sack
'fukushi'=>'*副[ふく]詞[し]', // ⓪
'fumi'=>'*文[ふみ]:書[ふみ]', // ➀ letter, mail, book, sentence
'fun'=>'*分[ふん]:分[ぷん]', // ➀
'fune'=>'*船[ふね]', // ➀
'furo'=>'*風[ふ]呂[ろ]', // ➂ bath
'furu'=>'*振[ふ]る:降[ふ]る', // ➀:➀ wave, shake; fall, come down rain, snow, etc.
'furui'=>'*古[ふる]い', // ➂ old
'futari'=>'*二[ふた]人[り]', // ➂ two persons
'futatsu'=>'*二[ふた]つ', // ➂ two things
'futoi'=>'*太[ふと]い', // ➁ thick, fat
'futsuka'=>'*二日[ふつか]', // ⓪ two days, second of the month
'futsuu'=>'*普[ふ]通[つう]', // ⓪ normal, regular, ordinary
'fuufu'=>'*夫[ふう]婦[ふ]', // ➀ husband and wife, married couple
'fuyasu'=>'*増[ふ]やす', // ➁ increase
'fuyu'=>'*冬[ふゆ]', // ➂ winter
'gaikoku'=>'*外[がい]国[こく]', // ⓪ foreign country



'gaikokujin'=>'*外[がい]国[こく]人[じん]', // foreigner
'gakkou'=>'*学[がっ]校[こう]', // school
'gakusei'=>'*学[がく]生[せい]', // student
'ganbaru'=>'*頑張る[がんばる]', // work hard, do one’s best
'garasu'=>'*ガラス', // glass material
'gasu'=>'*ガス', // gas loan word
'gatsu'=>'*月[がつ]',

'geemu'=>'*ゲーム', // game
'genkan'=>'*玄関[げんかん]', // entrance, door
'genki'=>'*元[げん]気[き]', // ➀ healthy, energetic
'getsu'=>'*月[げつ]', // ➀
'getsumatsu'=>'*月[げつ]末[まつ]', // ⓪
'getsuyoubi'=>'*月[げつ]曜[よう]日[び]', // Monday
'gekkyou'=>'*月[げっ]給[きゅう]', // ⓪ monthly salary
'genki'=>'*元[げん]気[き]', // ➀ lively, healthy
'geppu'=>'*月[げっ]賦[ぷ]', // ⓪ monthly installment
'gesshoku'=>'*月[げっ]食[しょく]', // ⓪  月蝕 lunar eclipse
'gin'=>'*銀', // ➀
'ginkou'=>'*銀[ぎん]行[こう]', // bank
'ginkouin'=>'*銀[ぎん]行[こう]員[いん]',
'go'=>'*ご:五[ご]', // five
'gochisou'=>'*ごちそう', // feast, treat
'gochisousuru'=>'*ごちそうする', // treat, host a meal
'gogo'=>'*午[ご]後[ご]', // afternoon, p.m.
'gohan'=>'*ご飯[はん]:御[ご]飯[はん]:誤[ご]判[はん]', // ➀ meal, cooked rice; ⓪
'gohandoki'=>'*ご飯[はん]時[どき]', // ⓪ mealtime
'gohanya'=>'*ご飯[はん]屋[や]', // ⓪ eatery, restaurant
'gohyaku'=>'*五[ご]百[ひゃく]',
'gojuu'=>'*五[ご]十[じゅう]',
'gokazoku'=>'*ご家[か]族[ぞく]', // family, household

'goman'=>'*五[ご]万[まん]',
'gonin'=>'*五[ご]人[にん]',
'gorufu'=>'*ゴルフ', // golf
'goryoushin'=>'*ご両[りょう]親[しん]', // ➁ 御両親 someone else's parents
'gosen'=>'*五[ご]千[せん]',
'goshujin'=>'*ご主[しゅ]人[じん]', // someone else’s husband
'goukaku'=>'*合[ごう]格[かく]', // pass an examination
'gozen'=>'*午[ご]前[ぜん]', // morning, a.m.
'guruupu'=>'*グループ', // group

'gyou'=>'*行[ぎょう]', // today
'gyuuniku'=>'*牛[ぎゅう]肉[にく]', // beef
'ha'=>'*は:歯[は]', // ➀ tooth
'haburashi'=>'*歯[は]ブラシ', // toothbrush
'hachi'=>'*八[はち]', // ➂ eight
'hachiman'=>'*八[はち]万[まん]',
'hachinin'=>'*八[はち]人[にん]',
'hagemasu'=>'*励[はげ]ます', // encourage, cheer up
'haha'=>'*母[はは]', // ➀ speaker’s mother
'hai'=>'*はい:杯[はい]',
'hairu'=>'*入[はい]る', // enter
'hajimaru'=>'*始[はじ]まる', // begin
'hajime'=>'*初[はじ]め', // beginning
'hajimeni'=>'*初[はじ]めに', // beginning
'hajimemashite'=>'*初[はじ]めまして', // I am meeting you for the first time
'hajimeru'=>'*始[はじ]める', // start something
'hajimete'=>'*初[はじ]めて', // for the first time
'hakkiri'=>'*はっきり', // clearly
'hakobu'=>'*運[はこ]ぶ', // carry, transport
'haku'=>'*履[は]く:拍[はく]', // ⓪ put on shoes, wear pants, skirt; ➀ mora
'han'=>'*半[はん]',
'hana'=>'*花[はな]:鼻[はな]', // ➂ flower; ⓪ nose
'hanashi'=>'*話[はなし]', // ➂ talk, story
'hanashiau'=>'*話[はな]し合[あ]う', // discuss, talk over
'hanasu'=>'*話[はな]す', // ➁ speak, talk
'hanbun'=>'*半[はん]分[ぶん]', // half, half minute
'hankachi'=>'*ハンカチ', // handkerchief
'hannichi'=>'*半[はん]日[にち]', // half a day
'hantai'=>'*反[はん]対[たい]', // oppose, object
'hanteisuru'=>'*判[はん]定[てい]する', // ⓪
'hantsuki'=>'*半[はん]月[つき]', // half a month
'happyaku'=>'*八[はっ]百[ぴゃく]',
'harau'=>'*払[はら]う', // pay money, respect, attention, etc.
'hare'=>'*晴[は]れ', // fine weather, clear sky
'hareru'=>'*晴[は]れる', // be sunny, clear up
'haru'=>'*春[はる]', // spring
'hashi'=>'*橋[はし]:箸[はし]', // bridge
'hashiru'=>'*走[はし]る', // run
'hasseisuru'=>'*発[はっ]生[せい]する', // ⓪
'hassen'=>'*八[はっ]千[せん]',
'hatarakimasu'=>'*働[はたら]きます', // work
'hataraku'=>'*働[はたら]く', // work
'hatsuon'=>'*発[はつ]音[おん]', // ⓪
'hatsuka'=>'*二十日[はつか]', // days, 20th of the month
'hayai'=>'*早[はや]い:速[はや]い', // ➁ early; ➁ fast
'hayaku'=>'*早[はや]く', // early, soon
'hayaru'=>'*流行[はや]る', // be in fashion, be popular
'heisei'=>'*平[へい]成[せい]', // ⓪ Heisei era
'heiwa'=>'*平[へい]和[わ]', // peace, harmony
'henkansuru'=>'*変[へん]換[かん]する', // ⓪
'henko'=>'*変[へん]更[こう]', // ⓪
'henji'=>'*返[へん]事[じ]', // ➂ reply, answer, response
'heru'=>'*減[へ]る', // decrease, diminish
'heta'=>'*下手[へた]', // ➂ not good at, poor, awkward
'heya'=>'*部屋[へや]', // ➂ room
'hi'=>'*ひ:火[ひ]', // fire, flame
'hidari'=>'*左[ひだり]', // left
'hidarigawa'=>'*左[ひだり]側[がわ]', // left side
'higashi'=>'*東[ひがし]', // east, eastern
'hiji'=>'*肘[ひじ]', // elbow
'hijouni'=>'*非[ひ]常[じょう]に', // very, extremely
'hiki'=>'*匹[ひき]', // insects, cats, dogs, etc
'hikouki'=>'*飛[ひ]行[こう]機[き]', // airplane
'hiku'=>'*引[ひ]く', // draw, pull
'hikui'=>'*低[ひく]い', // low, short
'himitsu'=>'*秘[ひ]密[みつ]', // secret, privacy
'hinshi'=>'*品[ひん]詞[し]', // ⓪ part of speech
'hinshibunrui'=>'*品[ひん]詞[し]分[ぶん]類[るい]', // ⓪ part of speech
'hiragana'=>'*平[ひら]仮[が]名[な]', // hiragana
'hiraku'=>'*開[ひら]く', // sich öffnen
'hiro'=>'*疲[ひ]労[ろう]', // ⓪
'hirosuru'=>'*疲[ひ]労[ろう]する', // ⓪
'hiroba'=>'*広[ひろ]場[ば]', // ➀
'hiroi'=>'*広[ひろ]い', // wide, big
'hiroshima'=>'*広[ひろ]島[しま]', // ⓪
'hiru'=>'*昼[ひる]', // daytime, midday
'hiruma'=>'*昼[ひる]間[ま]', // ➂ daytime, during the day
'hiruyasumi'=>'*昼[ひる]休[やす]み', // ➁るや➁ lunch break


'hito'=>'*人[ひと]', // person
'hitori'=>'*一人[ひとり]', // one person
'hitoride'=>'*一人で[ひとりで]', // by oneself, alone
'hitotsu'=>'*一つ[ひとつ]', // one thing
'hitsuyou'=>'*必要[ひつよう]', // need, necessary
'hiza'=>'*膝[ひざ]', // knee
'hojisuru'=>'*保[ほ]持[じ]する', // ➀
'hoka'=>'*他[ほか]', // other Japanese origin
'hon'=>'*本[ほん]', // book, volume
'honkon'=>'*ホンコン', // ①
'hontou'=>'*本当[ほんとう]', // reality, genuine
'hontouni'=>'*本当に[ほんとうに]', // really, truly
'honya'=>'*本屋[ほにゃ]', // bookstore
'hoshii'=>'*欲[ほ]しい', // ➁ want, desire of the speaker 車が欲しい
'hosoi'=>'*細い[ほそい]', // thin, slender
'hoteru'=>'*ホテル', // hotel
'hotondo'=>'*ほとんど', // almost, hardly
'hou'=>'*方[ほう]', // direction, side
'houhou'=>'*方[ほう]法[ほう]', // ⓪
'houhouron'=>'*方[ほう]法[ほう]論[ろん]', // ➁うほ➁

'houkou'=>'*方向[ほうこう]', // direction, course
'hozonsuru'=>'*保[ほ]存[ぞん]する', // ⓪
'hyaku'=>'*百[ひゃく]', // ➂ hundred
'hyoujisuru'=>'*表[ひょう]示[じ]する', // ⓪
'icchisuru'=>'*一[いっ]致[ち]する', // ⓪ einig sein

'ichi'=>'*一[いち]:位置[いち]', // ➂ one; ➀ 
'ichiban'=>'*一番[いちばん]', // most, best
'ichibanme'=>'*一[いち]番[ばん]目[め]', // ➂ first
'ichibu'=>'*一部[いちぶ]', // part
'ichiman'=>'*一[いち]万[まん]',
'idousuru'=>'*移[い]動[どう]する', // ⓪
'ie'=>'*家[いえ]', // ➂ home, household
'igai'=>'*以外[いがい]', // except for
'ii'=>'*いい', // good in/spoken form
'iie'=>'*いいえ', // good in/spoken form
'ijou'=>'*以上[いじょう]', // more than, not less than
'iken'=>'*意見[いけん]', // opinion
'ikiru'=>'*生きる[いきる]', // live one’s life
'ikko'=>'*一[いっ]個[こ]',
'ikimasu'=>'*行[い]きます', // ⓪ go 
'iku'=>'*行[い]く', // ⓪ go
'ikura'=>'*いくら', //  ➀ 幾ら how much money
'ikutsu'=>'*幾[いく]つ', // how many, how old
'ima'=>'*今[いま]:居[い]間[ま]', // ➀ now; ⓪ sitting room (western)
'imi'=>'*意味[いみ]', // meaning, sense
'imomushi'=>'*芋[いも]虫[むし]', // ➁ caterpillar
'imouto'=>'*妹[いもうと]', // ➂ younger sister
'infureeshon'=>'*インフレーション', // ➁ンフレ➁ inflation
'inu'=>'*犬[いぬ]', // dog
'ippai'=>'*いっぱい', // full
'ippiki'=>'*一[いっ]匹[ぴき]', // ➂
'irasshaimase'=>'*いらっしゃいませ',// ➁
'ireru'=>'*入れる[いれる]', // put in
'iriguchi'=>'*入[い]り口[ぐち]', // ⓪
'iro'=>'*色[いろ]', // ➂ color
'iroiro'=>'*色々[いろいろ]', // ⓪ a variety of
'ironna'=>'*いろんな', // ⓪ various; a variety of; all sorts of; many (different)
'iru'=>'*居[い]る:要[い]る', // ⓪ be present, stay, exist; brauchen
'isha'=>'*医[い]者[しゃ]', // ⓪ doctor
'isogashii'=>'*忙[いそが]しい', // busy, occupied
'isogu'=>'*急[いそ]ぐ', // hurry, do quickly
'issho'=>'*一[いっ]緒[しょ]', // together, same
'issho'=>'*一[いっ]緒[しょ]に', // together, at the same time
'isu'=>'*椅[い]子[す]', // chair
'itai'=>'*痛[いた]い', // sore, painful
'itazura'=>'*いたずら', // mischief, prank
'itoko'=>'*いとこ', // cousin
'itsu'=>'*いつ', // ➀ 何時 when, at what time
'itsugoro'=>'*いつ頃[ごろ]', // about when, about what time
'itsuka'=>'*いつか', // some time, some day
'itsuka'=>'*五日[いつか]', // ➂ five days, fifth of the month
'itsumo'=>'*いつも', // always
'iu'=>'*言[い]う', // ⓪ say, tell
'iwayuru'=>'*いわゆる', // ➁ 所謂
'iya'=>'*嫌[いや]', // ➂ dislike
'jaarimasen'=>'*じゃありません',
'jagaimo'=>'*ジャガイモ', // ⓪ potato
'ji'=>'*じ:字[じ]:時[じ]', // individual character, letter
'jibun'=>'*自[じ]分[ぶん]', // ⓪ self, oneself, myself
'jidai'=>'*時[じ]代[だい]', // ⓪ age, era, oldness, antique
'jidai'=>'*時[じ]代[だい]物[もの]', // ⓪ antique; pre-Meiji period drama; period piece
'jidaigeki'=>'*時[じ]代[だい]劇[げき]', // ➁だ➁ historical play; period drama

'jidouhanbaiki'=>'自[じ]動[どう]販[はん]売[ばい]機[き]', // ➁どうはんば➁
'jidousha'=>'*自[じ]動[どう]車[しゃ]', // ➁ど➁ automobile
'jikan'=>'*時[じ]間[かん]', // ⓪ time, hour
'jikan'=>'*時[じ]間[かん]割[わり]', // ⓪ School timetable
'jikkousuru'=>'*実[じっ]行[こう]する', // ⓪ execute
'jiko'=>'*事[じ]故[こ]', // ➀ accident, trouble
'jikoku'=>'*時[じ]刻[こく]', // ➀ time, hour, favourable time; opportunity; chance
'jikokuhyou'=>'*時[じ]刻[こく]表[ひょう]', // ⓪ timetable; schedule
'jikyou'=>'*時[じ]給[きゅう]', // ⓪ hourly pay, hourly wage, hourly rate
'jiryou'=>'*時[じ]流[りゅう]', // ⓪ fashion (current) of the times; general drift of affairs, market trend
'jimusho'=>'*事[じ]務[む]所[しょ]', // ➁む➁ office, one’s place of business
'jin'=>'*人[じん]', // pitch becomes ➁
'jinja'=>'*神[じん]社[じゃ]', // ➀
'jisa'=>'*時[じ]差[さ]', // ➀ time difference
'jishin'=>'*地[じ]震[しん]', // earthquake
'jisho'=>'*辞[じ]書[しょ]', // ➀ dictionary category
'jisoku'=>'*時[じ]速[そく]', // ➀
'jissai'=>'*実[じっ]際[さい]', // ➀ reality, actual state
'jitaku'=>'*自[じ]宅[たく]', // ⓪ one’s house, one’s home
'jiten'=>'*時[じ]点[てん]', // ➀ point in time; occasion
'jitensha'=>'*自[じ]転[てん]車[しゃ]', // ⓪ bicycle
'jiyuu'=>'*自由[じゆう]', // freedom
'jodoushi'=>'*助[じょ]動[どう]詞[し]', // ➁
'josei'=>'*女[じょ]性[せい]', // ⓪ woman, female
'joubu'=>'*丈[じょう]夫[ぶ]', // ➀ healthy, sturdy
'joshi'=>'*助[じょ]詞[し]', // ⓪
'jouzu'=>'*上[じょう]手[ず]', // ➂ good, skilled
'junbi'=>'*準[じゅん]備[び]', // ➀ preparation, arrangement
'juu'=>'*十[じゅう]', // ➀ ten
'juubun'=>'*十[じゅう]分[ぶん]', // ➁ enough plentiful
'juugyo'=>'*授[じゅう]業[ぎょ]', // ➀ class session, lecture
'juunin'=>'*十[じゅう]人[にん]', // ➀
'juusho'=>'*住[じゅう]所[しょ]', // address
'ka'=>'*か:課[か]', // ➂
'kaado'=>'*カード', // ➀
'kaban'=>'*かばん', // ⓪ 鞄 bag, handbag
'kabe'=>'*壁[かべ]', // ⓪ wall, partition
'kaburu'=>'*被[かぶ]る', // ➁ wear, put on on one’s head
'kadai'=>'*課[か]題[だい]', // ⓪ task, assignment
'kaerimasu'=>'*帰[かえ]ります', // ➀ go back home
'kaeru'=>'*帰[かえ]る:変[か]える', // ➀:⓪ go back home; to change, to alter, to transform, to reform
'kaesu'=>'*返[かえ]す', // ➀ return, repay
'kagaku'=>'*科[か]学[がく]', // ➀ science
'kagi'=>'*鍵[かぎ]', // ➂ key, lock
'kai'=>'*会[かい]:階[かい]:階[がい]', // ➀:➀:➀
'kaidan'=>'*階[かい]段[だん]', // ⓪ stairs, stairway
'kaigai'=>'*海[かい]外[がい]', // ➀ overseas, abroad
'kaigan'=>'*海[かい]岸[がん]', // ⓪ seashore, coast
'kaigi'=>'*会[かい]議[ぎ]', // ➀ conference, meeting
'kaigishitsu'=>'*会[かい]議[ぎ]室[しつ]', // ➁いぎ➁ conference, meeting
'kaimasu'=>'*買[か]います',
'kaimono'=>'*買[か]い物[もの]', // ⓪ shopping, purchase
'kaisatsuguchi'=>'*改[かい]札[さつ]口[ぐち]', // ➁いさつ➁ ticket gate
'kaisha'=>'*会[かい]社[しゃ]', // ⓪ company, corporation
'kaishain'=>'*会[かい]社[しゃ]員[いん]', // ➁ company employee
'kaisou'=>'*回[かい]想[そう]', // ⓪ recollection; retrospection; reflection; reminiscence
'kaisouki'=>'*回[かい]想[そう]記[き]', // ➁いそ➁ memoir


'kaiwa'=>'*会[かい]話[わ]', // ⓪
'kakageru'=>'*掲[かか]げる', // ⓪
'kakeru'=>'*掛[か]ける', // ➁ hang, put on
'kangoshi'=>'*看[かん]護[ご]師[し]', // ➁んご➁ nurse
'kaku'=>'*書[か]く', // ➀ write
'kakunin'=>'*確[かく]認[にん]', // ⓪ confirmation
'kamera'=>'*カメラ', // ➀ camera
'kami'=>'*紙[かみ]', // ➂ paper
'kami'=>'*髪[かみ]', // ➂ hair, hairstyle
'kamigata'=>'*髪[かみ]型[がた]', // ⓪
'kaminoke'=>'*髪[かみ]の毛[け]', // ➁みの➁ hair, each single hair
'kana'=>'*仮[か]名[な]', // ⓪
'kanai'=>'*家[か]内[ない]', // ➀ speaker's wife
'kanarazu'=>'*必[かなら]ず', // ⓪ without exception, always
'kanari'=>'*かなり', // ➀ fairly, rather
'kanashii'=>'*悲[かな]しい', // ⓪ sad
'kandoushi'=>'*感[かん]動[どう]詞[し]', // ➁ interjection

'kane'=>'*金[かね]', // ⓪ Metall, Geld
'kangae'=>'*考[かんが]え', // ➁んが➁ thought, idea
'kangaeru'=>'*考[かんが]える', // ➁んがえ➁ 勘える think, consider
'kanji'=>'*漢[かん]字[じ]', // ⓪
'kanjiru'=>'*感[かん]じる', // ⓪ feel, sense
'kankokugo'=>'*韓[かん]国[こく]語[ご]',
'kannou'=>'*可[か]能[のう]', // ⓪
'kannousei'=>'*可[か]能[のう]性[せい]', // ⓪
'kanojo'=>'*彼[かの]女[じょ]', // ➀ she, one's girlfriend
'kanojora'=>'*彼[かの]女[じょ]自[じ]身[しん]', // herself, she herself
'kanojora'=>'*彼[かの]女[じょ]ら', // they, them

'kanrensuru'=>'*関[かん]連[れん]する', // ⓪ zusammenhängen
'kanrisuru'=>'*管[かん]理[り]する', // ➀
'kantan'=>'*簡[かん]単[たん]', // ⓪ simple, easy
'kantoushi'=>'*間[かん]投[とう]詞[し]', // ➁ interjection
'kao'=>'*顔[かお]', // ⓪ face
'kasuru'=>'*化[か]する', // ➁




'kara'=>'*から', // アメリカから，これから
'karada'=>'*体[からだ]', // body, physique
'karai'=>'*辛[から]い', // spicy, hot
'kare'=>'*彼[かれ]', // he, one’s boyfriend
'karera'=>'*彼[かれ]ら', // they
'kariru'=>'*借[か]りる', // borrow
'karui'=>'*軽[かる]い', // light of weight
'kasa'=>'*傘[かさ]', // umbrella, parasol
'kata'=>'*方[かた]:肩[かた]', // direction, person, shoulder
'katai'=>'*固い[かたい]', // stiff, tight
'katakana'=>'*カタカナ', // katakana
'katei'=>'*家庭[かてい]', // home, family
'katsu'=>'*勝つ[かつ]', // win
'kau'=>'*買う[かう]', // ⓪ buy
'kawa'=>'*川[かわ]', // river, stream
'kawaii'=>'*可愛い[かわいい]', // ➁わい➁ cute, sweet
'kawaku'=>'*乾く[かわく]', // become dry
'kawaku'=>'*渇く[かわく]', // be thirsty
'kawaru'=>'*代わる[かわる]', // substitute, be substituted for
'kawaru'=>'*変わる[かわる]', // change, turn into
'kayou'=>'*通う[かよう]', // go to and from, frequent a place
'kayoubi'=>'*火[か]曜[よう]日[び]', // Tuesday
'kazaru'=>'*飾る[かざる]', // decorate
'kaze'=>'*風[かぜ]', // wind
'kaze'=>'*風邪[かぜ]', // cold illness
'kazegusuri'=>'*風邪薬[かぜぐすり]', // cold medicine
'kazoku'=>'*家[か]族[ぞく]', // ➀ family, household
'kazokukeikaku'=>'*家[か]族[ぞく]計[けい]画[かく]', // ➁ぞくけ➁ family planning

'kazoku'=>'*家[か]族[ぞく]旅[りょ]行[こう]', // family vacation; family trip
'kei'=>'*兄[けい]', // ➀
'keigo'=>'*敬[けい]語[ご]', // ⓪ honorific
'keiken'=>'*経[けい]験[けん]', // ⓪ experience, knowledge
'keisatsu'=>'*警[けい]察[さつ]', // ⓪ police
'keitai'=>'*携[けい]帯[たい]', // ⓪ cellular phone
'keitaidenwa'=>'*携[けい]帯[たい]電[でん]話[わ]', // ➁いたいで➁ cellular phone
'keiyou'=>'*形[けい]容[よう]', // ⓪
'keiyoudoushi'=>'*形[けい]容[よう]動[どう]詞[し]', // ➁いようど➁
'keiyoushi'=>'*形[けい]容[よう]詞[し]', // ➁いよ➁
'kekkon'=>'*結婚[けっこん]', // marriage
'kenka'=>'*喧嘩[けんか]', // fight, argument
'kenkou'=>'*健康[けんこう]', // health
'kenkyuu'=>'*研[けん]究[きゅう]', // ⓪
'kenkyuuin'=>'*研[けん]究[きゅう]員[いん]:研[けん]究[きゅう]院[いん]', // ⓪
'kenkyuusha'=>'*研[けん]究[きゅう]者[しゃ]', // ➁んきゅ➁
'kenkyuusuru'=>'*研[けん]究[きゅう]する', // ⓪
'keredo'=>'*けれど', // ➀ but; however; although
'keredomo'=>'*けれども', // ➀ but; however; although
'kesa'=>'*今朝[けさ]', // this morning
'kesu'=>'*消す[けす]', // switch off, turn off
'ki'=>'*き:木[き]', // tree, wood
'kibishii'=>'*厳[きび]しい', // strict, severe
'kieru'=>'*消[き]える', // be extinguished, disappear
'kigaeru'=>'*着[き]替[が]える', // ➁ change clothes
'kihon'=>'*基[き]本[ほん]', // ⓪ basics
'kiiro'=>'*黄色[きいろ]', // yellow color
'kiiro'=>'*黄色い[きいろ]', // yellow
'kikai'=>'*機械[きかい]', // machine
'kikan'=>'*期間[きかん]', // term, period
'kiken'=>'*危険[きけん]', // danger, dangerous
'kikoeru'=>'*聞こえる[きこえる]', // hear, be heard
'kikoku'=>'*帰国[きこく]', // return to one’s country
'kiku'=>'*聞く[きく]', // hear, ask
'kimaru'=>'*決まる[きまる]', // be decided
'kimeru'=>'*決める[きめる]', // decide, agree upon
'kimashita'=>'*来[き]ました',
'kimi'=>'*君[きみ]:気味[きみ]:黄身[きみ]:鬼魅[きみ]', // egg yolk
'kimitsu'=>'*機密[きみつ]',
'kimochi'=>'*気持ち[きもち]', // feeling, sensation
'kinou'=>'*昨日[きのう]', // ➁⓪ yesterday
'kinshi'=>'*近[きん]視[し]:禁[きん]止[し]', // ⓪;⓪
'kinyoubi'=>'*金[きん]曜[よう]日[び]', // Friday
'kirai'=>'*嫌い[きらい]', // dislike habitual
'kirei'=>'*綺[き]麗[れい]', // ➀ pretty, clean
'kireru'=>'*切れる[きれる]', // cut well, be sharp
'kimasu'=>'*来[き]ます', // ➀:➀ cut

'kiokusuru'=>'*記[き]憶[おく]する', // ⓪


'kiru'=>'*来[き]る:切る[きる]', // ➀:➀ cut
'kiru'=>'*着る[きる]', // wear, put on
'kisetsu'=>'*季節[きせつ]', // season
'kita'=>'*北[きた]', // north
'kitanai'=>'*汚い[きたない]', // dirty
'kitasu'=>'*来[きた]す',
'kitte'=>'*切手[きって]', // postage stamp
'kiwotsukeru'=>'*気を付ける[きをつける]', // be careful about, pay attention to
'ko'=>'*こ:子[こ]', // young child, kid
'koboreru'=>'*こぼれる', // spill, overflow
'kochi'=>'*こっち', // here, this way casual
'kochira'=>'*こちら', // here, this way, this one, this person
'kochirakoso'=>'*こちらこそ', // it is I who should say so
'kodomo'=>'*子供[こども]', // child
'koe'=>'*声[こえ]', // voice, sound
'koko'=>'*ここ', // here
'kokonoka'=>'*九日[ここのか]', // nine days, ninth of the month
'kokonotsu'=>'*九つ[ここのつ]', // nine things
'kokoro'=>'*心[こころ]', // ➂
'kokosei'=>'*高校生[ここせい]', // high school student
'kokusai'=>'*国際[こくさい]', // international
'komakai'=>'*細かい[こまかい]', // minute, fine
'komaru'=>'*困る[こまる]', // be in trouble, not know what to do
'kome'=>'*米[こめ]', // rice grain
'konban'=>'*今[こん]晩[ばん]', // this evening, tonight
'konbanwa'=>'*こんばんは', // this evening, tonight

'kondo'=>'*今[こん]度[ど]', // this time, next time
'kongetsu'=>'*今[こん]月[げつ]', // this month
'konichiwa'=>'*こんにちは',
'konkai'=>'*今[こん]回[かい]', // this time
'konna'=>'*こんな', // ⓪ this sort of; this kind of; like this; such
'konnani'=>'*こんなに', // ⓪ so, like this, in this way, this much, to this extent
'konnen'=>'*今[こん]年[ねん]', // ➀
'konnendo'=>'*今[こん]年[ねん]度[ど]', // ➁
'kono'=>'*この', // ⓪
'konogoro'=>'*この頃[このごろ]', // these days, recently
'konpuutaa'=>'*コンピューター',
'konpyuutaa'=>'*コンピューター', // computer
'konshyu'=>'*今週[こん]sひゅ', // this week
'konya'=>'*今夜[こにゃ]', // tonight, this evening
'koohii'=>'*コーヒー', // coffee
'koosu'=>'*コース', // course, route
'koppu'=>'*コップ', // cup, glass
'kore'=>'*これ', // this, this one
'korekara'=>'*此[こ]れから', // from now on, after this
'korera'=>'*これら', // these
'korosu'=>'*殺す[ころす]', // kill
'koshi'=>'*腰[こし]', // waist, lower back
'koshou'=>'*故障[こしょう]', // malfunction, breakdown
'kotae'=>'*答え[こたえ]', // answer, solution
'kotaeru'=>'*答える[こたえる]', // give an answer
'kotoba'=>'*言葉[ことば]', // word, language

'kotonaru'=>'*異[こと]なる', // ➁とな➁ differ



'kotoshi'=>'*今年[ことし]', // ⓪ this year
'kou'=>'*こう', //  ⓪ 斯う like this, such
'koudou'=>'*行[こう]動[どう]', // ⓪ action; Behavior

'kouen'=>'*公[こう]園[えん]', // ⓪ park, public garden
'koukou'=>'*高[こう]校[こう]', // ⓪ high school for short
'koukyuu'=>'*高[こう]級[きゅう]', // ⓪ high-class, high-quality, high-ranking
'koukyuusha'=>'*高[こう]級[きゅう]車[しゃ]', // ➁うきゅ➁
'koukyuujuutakuchi'=>'*高[こう]級[きゅう]住[じゅう]宅[たく]地[ち]',
'koukyuuhin'=>'*高[こう]級[きゅう]品[ひん]', // ⓪
'koukyuugango'=>'*高[こう]級[きゅう]言[げん]語[ご]', // (computing) high-level language
'koukyuutan'=>'*高[こう]級[きゅう]店[てん]', // 店➂
'koushinsuru'=>'*更[こう]新[しん]する', // ⓪


'kowareru'=>'*壊れる[こわれる]', // break, break down
'ku'=>'*く:九[く]',
'kubi'=>'*首[くび]', // neck
'kuchi'=>'*口[くち]', // mouth
'kudasai'=>'*ください', // ➁ please give me
'kumo'=>'*雲[くも]', // cloud
'kumori'=>'*曇り[くもり]', // cloudy weather
'kumoru'=>'*曇る[くもる]', // become cloudy
'kuni'=>'*国[くに]', // ⓪ country
'kuraberu'=>'*比べる[くらべる]', // compare, contrast
'kurai'=>'*暗い[くらい]', // dark, gloomy
'kurasu'=>'*クラス', // class in school
'kureru'=>'*くれる', // be given
'kuriiningu'=>'*クリーニング', // dry cleaning
'kurikaesu'=>'*繰り返す[くりかえす]', // repeat

'kuroi'=>'*黒[くろ]い', // ➁ black, dark
'kumasu'=>'*来[く]ます', // come
'kuru'=>'*来[く]る', // ➀ come
'kuruma'=>'*車[くるま]', // car, automobile
'kurushii'=>'*苦[くる]しい', // painful, agonizing
'kushi'=>'*くし', // comb
'kusuri'=>'*薬[くすり]', // drug, medicine
'kutsu'=>'*靴[くつ]', // ➂
'kutsushita'=>'*靴[くつ]下[した]', // socks
'kuuki'=>'*空気[くうき]', // air, atmosphere

'kuukou'=>'*空[くう]港[こう]', // ⓪ airport for public transportation
'kuunin'=>'*九[きゅう]人[にん]',
'kuwashii'=>'*詳[くわ]しい', // ➁わし➁ detailed
'kyaku'=>'*客[きゃく]:脚[きゃく]', // ⓪:➀ visitor, customer;脚 used for chairs and seats
'kyakuhon'=>'*脚[きゃく]本[ほん]', // ⓪
'kyakushoku'=>'*脚[きゃく]色[しょく]', // ⓪
'kyou'=>'*教[きょ]う', // ⓪
'kyou'=>'*教[きょう]育[いく]', // ⓪
'kyoku'=>'*曲[きょく]', // ⓪ piece of music
'kyonen'=>'*去[きょ]年[ねん]', // ➀ last year
'kyoushitsu'=>'*教[きょう]室[きょうしつ]', // ⓪
'kyou'=>'*今日[きょう]', // ➀ today
'kyoudai'=>'*兄[きょう]弟[だい]', // ➀ sibling
'kyouju'=>'*教[きょう]授[じゅ]', // ⓪ professor
'kyoukasho'=>'*教[きょう]科[か]書[しょ]', // ➁ textbook, schoolbook
'kyoushi'=>'*教[きょう]師[し]', // ➀ teacher, instructor
'kyoushitsu'=>'*教[きょう]室[しつ]', // ⓪ classroom, class
'kyuu'=>'*九[きゅう]', // ➀ nine used before counter words
'kyuuhyaku'=>'*九[きゅう]百[ひゃく]',
'kyuukou'=>'*急[きゅう]行[こう]', // ⓪ hurrying; express
'kyuukou'=>'*急[きゅう]行[こう]便[びん]', // express mail
'kyuukouressha'=>'*急[きゅう]行[こう]列[れっ]車[しゃ]', // ➁うこうれ➁
'kyuukouteishaeki'=>'*急[きゅう]行[こう]停[てい]車[しゃ]駅[えき]', // 
'kyoukyuusuru'=>'*供[きょう]給[きゅう]する', // ⓪
'kyuuni'=>'*急[きゅう]に', // ⓪ suddenly, unexpectedly

'kyuuryou'=>'*給[きゅう]料[りょう]', // salary, pay
'kyuuman'=>'*九[きゅう]万[まん]',
'kyuusen'=>'*九[きゅう]千[せん]',
'maamaa'=>'*まあまあ', // ➀ OK, not bad
'machi'=>'*町[まち]', // town, city
'machigaeru'=>'*間[ま]違[ちが]える', // ➁ make a mistake, fail at
'mada'=>'*まだ', // ➀ not yet, still
'made'=>'*まで', // ⓪ 迄
'mado'=>'*窓[まど]', // ➀ window
'mae'=>'*前[まえ]', // ➀ front, before
'magarikado'=>'*曲[ま]がり角[かど]', // ➁ corner, turn, bend, turning point
'magaru'=>'*曲[ま]がる', // ⓪ make a turn, turn
'mago'=>'*孫[まご]', // ➂ grandchild
'mai'=>'*毎[まい]:枚[まい]',
'maiasa'=>'*毎[まい]朝[あさ]', // ➀
'maiban'=>'*毎[まい]晩[ばん]', // ➀
'maitonen'=>'*毎[まい]年[ねん]', // ⓪ every year
'mainichi'=>'*毎[まい]日[にち]', // ➀ every day
'maishuu'=>'*毎[まい]週[しゅう]', // ⓪
'maitoshi'=>'*毎[まい]年[とし]', // ⓪ every year
'maitsuki'=>'*毎[まい]月[つき]', // ⓪ every month
'makao'=>'*マカオ', // ➀ Macao
'makeru'=>'*負[ま]ける', // ⓪ lose
'makura'=>'*枕[まくら]', // ➀ pillow
'mama'=>'*まま', // ➀ 儘 as is, still in the current state
'mamoru'=>'*守[まも]る', // ➁ protect, observe
'man'=>'*万[まん]', // ➀ ten thousand
'manichi'=>'*万[まん]一[いち]', // ➀ 
'mannaka'=>'*真[ま]ん中[なか]', // ⓪ center, middle casual
'manshon'=>'*マンション', // ➀ apartment, residential building
'marumaru'=>'*◯◯[まるまる]', // ⓪

'masen'=>'*ません', // 
'masendeshita'=>'*ませんでした', // 
'mashita'=>'*ました', // 
'masu'=>'*ます', // 
'mata'=>'*また', // again, also, or
'matomeru'=>'*まとめる', // ⓪ gather together, put in order
'matsu'=>'*待[ま]つ', // ➀ wait, wait for
'mattaku'=>'*全[まった]く', // ⓪ entirely, truly
'mawaru'=>'*回[まわ]る', // ⓪ turn round, go around
'mayu'=>'*眉[まゆ]', // ➀ eyebrow
'mazu'=>'*まず', // ➀ first of all, to begin with
'mazui'=>'*まずい', // ➁ bad taste, distasteful
'me'=>'*目[め]', // eye
'medatsu'=>'*目[め]立[だ]つ', // ➁ stand out, be conspicuous
'megane'=>'*メガネ', // ➀ 眼鏡 glasses
'mei'=>'*名[めい]', // ➀
'meibo'=>'*名[めい]簿[ぼ]', // ⓪
'meibutsu'=>'*名[めい]物[ぶつ]', // ➀ famous product; special product; speciality; specialty
'meijin'=>'*名[めい]人[じん]', // ➁いじ➁
'meisaku'=>'*名[めい]作[さく]', // ⓪
'meisakusen'=>'*名[めい]作[さく]選[せん]', // 
'meisei'=>'*名[めい]声[せい]', // ⓪
'meishi'=>'*名[めい]詞[し]:名[めい]刺[し]', // ⓪:⓪ business card
'meisho'=>'*名[めい]所[しょ]', // ⓪ famous place; noted place; place of (scenic or historical) interest; sights (to see)
'meishou'=>'*名[めい]称[しょう]', // ⓪
'meiyo'=>'*名[めい]誉[よ]', // ➀



'menyuu'=>'*メニュー', // menu
'mezamashitokei'=>'*目覚まし時計[めざましとけい]', // alarm clock
'mezurashii'=>'*珍しい[めずらしい]', // rare, scarce
'michi'=>'*道[みち]', // street, way
'midori'=>'*緑[みどり]', // green
'mieru'=>'*見える[みえる]', // be visible, can see
'migakimasu'=>'*磨[みが]きます', // ⓪ polish, brush
'migaku'=>'*磨[みが]く', // ⓪ polish, brush
'migi'=>'*右[みぎ]', // right
'migigawa'=>'*右側[みぎがわ]', // right side
'miitingu'=>'*ミーティング', // meeting
'mijikai'=>'*短い[みじかい]', // short, brief
'mikan'=>'*みかん', // tangerine
'mikata'=>'*見方[みかた]', // view, perspective
'mikka'=>'*三日[みっか]', // three days, third of the month
'mimi'=>'*耳[みみ]', // ear
'minami'=>'*南[みなみ]', // south
'minna'=>'*みんな', // everybody
'miru'=>'*見る[みる]', // see, look at
'mise'=>'*店[みせ]', // shop, store
'miseru'=>'*見[み]せる', // show
'miitingu'=>'*ミ─ティング', // meeting
'mitsu'=>'*三つ[みつ]', // three things
'mitsukaru'=>'*見つかる[みつかる]', // be found, be caught
'mitsukeru'=>'*見つける[みつける]', // find
'mizu'=>'*水[みず]', // water
'mochiron'=>'*もちろん', // of course
'modoru'=>'*戻る[もどる]', // return to a point of departure
'mokuyoubi'=>'*木[もく]曜[よう]日[び]', // Thursday
'mondai'=>'*問題[もんだい]', // ⓪ problem, question
'mondainai'=>'*問題[もんだい]ない', // no problem

'monosabishii'=>'*物[もの]寂[さび]しい', // ➁のさびし➁ lonely

'morau'=>'*もらう', // receive
'mori'=>'*森[もり]', // forest
'moshi'=>'*もし', // ➀ 若し if, in case of
'moshimoshi'=>'もしもし',
'motsu'=>'*もつ', // last long, be durable
'motsu'=>'*持つ[もつ]', // have, possess
'motteiku'=>'*持って行く[もっていく]', // take, bring
'motto'=>'*もっと', // more
'mou'=>'*もう', // already, yet
'mou'=>'*もう', // another, again
'muika'=>'*六日[むいか]', // six days, sixth of the month
'mukaeru'=>'*迎える[むかえる]', // welcome, receive a visitor
'mukau'=>'*向かう[むかう]', // face, head toward
'mukou'=>'*向こう[むこう]', // over there, on the other side
'mune'=>'*胸[むね]', // chest, breast
'muri'=>'*無理[むり]', // unreasonable, impossible
'mushi'=>'*虫[むし]', // ⓪
'musuko'=>'*息子[むすこ]', // ⓪ speaker's son
'musukosan'=>'*（お）息子[むすこ]さん', // ⓪ someone else's son
'musume'=>'*娘[むすめ]', // ➂ speaker's daughter, girl
'musumesan'=>'*（お）娘[むすめ]さん', // ➂ someone else's daughter, girl
'muttsu'=>'*六つ[むっつ]', // six things
'muzukashii'=>'*難[むずか]しい', // ➁ difficult
'myougonichi/asatte'=>'*明後日[みょうごにち]/あさっ て', // day after tomorrow
'myouji'=>'*名字[みょうじ]', // surname, family name
'na'=>'*名[な]', // ⓪

'nadagai'=>'*名[な]高[だか]い', // ➁だか➁ famous, renowned
'nagareru'=>'*流[なが]れる', // flow, run
'naga'=>'*長[なが]', // long
'nagai'=>'*長[なが]い', // ➁ long
'nagasa'=>'*長[なが]さ', // ➀ length
'nagori'=>'*名[な]残[ごり]', // ➂ remains, traces, vestiges, relics, 離愁
'nahuda'=>'*名[な]札[ふだ]', // ⓪ name plate, name tag
'nai'=>'*無い[ない]', // to not be
'naka'=>'*中[なか]', // inside, middle
'nakanaka'=>'*なかなか', // rather, pretty
'nakunaru'=>'*亡くなる[なくんある]', // die, pass away
'nakusu'=>'*無くす[なくす]', // lose, get rid of
'namae'=>'*名[な]前[まえ]', // ⓪ name
'namida'=>'*涙[なみだ]', // tear
'nan'=>'*何[なん]',
'nana'=>'*七[なな]', // ➀ seven Chinese origin
'nanahyaku'=>'*七[なな]百[ひゃく]',
'rokuman'=>'*七[なな]万[まん]',
'nanasen'=>'*七[なな]千[せん]',
'nanatsu'=>'*七つ[なんあつ]', // seven things
'nanban'=>'*何[なん]番[ばん]',
'nande'=>'*何[なん]で', // ➀ why
'nangai'=>'*何[なん]階[がい]', // ⓪
'nani'=>'*何[なに]', // what
'nanika'=>'*何か[なにか]', // something, some
'nanji'=>'*何[なん]時[じ]', // ➀
'nanoka'=>'*七日[なのか]', // seven days, seventh of the month
'nanpun'=>'*何[なん]分[ぷん]',
'nansai'=>'*何[なん]歳[さい]',
'nanyoubi'=>'*何[なん]曜[よう]日[び]',
'naoru'=>'*治[なお]る', // be cured, get well
'naoru'=>'*直[なお]る', // be repaired, get fixed
'naosu'=>'*直[なお]す', // repair, fix
'nara'=>'*なら', // ➀ if, in case; as for; if possible
'naraberu'=>'*並[なら]べる', // line up, arrange
'narabu'=>'*並[なら]ぶ', // line up, be parallel
'narau'=>'*習[なら]う', // な➁ら➁う to take lessons in, to study
'nareru'=>'*慣[な]れる', // grow accustomed to, get used to
'narimasu'=>'*成[な]ります', // become
'naru'=>'*成[な]る', // become
'naruhodo'=>'*なるほど', // I see, really
'nasu'=>'*ナス', // eggplant
'natsu'=>'*夏[なつ]', // summer
'naze'=>'*なぜ', // why
'nazukeru'=>'*名[な]付[づ]ける', // ➂ name, call, christen, term
'nedan'=>'*値[ね]段[だん]', // price
'neesan'=>'*姉[ねえ]さん', // one’s own older sister
'nemui'=>'*眠[ねむ]い', // sleepy
'nekutai'=>'*ネクタイ', // ➀
'nema'=>'*寝[ね]間[ま]', // ➂
'nemuru'=>'*眠[ねむ]る', // sleep, lie idle
'nemasu'=>'*寝[ね]ます',
'nen'=>'*年[ねん]',
'nendo'=>'*年[ねん]度[ど]', // year, school year
'nenkan'=>'*年[ねん]', // ➀
'nenkan'=>'*年[ねん]間[かん]', // period of one year
'neru'=>'*寝[ね]る', // ⓪ lie down and sleep, go to sleep
'netsu'=>'*熱[ねつ]', // heat, fever
'ni'=>'*に:二[に]',
'nichi'=>'*二[にち]', // two
'nichi'=>'*日[にち]', // counter for days
'nichiji'=>'*日[にち]時[じ]', // date and time
'nichiyoubi'=>'*日[にち]曜[よう]日[び]', // Sunday
'nigeru'=>'*逃げる[にげる]', // escape, run away
'nigiyaka'=>'*賑[にぎ]やか', // ➁ぎ➁ lively, exciting
'nihiki'=>'*二匹[にひき]',
'nihon'=>'*日[に]本[ほん]',
'nihongo'=>'*日[に]本[ほん]語[ご]',
'nihonjin'=>'*日[に]本[ほん]人[じん]',
'nihyaku'=>'*二[に]百[ひゃく]',
'niisan'=>'*兄[にい]さん', // one’s own older brother
'nijuu'=>'*二[に]十[じゅう]', // 
'nikai'=>'*二階[にかい]', // second floor, upstairs
'nikki'=>'*日記[にっき]', // diary
'niku'=>'*肉[にく]', // flesh, meat
'niman'=>'*二[に]万[まん]',
'nin'=>'*人[にん]', // in 三人，etc

'ninjin'=>'*にんじん', // carrot
'ninki'=>'*人気[にんき]', // popularity
'nisen'=>'*二[に]千[せん]',
'nishi'=>'*西[にし]', // west, western
'niteiru'=>'*似ている[にている]', // look like, resemble
'niwa'=>'*庭[にわ]', // garden, yard
'nobiru'=>'*伸びる[のびる]', // stretch, grow
'noboru'=>'*上る[のぼる]', // go up, climb
'nokoru'=>'*残る[のこる]', // remain, be left over
'nokosu'=>'*残す[のこす]', // leave, leave undone
'nomimono'=>'*飲み物[のみもんお]', // beverage, drink
'nomu'=>'*飲む[のむ]', // drink
'nooto'=>'*ノート',
'norikaeru'=>'*乗り換える[のりかえる]', // change, transfer
'noru'=>'*乗る[のる]', // ride, take
'noseru'=>'*載せる[のせる]', // place, put on
'nurui'=>'*ぬるい', // tepid, lukewarm
'nyuugaku'=>'*入学[にゅうがく]', // enter a school, matriculate
'nyuuin'=>'*入院[にゅういん]', // be hospitalized
'nyuusu'=>'*ニュース', // news
'obaasan'=>'*お祖母[ばあ]さん', // grandmother
'oba'=>'*伯母[おば]/叔母[おば]', // aunt
'obasan'=>'*伯母[おば]/叔母[おば]さん', // aunt
'obake'=>'*お化[ば]け', // ghost
'obasan'=>'*おばさん', // aunt
'oboeru'=>'*覚[おぼ]える', // memorize, learn
'oubo'=>'*応[おう]募[ぼ]', // ➀ application
'oubosuru'=>'*応[おう]募[ぼ]する', // ⓪ to apply for sth
'oubosha'=>'*応[おう]募[ぼ]者[しゃ]', // ➁ applicant
'ocha'=>'*お茶[おちゃ]', // tea
'ochiru'=>'*落ちる[おちる]', // fall, come down
'odoroku'=>'*驚く[おどろく]', // be surprised, be startled
'odoru'=>'*踊る[おどる]', // dance
'ofisu'=>'*オフィス',
'ofukuro'=>'*おふくろ', // ⓪ speaker's mother
'ohayougozaimasu'=>'*おはようございます',
'oishasan'=>'*お医者さん[おいしゃさん]', // doctor
'oishi'=>'*おいしい', // ⓪ 美味しい tasty
'oiwai'=>'*お祝[いわ]い', // celebrate
'oji'=>'*おじ', // one’s own uncle
'oji'=>'*おじ', // one’s own uncle
'ojiisan'=>'*お祖父[じい]さん', // grandfather
'ojisan'=>'*伯父[おじ]/叔父[おじ]さん', // uncle, man
'okaasan'=>'*お母[かあ]さん', // mother
'okashi'=>'*お菓[か]子[し]', // sweets, snacks
'okeru'=>'*於[お]ける', // ➁ on, at, in, for
'oki'=>'*大[お]きい', // big
'okimasu'=>'*起[お]きます', // ➁ get up, get out of bed; occur, happen
'okonau'=>'*行[おこな]う', // ⓪
'okiru'=>'*起[お]きる', // ➁ get up, get out of bed; occur, happen
'okoru'=>'*起[お]こる', // happen
'okosu'=>'*起[お]こす', // wake someone up
'oku'=>'*置く[おく]:億[おく]', // put, place; ➀
'okuni'=>'*お国[くに]', // ⓪ your/my native country

'okureru'=>'*遅れる[おくれる]', // be late
'okuru'=>'*贈る[おくる]', // offer, give
'okuru'=>'*送る[おくる]', // send
'okusan'=>'*奥[おく]さん', // ➀ someone else's wife
'omawarisan'=>'*お巡りさん[おまわりさん]', // police officer
'omiyage'=>'*お土産[みやげ]', // ⓪ souvenir, gift
'omoi'=>'*重[おも]い:思[おも]い', // ⓪ heavy; ➁ thought, affection, love, feelings
'omoidasu'=>'*思[おも]い出[だ]す', // recollect, recall
'omoshiroi'=>'*面[おも]白[しろ]い', // interesting, amusing
'omou'=>'*思[おも]う', // think
'onaji'=>'*同じ[おなじ]', // same, identical
'onaka'=>'*お腹[おなか]', // stomach, belly
'ondo'=>'*温度[おんど]', // temperature
'onegai'=>'*お願い[おねがい]', // favor
'onegaishimasu'=>'*お願[ねが]いします', // please
'oneesan'=>'*お姉[ねえ]さん', // ➁ね➁ older sister, woman
'ongaku'=>'*音楽[おんがく]', // music
'oniisan'=>'*お兄[にい]さん', // ➁ older brother
'onna'=>'*女[おんな]', // woman
'onna'=>'*女の子[おんな][の][こ]', // little girl
'ooi'=>'*多い[おおい]', // a lot of, many
'ookii'=>'*大[おお]きい', // ➁おき➁ big, large
'ookina'=>'*大[おお]きな', // big; large; great
'ookisa'=>'*大[おお]きさ', // size, dimension
'ooku'=>'*多[おお]く', // much, largely
'oosaka'=>'*大[おお]阪[さか]',
'oriru'=>'*下りる[おりる]', // go down, come down
'oriru'=>'*降りる[おりる]', // get off, land
'osenwaninarimasu'=>'*お世話[せわ]になります', // Vielen Dank für Ihre Unterstützung.
'oshieru'=>'*教える[おしえる]', // teach, tell
'osoi'=>'*遅い[おそい]', // slow, late
'osu'=>'*押す[おす]', // push, press down
'otearai'=>'*お手[て]洗[あ]い', // toilet, bathroom
'oto'=>'*音[おと]', // sound, noise
'otoko'=>'*男[おとこ]', // man, male
'otoko'=>'*男の子[おとこ][の][こ]', // boy
'otona'=>'*大人[おとな]', // adult
'otonashii'=>'*大人しい[おとなしい]', // gentle, quiet
'otosu'=>'*落とす[おとす]', // drop
'ototoi'=>'*一昨日[おととい]', // the day before yesterday
'otousan'=>'*お父[とう]さん', // father, dad
'otouto'=>'*弟[おとうと]', // ➂ younger brother
'otoutosan'=>'*弟[おとうと]さん', //  younger brother
'otsuri'=>'*お釣[つ]り', // change of money
'otto'=>'*夫[おっと]', // ➀ speaker's husband
'ouji'=>'*往[おう]時[じ]',
'owari'=>'*終[お]わり', // end, conclusion
'owarimasu'=>'*終[お]わります', // finish, end
'owaru'=>'*終[お]わる', // finish, end
'oya'=>'*親[おや]', // parent
'oyaji'=>'*親[おや]父[じ]', // speaker's dad
'paatii'=>'*パーティー', // party
'paato'=>'*パート', // part-time
'pasokon'=>'*パソコン', // ⓪ personal computer
'pasupooto'=>'*パスポート', // passport
'peeji'=>'*ページ', // page
'posuto'=>'*ポスト', // postbox, mailbox
'puroguramu'=>'*プログラム', // program booklet
'raigetsu'=>'*来[らい]月[げつ]', // next month
'rainen'=>'*来[らい]年[ねん]', // next year
'raishuu'=>'*来[らい]週[しゅう]', // next week
'rajio'=>'*ラジオ', // radio
'ranchi'=>'*ランチ', // lunch loan word
'rei'=>'*零[れい]:例[れい]:令[れい]', // ➀ zero
'reibun'=>'*例[れい]文[ぶん]',
'rekoodo'=>'*レコード', // record
'renshuu'=>'*練[れん]習[しゅう]',
'rentaishi'=>'*連[れん]体[たい]詞[し]', // ➁んた➁
'reshiito'=>'*レシート', // receipt loan word
'ringo'=>'*りんご', // apple
'riyou'=>'*利[り]用[よう]', // ⓪

'riyuu'=>'*理[り]由[ゆう]', // reason, excuse
'robii'=>'*ロビ─', // ➀
'rokko'=>'*六[ろっ]個[こ]', // ➂ six
'roku'=>'*六[ろく]', // ➂ six
'rokuman'=>'*六[ろく]万[まん]',
'rokunin'=>'*六[ろく]人[にん]',
'rokusen'=>'*六[ろく]千[せん]',
'roppyaku'=>'*六[ろっ]百[ぴゃく]',

'ryokou'=>'*旅[りょ]行[こう]', // travel, trip
'ryouhou'=>'*両[りょう]方[ほう]', // both

'ryoukin'=>'*料[りょう]金[きん]', // ➀ fee; charge; fare
'ryoukinbako'=>'*料[りょう]金[きん]箱[ばこ]', // ➀ fare box (in a bus, etc.)
'ryoukinhyou'=>'*料[りょう]金[きん]表[ひょう]', // ➀ table of charges; tariff; price list
'ryoukinjo'=>'*料[りょう]金[きん]所[じょ]', // ➀ tollgate; toll booth

'ryouri'=>'*料[りょう]理[り]', // cooking

'ryoushin'=>'*両[りょう]親[しん]', // ➀ parents
'ryuugaku'=>'*留学[りゅうがく]', // study abroad
'saabisu'=>'*サービス', // service, on the house
'sagasu'=>'*探す[さがす]', // search for, look for
'sageru'=>'*下げる[さげる]', // lower, turn down
'sai'=>'*歳[さい]:妻[さい]:際[さい]:再[さい]:最[さい]:賽[さい]:才[さい]:債[さい]:犀[さい]:菜[さい]:差[さ]異[い]', // ➀ 賽:dice, die 菜:side dish
'saifu'=>'*財布[さいふ]', // purse, wallet
'saigo'=>'*最後[さいご]', // last
'saikin'=>'*最近[さいきん]', // recent, latest
'saisho'=>'*最初[さいしょ]', // first, outset
'sakana'=>'*魚[さかな]', // ⓪ fish
'sake'=>'*酒[さけ]', // alcohol, rice wine
'saki'=>'*先[さき]', // ahead, first
'sakura'=>'*桜[さくら]',
'sakuradaigaku'=>'*桜[さくら]大[だい]学[がく]',
'sakunen'=>'*昨年[さくねん]', // last year , often used in writing
'sakuya'=>'*昨夜[さくや]', // last night, last evening
'sameru'=>'*冷める[さめる]', // cool off
'samui'=>'*寒[さむ]い', // ➁ cold temperature of the air
'san'=>'*三[さん]:さん', // three
'sanban'=>'*三[さん]番[ばん]', // ⓪ third
'sanbiki'=>'*三匹[さんびき]', // use ひき after 3
'sanbyaku'=>'*三[さん]百[びゃく]',
'sanjuu'=>'*三十[さんじゅう]', // 
'sanman'=>'*三[さん]万[まん]',
'sannin'=>'*三[さん]人[にん]',
'nisen'=>'*三[さん]千[ぜん]',
'sara'=>'*皿[さら]', // plate, counter for plates or helpings
'saraishuu'=>'*再来週[さらいしゅう]', // the week after next
'sarariiman'=>'*サラリーマン', // office worker, company employee
'satou'=>'*砂糖[さとう]', // sugar
'satsu'=>'*冊[さつ]',
'sawaru'=>'*触る[さわる]', // touch, feel
'se'=>'*せ:背[せ]', // height, stature
'seetaa'=>'*セーター', // sweater
'seikatsu'=>'*生[せい]活[かつ]', // life, living
'seikou'=>'*成[せい]功[こう]', // success
'seiseki'=>'*成[せい]績[せき]', // results, grade
'seito'=>'*生[せい]徒[と]', // pupil, student
'sekai'=>'*世[せ]界[かい]', // world
'seiki'=>'*世[せい]紀[き]:席[せき]', // century, seat, one’s place
'sekken'=>'*石[せっ]鹸[けん]', // soap
'semai'=>'*狭[せま]い', // narrow, small
'sen'=>'*千[せん]:線[せん]:選[せん]', // ⓪ thousand,line
'sensei'=>'*先[せん]生[せい]', // teacher
'senshu'=>'*選[せん]手[しゅ]', // athlete, sports player
'senshuu'=>'*先[せん]週[しゅう]', // ⓪ last week
'sentaku'=>'*洗[せん]濯[たく]', // laundry, washing
'setsu'=>'*説[せつ]', // ➀ theory, opinion, rumour
'setsumei'=>'*説[せつ]明[めい]', // ⓪ explanation, description
'setsuzokushi'=>'*接[せつ]続[ぞく]詞[し]', // ➁つぞく➁
'sha'=>'*しゃ:車[しゃ]', // 
'shako'=>'*車[しゃ]庫[こ]', // ➀
'shaberu'=>'*しゃべる', // chat, talk
'shain'=>'*社[しゃ]員[いん]',
'shakai'=>'*社[しゃ]会[かい]', // ➀ society
'shasetsu'=>'*社[しゃ]説[せつ]', // ⓪
'shashin'=>'*写[しゃ]真[しん]', // photograph
'shatsu'=>'*シャツ', // ➀ shirt
'shi'=>'*し:四[し]', // and; besides; moreover; what's more; not only ... but also; because; since
'shibaraku'=>'*しばらく', // a little while, a while
'shichi'=>'*七[しち]', // ➂
'shichihyaku'=>'*七[しち]百[ひゃく]',
'shichinin'=>'*七[しち]人[にん]',
'shigoto'=>'*仕[し]事[ごと]', // ⓪ work, job
'shigotosagashi'=>'*仕[し]事[ごと]探[さが]し', // job hunting
'shigotonomushi'=>'*仕[し]事[ごと]の虫[むし]', // workaholic
'shigotooyameru'=>'*仕[し]事[ごと]を辞[や]める', // to quit one's job; to resign
'shigotonioubosuru'=>'*仕[し]事[ごと]に応[おう]募[ぼ]する', // to apply for a job
'shihyaku'=>'*四[し]百[ひゃく]',
'shiken'=>'*試[し]験[けん]', // ➁ exam
'shima'=>'*島[しま]', // island Japanese origin
'shimaru'=>'*閉[し]まる', // be shut, be closed
'shimasu'=>'*します',
'shimau'=>'*仕[し]舞[ま]う', // put away, put in
'shimei'=>'*氏[し]名[めい]', // full name
'shimeru'=>'*締[し]める:閉[し]める', // tighten, fasten; shut, close doors, windows, etc.
'shinbun'=>'*新[しん]聞[ぶん]', // newspaper
'shingou'=>'*信[しん]号[ごう]', // signal, traffic light
'shinjiru'=>'*信[しん]じる', // believe, trust
'shinkansen'=>'*新[しん]幹[かん]線[せん]', // ➁んか➁
'mashime'=>'*真[ま]面[じ]目[め]', // ⓪ serious, earnest, sober, grave; honest, sincere
'shinoosaka'=>'*新[しん]大[おお]阪[さか]', // ➁んお➁
'shinpai'=>'*心[しん]配[ぱい]', // anxiety, worry
'shinsetsu'=>'*親[しん]切[せつ]', // ➀ kind; gentle; considerate; generous; friendly; nice
'shinu'=>'*死[し]ぬ', // die
'shio'=>'*塩[しお]', // salt
'shiraberu'=>'*調[しら]べる', // investigate, check
'shiro'=>'*白[しろ]', // white
'shiroi'=>'*白[しろ]い', // white, blank
'shiru'=>'*知[し]る', // know
'shisen'=>'*四[し]千[せん]',

'shita'=>'*下[した]', // under, below
'shitsumon'=>'*質[しつ]問[もん]', // question
'shitsurei'=>'*失[しつ]礼[れい]',
'shizen'=>'*自[し]然[ぜん]', // natural， nature
'shizuka'=>'*静[しず]か', // ➀ quiet, tranquil
'shokuba'=>'*職[しょく]場[ば]', // ⓪ place of work, office
'shokuji'=>'*食[しょく]事[じ]', // ⓪ meal
'shokudou'=>'*食[しょく]堂[どう]', // ⓪ dining room, restaurant, canteen
'shougakkou'=>'*小[しょう]学[がっ]校[こう]', // elementary school
'shoukai'=>'*紹[しょう]介[かい]', // ⓪ introduction
'shokyuu'=>'*初[しょ]級[きゅう]', // ⓪
'shokyuusha'=>'*初[しょ]級[きゅう]者[しゃ]',
'shounen'=>'*少[しょう]年[ねん]', // ⓪ boy between and years old
'shousetsu'=>'*小[しょう]説[せつ]', // novel
'shouyu'=>'*醤[しょう]油[ゆ]', // ⓪ soy sauce
'shujin'=>'*主[しゅ]人[じん]', // ➀ one's husband, one's employer
'shujin'=>'*主[しゅ]人[じん]公[こう]', // ➁じ➁ 
'shujutsu'=>'*手[しゅ]術[じゅつ]', // ➀ surgical operation
'shukudai'=>'*宿[しゅく]題[だい]', // ⓪ homework
'shuppatsu'=>'*出[しゅっ]発[ぱつ]', // ⓪ departure, starting
'shurui'=>'*種[しゅ]類[るい]', // ➀ kind, type
'shusseki'=>'*出[しゅっ]席[せき]', // ⓪
'shussekisha'=>'*出[しゅっ]席[せき]者[しゃ]', // ➁
'shussekirotsu'=>'*出[しゅっ]席[せき]率[りつ]', // ➁
'shuu'=>'*週[しゅう]', // week
'shuukan'=>'*習慣[しゅうかん]', // ⓪
'shuumatsu'=>'*週[しゅう]末
[まつ]', // ⓪ weekend
'sisutemu'=>'*システム', // ➀ system 
'soba'=>'*そば', // 側;蕎麦 ➀ side, near, beside, vicinity
'sobo'=>'*祖[そ]母[ぼ]', // ➀ grandmother
'socchi'=>'*そっち', // there casual
'sochira'=>'*そちら', // there, that way
'sodateru'=>'*育[そだ]てる', // ➁だて➁ bring up, raise
'sofu'=>'*祖[そ]父[ふ]', // ➀ grandfather
'soko'=>'*そこ', // there
'sonna'=>'*そんな', // ⓪ such; that sort of; that kind of; like that
'sono'=>'*その',
'sonomama'=>'*そのまま', // as it is, just like that
'sora'=>'*空[そら]', // ➀ sky
'sore'=>'*それ', // that, that one
'soto'=>'*外[そと]', // outside, open air
'sotsugyou'=>'*卒[そつ]業[ぎょう]', // ⓪ graduation
'sou'=>'*そう', // so, that way
'soudan'=>'*相[そう]談[だん]', // ⓪ consultation, advice
'soudesu'=>'*そうです', // that's right
'soudesuka'=>'*そうですか', // ↗ Is that right? ↘ Oh, I see.
'subarashii'=>'*素[す]晴[ば]らしい', // ➁ばらし➁ excellent, wonderful
'sugu'=>'*直[す]ぐ', // ➀ at once, soon
'suiyoubi'=>'*水[すい]曜[よう]日[び]', // ➁いよ➁ Wednesday
'suki'=>'*好[す]き', // ➂ favorite, liked
'sukoshi'=>'*少[すこ]し', // ➁こ➁ a bit, a little while
'suku'=>'*空[す]く', // be ⓪ empty, become less crowded
'sukunai'=>'*少[すく]ない', // ➁ few, little
'suimasen'=>'*すいません',
'sumimasen'=>'*すみません',
'sumu'=>'*住[す]む', // ➀ live, reside
'supootsu'=>'*スポーツ', // sport
'suppai'=>'*酸[す]っぱい', // ➁っぱ➁ sour
'supuun'=>'*スプーン', // spoon
'suru'=>'*する', // ⓪ 為る します、しました do, make
'sushi'=>'*寿[す]司[し]', // ➂, ➁お寿司
'sushiya'=>'*寿[す]司[し]屋[や]', // ➁
'susumeru'=>'*進[すす]める', // ⓪ go ahead, proceed
'susumu'=>'*進[すす]む', // ⓪ advance, move forward
'suteru'=>'*捨[す]てる', // ⓪ discard, abandon
'suu'=>'*数[すう]', // ➀ number
'suugaku'=>'*数[すう]学[がく]', // ⓪ mathematics
'suuji'=>'*数[すう]字[じ]', // ⓪ numeric characters
'suushi'=>'*数[すう]詞[し]', // ⓪
'suwaru'=>'*座[すわ]る', // ⓪ sit, sit down
'suzushii'=>'*涼[すず]しい', // ➁ cool of temperature
'tabako'=>'*煙草[たばこ]', // ⓪ tobacco, cigarette
'tabemono'=>'*食[た]べ物[もの]', // ➁べも➁  food
'tabemasu'=>'*食[た]べます', // ➁ eat
'taberu'=>'*食[た]べる', // ➁ eat
'tabun'=>'*多[た]分[ぶん]', // ➀ probably, perhaps
'tabunni'=>'*多[た]分[ぶん]に', // in great amount; considerably
'tada'=>'*ただ', // 只 free of charge, common, usual
'tadashii'=>'*正[ただ]しい', // ➁ correct, righteous
'taifuu'=>'*台[たい]風[ふう]', // ➁ typhoon
'taigen'=>'*体[たい]言[げん]', // ➀ indeclinable nominal
'taihen'=>'*大[たい]変[へん]', // ⓪ awful, hard, immense, grave
'taijin'=>'*タイ人[じん]', // ➁イ➁
'taisetsu'=>'*大[たい]切[せつ]', // ⓪ important, valuable
'taishikan'=>'*大[たい]使[し]館[かん]', // ➁いし➁ embassy
'taiwan'=>'*臺[たい]灣[たい]', // ⓪
'taiyou'=>'*太陽[たいよう]', // sun
'takai'=>'*高[たか]い', // ➁ high, tall, expensive
'takasa'=>'*高さ[たかさ]', // height
'takusan'=>'*たくさん', // a lot, in large quantity
'takushii'=>'*タクシー', // taxi
'tame'=>'*ため', // sake, purpose
'tanjoubi'=>'*誕[たん]生[じょう]日[び]', // ➁んじょ➁

'tanomu'=>'*頼む[たのむ]', // order, ask for
'tanoshii'=>'*楽しい[たのしい]', // fun, enjoyable
'tanoshimu'=>'*楽しむ[たのしむ]', // enjoy
'taoreru'=>'*倒れる[たおれる]', // fall over
'tara'=>'*たら', // ➀ if; when; after
'tashika'=>'*確か[たしか]', // for sure, for certain
'tasukeru'=>'*助ける[たすける]', // help, save
'tatemono'=>'*建物[たてもの]', // building, structure
'tateru'=>'*建てる[たてる]', // build, erect
'tateru'=>'*立てる[たてる]', // stand, set up
'tatoeba'=>'*例えば[たとえば]', // for example
'tatsu'=>'*立つ[たつ]', // stand, rise
'tazuneru'=>'*訪ねる[たずねる]', // visit, go to see
'te'=>'*て:手[て]', // hand
'techou'=>'*手[て]帳[ちょう]',
'teeburu'=>'*テーブル', // table
'teepu'=>'*テープ',
'tegami'=>'*手[て]紙[がみ]', // letter
'teian'=>'*提[てい]案[あん]', // proposition, proposal
'tempura'=>'*天[て]ぷら', // Japanese deep-fried food
'tenin'=>'*店[てん]員[いん]', // ⓪
'tenjoubi'=>'*誕[たん]生[じょう]日[び]', // ➁
'tenki'=>'*天[てん]気[き]', // weather
'terebi'=>'*テレビ', // ➀ television
'tesuto'=>'*テスト', // ➀ test
'tetsudau'=>'*手伝う[てつだう]', // help, assist
'tisshu'=>'*ティッシュ', // tissue
'to'=>'*と:戸[と]', // door, sliding door
'tobu'=>'*飛ぶ[とぶ]', // fly
'todoku'=>'*届く[とどく]', // reach, be received
'toire'=>'*トイレ', // ➀
'tojiru'=>'*閉じる[とじる]', // shut, close books, eyes, etc.
'tokei'=>'*時計[とけい]', // ⓪ 土圭 clock, watch
'toki'=>'*時[とき]', // time, moment
'tokiori'=>'*時[とき]折[おり]', // ⓪ sometimes; at intervals; occasionally; on occasion; from time to time

'tokidoki'=>'*時[とき]々[とき]', // sometimes
'tokitoshite'=>'*時[とき]として',// ➁き➁ in some cases; sometimes; on occasions

'tokkyuu'=>'*特[とっ]急[きゅう]', // limited express

'tokoro'=>'*所[ところ]', // place
'tokubetsu'=>'*特[とく]別[べつ]', // ⓪ special

'tokuni'=>'*特[とく]に', // specially, particularly
'tomaru'=>'*止[と]まる', // come to a stop, cease
'tomaru'=>'*泊[と]まる', // stay overnight
'tomeru'=>'*止[と]める', // stop a car…. 止める yameru give up
'tomodachi'=>'*友[とも]達[だち]', // ⓪ friend, companion
'tomonau'=>'*伴[ともな]う', // ➁
'tonari'=>'*隣[となり]', // ⓪ next to, next door
'tooi'=>'*遠[とお]い', // far, distant
'tooka'=>'*十日[とおか]', // ⓪ ten days, tenth of the month
'tooku'=>'*遠[とお]く', // ⓪ far away, at a distance
'toori'=>'*通[とお]り', // ⓪ street, road
'tooru'=>'*通[とお]る', // ➀ pass, go through
'torakku'=>'*トラック', // ➁ truck
'tori'=>'*鳥[とり]', // bird, poultry
'toru'=>'*取[と]る:撮[と]る', // ➀:➀ take; take a photograph, film
'toshi'=>'*年[とし]', // ➂ year, age
'toshiue'=>'*年[とし]上[うえ]', // ⓪ older, senior
'toshiueno'=>'*年[とし]上[うえ]の', // ⓪ old
'toshiuenohito'=>'*年[とし]上[うえ]の人[ひと]', // 
'toshokan'=>'*図[と]書[しょ]館[かん]', // ➁しょ➁ library
'totemo'=>'*とても', // very
'tottori'=>'*鳥取[とっとり]', // ⓪
'tou'=>'*頭[とう]', // ➀ cattle, horses; head
'toukyou'=>'*東京[とうきょう]',
'tsuchi'=>'*土[つち]', // ➂
'tsugi'=>'*次[つぎ]', // next
'tsuitachi'=>'*一[つい]日[たち]:一[いっ]日[ぴ]', // ➂:➀ first of the month
'tsukau'=>'*使[つか]う', // ⓪ to use, to make use

'tsukare'=>'*疲[つか]れ', // ➂ tiredness
'tsukareru'=>'*疲[つか]れる', // ➁ to get tired
'tsukau'=>'*使[つか]う', // ⓪ use, make use of
'tsukeru'=>'*つける', // switch on, turn on
'tsuki'=>'*月[つき]', // moon
'tsuku'=>'*つく', // be on, be switched on
'tsuku'=>'*着く[つく]', // arrive at, reach
'tsukue'=>'*机[つくえ]', // desk
'tsukuru'=>'*作[つく]る', // make, create
'tsuma'=>'*妻[つま]', // ➀ woman, speaker's wife
'tsumaranai'=>'*つまらない', // boring, dull
'tsumari'=>'*つまり', // in short, that is to say
'tsumetai'=>'*冷たい[つめたい]', // cold to touch
'tsumori'=>'*つもり', // intention, purpose
'tsureteiku'=>'*連れていく[つれていく]', // take along, bring along a person
'tsuretekuru'=>'*連れて来る[つれてくる]', // bring a person
'tsutaeru'=>'*伝える[つたえる]', // convey, transmit
'tsutomeru'=>'*勤める[つとめる]', // serve, hold a job

'tsuu'=>'*通[つう]', // ➀ authority, expert; letters, notes; understanding
'tsuukin'=>'*通[つう]勤[きん]客[きゃく]', // ➁うき➁
'tsuukinsha'=>'*通[つう]勤[きん]者[しゃ]', // ⓪
'tsuuka'=>'*通[つう]貨[か]', // ➀
'tsuukashuushuku'=>'*通[つう]貨[か]収[しゅう]縮[しゅく]', // ➀
'tsuugaku'=>'*通[つう]学[がく]', // ⓪
'tsuuro'=>'*通[つう]路[ろ]', // ➀

'tsuuyaku'=>'*通[つう]訳[やく]', // ➀
''=>'*', // ⓪➀➁➂


'tsuyoi'=>'*強い[つよい]', // strong
'tsuzukeru'=>'*続ける[つずける]', // continue, keep up
'tsuzuku'=>'*続く[つずく]', // continue, follow
'uchi'=>'*家[うち]', // ⓪
'ude'=>'*腕[うで]', // arm
'udedokei'=>'*腕[うで]時計[どけい]', // ➁でど➁ wristwatch
'ue'=>'*上[うえ]', // up, above
'ugokasu'=>'*動かす[うごかす]', // move something
'ugoku'=>'*動く[うごく]', // move
'uketoru'=>'*受け取る[うけとる]', // receive, get
'uketsuke'=>'*受[うけ]付[つけ]', // ⓪ reception (desk), information desk
'uma'=>'*馬[うま]', // horse
'umai'=>'*うまい', // ➁ good at, sweet, delicious
'umareru'=>'*生まれる[うまれる]', // be born, come into existence
'umi'=>'*海[うみ]', // sea, ocean
'un'=>'*うん', // casual yes
'uun'=>'*ううん', // casual no
'undou'=>'*運動[うんどう]', // movement, exercise
'unten'=>'*運転[うんてん]', // drive
'ura'=>'*裏[うら]', // the back, the reverse side
'ureru'=>'*売れる[うれる]', // sell, be in demand
'ureshii'=>'*嬉しい[うれしい]', // happy, glad
'uriba'=>'*売[う]り場[ば]', // ⓪ selling area, counter

'urikire'=>'*売り切れ[うりきれ]', // sell out
'uru'=>'*売る[うる]:得[う]る', // sell; be able to; get, obtain
'eru'=>'*', // ➀ obtain, gain; understand,

'urusai'=>'*うるさい', // noisy, annoying
'ushiro'=>'*後ろ[うしろ]', // back, behind
'usui'=>'*薄い[うすい]', // thin, weak
'uta'=>'*歌[うた]', // song
'utau'=>'*歌う[うたう]', // sing
'utsu'=>'*打つ[うつ]', // hit, strike
'utsukushii'=>'*美しい[うつくしい]', // beautiful
'utsusu'=>'*移す[うつす]', // move, transfer
'waga'=>'*我[わ]が', // ➀ my; our; one's own
'wain'=>'*ワイン', // ➀
'wakai'=>'*若い[わかい]', // young
'wakamono'=>'*若者[わかもの]', // young person, youth
'wakareru'=>'*分かれる[わかれる]', // be divided, split off
'wakaru'=>'*分かる[わかる]', // understand
'wakeru'=>'*分ける[わける]', // divide, share
'wakiagaru'=>'*湧[わ]き上[あ]がる', // ➁きあが➁ arise, get excited, boil up

'warau'=>'*笑う[わらう]', // laugh, smile
'warui'=>'*悪い[わるい]', // bad
'wasureru'=>'*忘れる[わすれる]', // forget, leave behind
'watashi'=>'*私[わたし]', // I
'watashitachi'=>'*私たち[わたしたち]', // we
'watasu'=>'*渡す[わたす]', // hand over, give
'weetaa'=>'*ウェーター', // waiter
'weetoresu'=>'*ウェートレス', // waitress
'yahari'=>'*やはり', // as expected
'yakan'=>'*やかん:夜[や]間[かん]', // ⓪ 薬缶 薬罐 kettle, bald head; ➀
'yakedo'=>'*火傷[やけど]', // ⓪ burn
'yakusoku'=>'*約[やく]束[そく]', // ⓪ promise, vow
'yakyuu'=>'*野[や]球[きゅう]', // baseball
'yama'=>'*山[やま]', // mountain
'yamai'=>'*病[やまい]', // ➀
'yamu'=>'*止む[やむ]', // stop, cease
'yaru'=>'*やる', // do, give
'yaru'=>'*やる', // give to an inferior
'yasai'=>'*野[や]菜[さい]', // vegetable
'yasashi'=>'*易[やさ]しい', // easy, simple
'yasashii'=>'*優[やさ]しい', // gentle, kind
'yasui'=>'*安[やす]い', // ➁ cheap, inexpensive
'yasumi'=>'*休[やす]み', // ➂ holiday, break
'yasumimasu'=>'*休[やす]みます', // take a rest, take a break
'yasumu'=>'*休[やす]む', // take a rest, take a break
'yatto'=>'*やっと', // at last, finally
'yattsu'=>'*八[やっ]つ', // eight things
'yobu'=>'*呼[よ]ぶ', // call, name
'yohin'=>'*用[よう]品[ひん]', // ⓪
'yoi'=>'*良[よ]い', // good /written form
'yokka'=>'*四[よっ]日[か]', // four days, fourth of the month
'yoko'=>'*横[よこ]', // side, width across
'yoku'=>'*よく', // often, well
'yomu'=>'*読[よ]む', // read
'yon'=>'*四[よん]', // four Japanese origin
'yonaka'=>'*夜[よ]中[なか]', // ⓪ midnight
'yonhyaku'=>'*四[よん]百[ひゃく]',
'yonin'=>'*四人[よにん]', // not よん
'sanman'=>'*四[よん]万[まん]',
'yonsen'=>'*四[よん]千[せん]',
'yorokobu'=>'*喜[よろこ]ぶ', // be happy, be delighted
'yoroshiku'=>'*よろしく', // one’s regards
'yoru'=>'*夜[よる]', // ➀ night from sunset to sunrise
'yotei'=>'*予[よ]定[てい]', // ⓪ schedule, plan
'yotsu'=>'*四つ[よつ]', // four things
'yotsukado'=>'*四[よ]つ角[かど]', // intersection
'you'=>'*用[よう]', // things to do
'youbi'=>'*曜[よう]日[び]', // day of the week
'yougen'=>'*用[よう]言[げん]', // ➀ inflectable word
'youi'=>'*用[よう]意[い]', // preparation
'youka'=>'*八日[ようか]', // eight days, eighth of the month
'youkoso'=>'*ようこそ', // ➀ welcome greeting
'yowai'=>'*弱[よわ]い', // weak
'yu'=>'*湯[ゆ]', // hot water
'yubi'=>'*指[ゆび]', // finger, toe
'yuki'=>'*雪[ゆき]', // ➂ snow, snowfall
'yukkuri'=>'*ゆっくり', // slowly
'yume'=>'*夢[ゆめ]', // ➂ dream
'yurui'=>'*緩[ゆる]い', // slack, loose
'yuu'=>'*夕[ゆう]', // ⓪ evening ➀ name
'yuugure'=>'*夕[ゆう]暮[ぐ]れ', // ⓪ evening, dusk
'yurusu'=>'*許[ゆる]す', // permit, forgive
'yuubinkyoku'=>'*郵[ゆう]便[びん]局[きょく]', // post office
'yuugata'=>'*夕[ゆう]方[がた]', // ⓪ early evening, at dusk
'yuubin'=>'*郵[ゆう]便[びん]', // ⓪
'yuubinuke'=>'*郵[ゆう]便[びん]受[う]（け）', // ➁ mailbox
'yuubinbako'=>'*郵[ゆう]便[びん]箱[ばこ]', // ➁ mailbox
'yuubinkyoku'=>'*郵[ゆう]便[びん]局[きょく]', // ➁うび➁
'yuuki'=>'*勇[ゆう]気[き]', // ➀
'yuumei'=>'*有[ゆう]名[めい]', // ⓪ famous
'yuushoku'=>'*夕[ゆう]食[しょく]', // ⓪ supper, dinner
'zannen'=>'*残[ざん]念[ねん]', // regretful, disappointing
'zasshi'=>'*雑[ざっ]誌[し]', // magazine, journal
'zen'=>'*前[ぜん]', // ➀ former, last, pre-

'zenbu'=>'*全[ぜん]部[ぶ]', // all, whole
'zero'=>'*ゼロ', // ➀
'zettaini'=>'*絶[ぜっ]対[たい]に', // absolutely, definitely
'zutto'=>'*ずっと', // all the time, all through
''=>'*[]',
''=>'*[]',
''=>'*[]',
);
?>