<?php
/*
key => : separated values
*/
$romaji_kanji = array(
'abiru'=>'*浴びる[あびる]', // take a shower
'acchi'=>'*あっち', // other side, over there casual
'achikochi'=>'*あちこち', // all over, here and there
'achira'=>'*あちら', // over there, that way
'agaru'=>'*上がる[あがる]', // go up, rise physical movement
'ageru'=>'*あげる', // give, offer
'ageru'=>'*上げる[あげる]', // raise, lift
'aisuko-hi-'=>'*アイスコーヒー', // iced coffee
'aisukuri-mu'=>'*アイスクリーム', // ice cream
'aite'=>'*相手[あいて]', // opponent, the other party
'aji'=>'*味[あじ]', // taste, flavor
'aka'=>'*赤[あか]', // red color
'akai'=>'*赤い[あかい]', // red
'akarui'=>'*明るい[あかるい]', // bright, cheerful
'akeru'=>'*開ける[あける]', // open, unlock doors, windows, etc.
'aki'=>'*秋[あき]', // autumn, fall
'amai'=>'*甘い[あまい]', // sweet
'amari'=>'*あまり', // not much
'ame'=>'*雨[あめ]', // rain
'amerika'=>'*アメリカ',
'amerikajin'=>'*アメリカ人[]',
'ana'=>'*穴[あな]', // hole
'anata'=>'*あなた', // you
'ane'=>'*姉[あね]', // one’s own older sister
'ani'=>'*兄[あに]', // one’s own older brother
'anokata'=>'あの方[かた]',
'anzen'=>'*安全[あんぜん]', // safety, security
'ao'=>'*青[あお]', // blue, green
'aoi'=>'*青い[あおい]', // blue
'apa-to'=>'*アパート', // apartment, flat
'arau'=>'*洗う[あらう]', // wash
'are'=>'*あれ', // that over there
'arimasen'=>'*ありません', // 
'aru'=>'*ある', // exist, there is
'aruku'=>'*歩く[あるく]', // walk, go on foot
'asa'=>'*朝[あさ]', // morning
'asagohan'=>'*朝ご飯[あさごはん]', // breakfast
'ashi'=>'*足[あし]', // leg, foot
'ashita'=>'*明日[あした]', // tomorrow
'asobi'=>'*遊び[あそび]', // play, amusement
'asobu'=>'*遊ぶ[あそぶ]', // play
'asoko'=>'*あそこ', // over there
'atama'=>'*頭[あたま]', // head
'atarashii'=>'*新しい[あたらしい]', // new
'atari'=>'*辺[あたり]', // vicinity
'ataru'=>'*当たる[あたる]', // go straight and hit, strike
'atatakai'=>'*暖かい[あたたかい]', // warm
'ato'=>'*あと', // after
'atsui'=>'*厚い[あつい]', // thick, bulky
'atsui'=>'*暑い[あつい]', // hot of weather
'atsui'=>'*熱い[あつい]', // hot to touch
'atsumaru'=>'*集まる[あつまる]', // gather, be collected
'atsumeru'=>'*集める[あつめる]', // collect, gather
'atsusa'=>'*厚さ[あつさ]', // thickness
'au'=>'*会う[あう]', // meet
'au'=>'*合う[あう]', // fit, match
'baai'=>'*場合[ばあい]', // situation, case
'ban'=>'*晩[ばん]', // evening, night from sunset to bedtime
'bangumi'=>'*番組[ばんぐみ]', // program
'basho'=>'*場所[ばしょ]', // place, space
'basu'=>'*バス', // bus
'basutei'=>'*バス停[ばすてい]', // bus stop
'benkyou'=>'*勉強[べんきょう]', // study
'betsu'=>'*別[べつ]', // another, different
'bi-ru'=>'*ビール', // beer
'bideo'=>'*ビデオ', // video
'bin'=>'*瓶[びん]', // bottle
'biru'=>'*ビル', // building
'boku'=>'*僕[ぼく]', // I, me usually used by young males
'boushi'=>'*帽子[ぼうし]', // hat, cap
'bun'=>'*分[ぶん]', // amount, share
'bunka'=>'*文化[ぶんか]', // culture
'bunkei'=>'*文型[ぶんけい]', // 
'bunshou'=>'*文章[ぶんしょう]', // sentence, writing
'burausu'=>'*ブラウス', // blouse
'byouin'=>'*病院[びょういん]', // hospital
'byouki'=>'*病気[びょうき]', // illness
'chairo'=>'*茶色[ちゃいろ]', // brown
'chan'=>'*ちゃん',
'chansu'=>'*チャンス', // chance
'chawan'=>'*茶碗[ちゃわん]', // rice bowl
'chichi'=>'*父[ちち]', // speaker’s father
'chigau'=>'*違う[ちがう]', // differ, be wrong
'chikai'=>'*近い[ちかい]', // near, close
'chikaku'=>'*近く[ちかく]', // in the near future, before long
'chikaku'=>'*近く[ちかく]', // near, close to
'chikara'=>'*力[ちから]', // strength, power
'chisai'=>'*小さい[ちさい]', // small
'chizu'=>'*地図[ちず]', // map, atlas
'chokugo'=>'*直接[ちょくせつ]', // directly
'chotto'=>'*ちょっと', // just a moment, just a little
'choudo'=>'*ちょうど', // just, exactly
'chounan'=>'*長男[ちょうなん]', // eldest son
'choushoku'=>'*朝食[ちょうしょく]', // breakfast
'chuugakkou'=>'*中学校[ちゅうがっこう]', // junior high school
'chuugaku'=>'*中学[ちゅうがく]', // junior high
'chuugakusei'=>'*中学生[ちゅうがくせい]', // junior high school student
'chuugoku'=>'*中国[ちゅうごく]', // China
'chuugokujin'=>'*中国人[ちゅうごくじん]', // Chinese
'chuui'=>'*注意[ちゅうい]', // attention, care
'chyuushoku'=>'*昼食[ちゅうしょく]', // lunch
'dai'=>'*第[だい]:台[だい]',
'daigaku'=>'*大学[だいがく]', // university, college
'daigakusei'=>'*大学生[だいがくせい]', // university student
'daiji'=>'*大事[だいじ]', // importance
'daijoubu'=>'*大丈夫[だいじょうぶ]', // all right, OK
'daikirai'=>'*大嫌い[だいきらい]', // hate
'daisuki'=>'*大好き[だいすき]', // like something a lot
'dame'=>'*駄目[だめ]', // no good
'dare'=>'*誰[だれ]', // who
'dareka'=>'*誰か[だれか]', // someone
'dasu'=>'*出す[だす]', // take out
'dekiru'=>'*できる', // can do, be good at
'denki'=>'*電気[でんき]', // electricity, electric light
'densha'=>'*電車[でんしゃ]', // train
'denwa'=>'*電話[でんわ]', // telephone, phone call
'deru'=>'*出る[でる]', // go out, leave
'desu'=>'*です',
'desuka'=>'*ですか',
'doa'=>'*ドア', // door loan word
'docchi'=>'*どっち', // which casual
'dochira'=>'*どちら', // which
'doko'=>'*どこ', // where
'donata'=>'*どなた', // who
'dondon'=>'*どんどん', // knock, bang
'dore'=>'*どれ', // what, which
'doru'=>'*ドル', // dollar
'doryoku'=>'*努力[どりょく]', // endeavor, effort
'dou'=>'*どう', // how, what
'doubutsu'=>'*動物[どうぶつ]', // animal
'douro'=>'*道路[どうろ]', // road
'doushite'=>'*どうして', // how come
'douzo'=>'*どうぞ', // please
'doyoubi'=>'*土曜日[どようび]', // Saturday
'eiga'=>'*映画[えいが]', // movie
'eigo'=>'*英語[えいご]', // English
'eki'=>'*駅[えき]', // train station
'en'=>'*円[えん]', // circle, Japanese yen
'erabu'=>'*選ぶ[えらぶ]', // choose, elect
'erebe-ta-'=>'*エレベーター', // elevator
'fo-ku'=>'*フォーク', // fork
'fueru'=>'*増える[ふえる]', // increase, accrue
'fujidaigaku'=>'*富士大学[ふじだいがく]',
'fukai'=>'*深い[ふかい]', // deep, profound
'fuku'=>'*服[ふく]', // clothes
'fukushuu'=>'*復習[ふくしゅう]', // review
'fukuzatsu'=>'*複雑[ふくざつ]', // complicated, intricate
'furo'=>'*風呂[ふろ]', // bath
'furu'=>'*振る[ふる]', // wave, shake
'furu'=>'*降る[ふる]', // fall, come down rain, snow, etc.
'furui'=>'*古い[ふるい]', // old
'futari'=>'*二人[ふたり]',
'futari'=>'*二人[ふたり]', // two persons
'futatsu'=>'*二つ[ふたつ]', // two things
'futoi'=>'*太い[ふとい]', // thick, fat
'futsuka'=>'*二日[ふつか]', // two days, second of the month
'futsuu'=>'*普通[ふつう]', // normal, regular
'fuufu'=>'*夫婦[ふうふ]', // husband and wife, married couple
'fuyasu'=>'*増やす[ふやす]', // increase
'fuyu'=>'*冬[ふゆ]', // winter
'gaikoku'=>'*外国[がいこく]', // foreign country
'gaikokujin'=>'*外国人[がいこくじん]', // foreigner
'gakkou'=>'*学校[がっこう]', // school
'gakusei'=>'*学生[がくせい]', // student
'ganbaru'=>'*頑張る[がんばる]', // work hard, do one’s best
'garasu'=>'*ガラス', // glass material
'gasu'=>'*ガス', // gas loan word
'ge-mu'=>'*ゲーム', // game
'genkan'=>'*玄関[げんかん]', // entrance, door
'genki'=>'*元気[げんき]', // healthy, energetic
'getsuyoubi'=>'*月曜日[げつようび]', // Monday
'ginkou'=>'*銀行[ぎんこう]', // bank
'ginkouin'=>'*銀行員[ぎんこういん]',
'go'=>'*五[ご]', // five
'gochisou'=>'*ごちそう', // feast, treat
'gochisousuru'=>'*ごちそうする', // treat, host a meal
'gogo'=>'*午後[ごご]', // afternoon, p.m.
'gohan'=>'*ご飯[ごはん]', // meal, cooked rice
'gonin'=>'*五人[ごにん]',
'gorufu'=>'*ゴルフ', // golf
'goshujin'=>'*ご主人[ごしゅじん]', // someone else’s husband
'goukaku'=>'*合格[ごうかく]', // pass an examination
'gozen'=>'*午前[ごぜん]', // morning, a.m.
'guru-pu'=>'*グループ', // group
'gyuuniku'=>'*牛肉[ぎゅうにく]', // beef
'ha'=>'*は:歯[は]', // tooth
'haburashi'=>'*歯ブラシ[はぶらし]', // toothbrush
'hachi'=>'*八[はち]', // eight
'hachinin'=>'*八人[はちにん]',
'hagemasu'=>'*励ます[はげます]', // encourage, cheer up
'haha'=>'*母[は]hあ', // speaker’s mother
'hai'=>'*はい:杯[はい]',
'hairu'=>'*入る[はいる]', // enter
'hajimaru'=>'*始まる[はじまる]', // begin
'hajime'=>'*初め[はじめ]', // beginning
'hajimemashite'=>'*初[はじ]めまして',
'hajimeru'=>'*始める[はじめる]', // start something
'hajimete'=>'*初めて[はじめて]', // for the first time
'hakkiri'=>'*はっきり', // clearly
'hakobu'=>'*運ぶ[はこぶ]', // carry, transport
'haku'=>'*履く[はく]', // put on shoes, wear pants, skirt
'hana'=>'*花[はな]', // flower
'hana'=>'*鼻[はな]', // nose
'hanashi'=>'*話[はなし]', // talk, story
'hanashiau'=>'*話し合う[はなしあう]', // discuss, talk over
'hanasu'=>'*話す[はなす]', // speak, talk
'hanbun'=>'*半分[はんぶん]', // half
'hankachi'=>'*ハンカチ', // handkerchief
'hannichi'=>'*半日[はんにち]', // half a day
'hantai'=>'*反対[はんたい]', // oppose, object
'hantsuki'=>'*半月[はんつき]', // half a month
'harau'=>'*払う[はらう]', // pay money, respect, attention, etc.
'hare'=>'*晴れ[はれ]', // fine weather, clear sky
'hareru'=>'*晴れる[はれる]', // be sunny, clear up
'haru'=>'*春[はる]', // spring
'hashi'=>'*橋[はし]:箸[はし]', // bridge
'hashiru'=>'*走る[はしる]', // run
'hataraku'=>'*働く[はたらく]', // work
'hatsuka'=>'*二十日[はつか]', // days, th of the month
'hayai'=>'*早い[はやい]', // early
'hayai'=>'*速い[はやい]', // fast
'hayaku'=>'*早く[はやく]', // early, soon
'hayaru'=>'*流行る[はやる]', // be in fashion, be popular
'heisei'=>'*平成[へいせい]', // Heisei era
'heiwa'=>'*平和[へいわ]', // peace, harmony
'henji'=>'*返事[へんじ]', // reply, answer, response
'heru'=>'*減る[へる]', // decrease, diminish
'heta'=>'*下手[へた]', // not good at
'heya'=>'*部屋[へや]', // room
'hi'=>'*火[ひ]', // fire, flame
'hidari'=>'*左[ひだり]', // left
'hidarigawa'=>'*左側[ひだりがわ]', // left side
'higashi'=>'*東[ひがし]', // east, eastern
'hiji'=>'*肘[ひじ]', // elbow
'hijouni'=>'*非常に[ひじょうに]', // very, extremely
'hiki'=>'*匹[ひき]', // insects, cats, dogs, etc
'hikouki'=>'*飛行機[ひこうき]', // airplane
'hiku'=>'*引く[ひく]', // draw, pull
'hikui'=>'*低い[ひくい]', // low, short
'himitsu'=>'*秘密[ひみつ]', // secret, privacy
'hiragana'=>'*平仮名[ひらがな]', // hiragana
'hiraku'=>'*開く[ひらく]', // open
'hiraku'=>'*開く[ひらく]', // open books, eyes, etc.
'hiroi'=>'*広い[ひろい]', // wide, big
'hiru'=>'*昼[ひる]', // daytime, midday
'hiruma'=>'*昼間[ひるま]', // daytime, during the day
'hito'=>'*人[ひと]', // person
'hitori'=>'*一人[ひとり]', // one person
'hitoride'=>'*一人で[ひとりで]', // by oneself, alone
'hitotsu'=>'*一つ[ひとつ]', // one thing
'hitsuyou'=>'*必要[ひつよう]', // need, necessary
'hiza'=>'*膝[ひざ]', // knee
'hoka'=>'*他[ほか]', // other Japanese origin
'hon'=>'*本[ほん]', // book, volume
'hontou'=>'*本当[ほんとう]', // reality, genuine
'hontouni'=>'*本当に[ほんとうに]', // really, truly
'honya'=>'*本屋[ほにゃ]', // bookstore
'hoshii'=>'*欲しい[ほしい]', // want, desire of the speaker
'hosoi'=>'*細い[ほそい]', // thin, slender
'hoteru'=>'*ホテル', // hotel
'hotondo'=>'*ほとんど', // almost, hardly
'hou'=>'*方[ほう]', // direction, side
'houkou'=>'*方向[ほうこう]', // direction, course
'hyaku'=>'*百[ひゃく]', // hundred
'ichi'=>'*一[いち]:位置[いち]', // one
'ichiban'=>'*一番[いちばん]', // most, best
'ichibu'=>'*一部[いちぶ]', // part
'ie'=>'*家[いえ]', // home, household
'ie'=>'*家[いえ]', // house, dwelling
'igai'=>'*以外[いがい]', // except for
'ii'=>'*いい', // good in/spoken form
'iie'=>'*いいえ', // good in/spoken form
'ijou'=>'*以上[いじょう]', // more than, not less than
'iken'=>'*意見[いけん]', // opinion
'ikiru'=>'*生きる[いきる]', // live one’s life
'iku'=>'*行く[いく]', // go
'ikura'=>'*いくら', // how much money
'ikutsu'=>'*いくつ', // how many, how old
'ima'=>'*今[いま]', // now
'imi'=>'*意味[いみ]', // meaning, sense
'imouto'=>'*妹[いもうと]', // younger sister
'inu'=>'*犬[いぬ]', // dog
'ippai'=>'*いっぱい', // full
'ippiki'=>'*一匹[いっぴき]',
'ireru'=>'*入れる[いれる]', // put in
'iro'=>'*色[いろ]', // color
'iroiro'=>'*色々[いろいろ]', // a variety of
'iru'=>'*いる', // be present, stay
'iru'=>'*要る[いる]', // need, require
'isha'=>'*医者[いしゃ]', // doctor
'isogashii'=>'*忙しい[いそがしい]', // busy, occupied
'isogu'=>'*急ぐ[いそぐ]', // hurry, do quickly
'issho'=>'*一緒[いっしょ]', // together, same
'issho'=>'*一緒に[いっしょ][に]', // together, at the same time
'isu'=>'*椅子[いす]', // chair
'itai'=>'*痛い[いたい]', // sore, painful
'itazura'=>'*いたずら', // mischief, prank
'itoko'=>'*いとこ', // cousin
'itsu'=>'*いつ', // when
'itsugoro'=>'*いつ頃[いつごろ]', // about when, about what time
'itsuka'=>'*いつか', // some time, some day
'itsuka'=>'*五日[いつか]', // five days, fifth of the month
'itsumo'=>'*いつも', // always
'itsutsu'=>'*五つ[いつ]tす', // five things
'iu'=>'*言う[いう]', // say, tell
'iya/'=>'*嫌[いや]/[きら]ーい', // dislike situational
'jaarimasen'=>'*じゃありません',
'jagaimo'=>'*ジャガイモ', // potato
'ji'=>'*字[じ]', // individual character, letter
'jibun'=>'*自分[じぶん]', // self, oneself
'jidai'=>'*時代[じだい]', // age, era
'jidousha'=>'*自動車[じどうしゃ]', // automobile
'jikan'=>'*時間[じかん]', // time, hour
'jiko'=>'*事故[じこ]', // accident, trouble
'jimusho'=>'*事務所[じむしょ]', // office, one’s place of business
'jishin'=>'*地震[じしん]', // earthquake
'jisho'=>'*辞書[じしょ]', // dictionary category
'jissai'=>'*実際[じっさい]', // reality, actual state
'jitaku'=>'*自宅[じたく]', // one’s house, one’s home
'jitensha'=>'*自転車[じてんしゃ]', // bicycle
'jiyuu'=>'*自由[じゆう]', // freedom
'josei'=>'*女性[じょせい]', // woman, female
'joubu'=>'*丈夫[じょうぶ]', // healthy, sturdy
'jouzu'=>'*上手[じょうず]', // good, skilled
'junbi'=>'*準備[じゅんび]', // preparation, arrangement
'juu'=>'*よん四十[よんじゅう]', // 
'juu'=>'*七十[ななじゅう]', // 
'juu'=>'*九十[きゅうじゅう]', // 
'juu'=>'*五十[ごじゅう]', // 
'juu'=>'*八十[はちじゅう]', // 
'juu'=>'*六十[ろくじゅう]', // 
'juu'=>'*十[じゅう]', // ten
'juubun'=>'*十分[じゅうぶん]', // enough plentiful
'juugo'=>'*十五[じゅうご]', // 
'juugyo'=>'*授業[じゅうぎょ]', // class session, lecture
'juuhachi'=>'*十八[じゅうはち]', // 
'juuichi'=>'*十一[じゅういち]', // 
'juuini'=>'*十二[じゅうに]', // 
'juukyuo'=>'*十九[じゅうきゅう]', // 
'juunana'=>'*十七[じゅうなな]', // 
'juunin'=>'*十人[じゅうにん]',
'juuroku'=>'*十六[じゅうろく]', // 
'juusan'=>'*十三[じゅうさん]', // 
'juushi'=>'*十四[じゅうし]', // 
'juushichi'=>'*十七[じゅうしち]', // 
'juusho'=>'*住所[じゅうしょ]', // address
'juuyon'=>'*十四[じゅうよん]', // 
'ka'=>'*か:課[か]',
'kaban'=>'*鞄[かばん]', // bag, handbag
'kabe'=>'*壁[かべ]', // wall, partition
'kaburu'=>'*被る[かぶる]', // wear, put on on one’s head
'kadai'=>'*課題[かだい]', // task, assignment
'kaeru'=>'*変える[かえる]', // change something, alter
'kaeru'=>'*帰る[かえる]', // go back home
'kaesu'=>'*返す[かえす]', // return, repay
'kagaku'=>'*科学[かがく]', // science
'kagi'=>'*鍵[かぎ]', // key, lock
'kai'=>'*階[かい]',
'kaigai'=>'*海外[かいがい]', // overseas, abroad
'kaigan'=>'*海岸[かいがん]', // seashore, coast
'kaigi'=>'*会議[かいぎ]', // conference, meeting
'kaimono'=>'*買い物[かいもの]', // shopping, purchase
'kaisatsuguchi'=>'*改札口[かいさつぐち]', // ticket gate
'kaisha'=>'*会社[かいしゃ]', // company, corporation
'kaishain'=>'*会社員[かいしゃいん]', // company employee
'kaiwa'=>'*会話[かいわ]',
'kakeru'=>'*掛ける[かける]', // hang, put on
'kaku'=>'*書く[かく]', // write
'kakunin'=>'*確認[かくにん]', // confirmation
'kamera'=>'*カメラ', // camera
'kami'=>'*紙[かみ]', // paper
'kami'=>'*髪[かみ]', // hair, hairstyle
'kaminoke'=>'*髪の毛[かみのけ]', // hair, each single hair
'kanarazu'=>'*必ず[かならず]', // without exception, always
'kanari'=>'*かなり', // fairly, rather
'kanashii'=>'*悲しい[かなしい]', // sad
'kane'=>'*金[かね]', // money
'kangae'=>'*考え[かんがえ]', // thought, idea
'kangaeru'=>'*考える[かんがえる]', // think, consider
'kanji'=>'*漢字[かんじ]', // Chinese character
'kanjiru'=>'*感じる[かんじる]', // feel, sense
'kanojo'=>'*彼女[かのじょ]', // she, one’s girlfriend
'kantan'=>'*簡単[かんたん]', // simple, easy
'kao'=>'*顔[かお]', // face
'karada'=>'*体[からだ]', // body, physique
'karai'=>'*辛い[からい]', // spicy, hot
'kare'=>'*彼[かれ]', // he, one’s boyfriend
'karera'=>'*彼ら[かれら]', // they
'kariru'=>'*借りる[かりる]', // borrow
'karui'=>'*軽い[かるい]', // light of weight
'kasa'=>'*傘[かさ]', // umbrella, parasol
'kata'=>'*方[かた]', // person form
'kata'=>'*肩[かた]', // shoulder
'katai'=>'*固い[かたい]', // stiff, tight
'katakana'=>'*カタカナ', // katakana
'katei'=>'*家庭[かてい]', // home, family
'katsu'=>'*勝つ[かつ]', // win
'kau'=>'*買う[かう]', // buy
'kawa'=>'*川[かわ]', // river, stream
'kawaii'=>'*可愛い[かわいい]', // cute, sweet
'kawaku'=>'*乾く[かわく]', // become dry
'kawaku'=>'*渇く[かわく]', // be thirsty
'kawaru'=>'*代わる[かわる]', // substitute, be substituted for
'kawaru'=>'*変わる[かわる]', // change, turn into
'kayou'=>'*通う[かよう]', // go to and from, frequent a place
'kayoubi'=>'*火曜日[かようび]', // Tuesday
'kazaru'=>'*飾る[かざる]', // decorate
'kaze'=>'*風[かぜ]', // wind
'kaze'=>'*風邪[かぜ]', // cold illness
'kazegusuri'=>'*風邪薬[かぜぐすり]', // cold medicine
'kazoku'=>'*家族[かぞく]', // family, household
'keiken'=>'*経験[けいけん]', // experience, knowledge
'keisatsu'=>'*警察[けいさつ]', // police
'keitaidenwa'=>'*携帯電話[けいたいでんわ]', // cellular phone
'kekkon'=>'*結婚[けっこん]', // marriage
'kenka'=>'*喧嘩[けんか]', // fight, argument
'kenkou'=>'*健康[けんこう]', // health
'kenkyuusha'=>'*研究者[けんきゅうしゃ]',
'kesa'=>'*今朝[けさ]', // this morning
'kesu'=>'*消す[けす]', // switch off, turn off
'ki'=>'*木[き]', // tree, wood
'kibishii'=>'*厳しい[きびしい]', // strict, severe
'kieru'=>'*消える[きえる]', // be extinguished, disappear
'kigaeru'=>'*着替える[きがえる]', // change clothes
'kihon'=>'*基本[きほん]', // basics
'kiiro'=>'*黄色[きいろ]', // yellow color
'kiiro'=>'*黄色い[きいろ]', // yellow
'kikai'=>'*機械[きかい]', // machine
'kikan'=>'*期間[きかん]', // term, period
'kiken'=>'*危険[きけん]', // danger, dangerous
'kikoeru'=>'*聞こえる[きこえる]', // hear, be heard
'kikoku'=>'*帰国[きこく]', // return to one’s country
'kiku'=>'*聞く[きく]', // hear, ask
'kimaru'=>'*決まる[きまる]', // be decided
'kimeru'=>'*決める[きめる]', // decide, agree upon
'kimochi'=>'*気持ち[きもち]', // feeling, sensation
'kino'=>'*昨日[きのう]', // yesterday
'kinyoubi'=>'*金曜日[きにょうび]', // Friday
'kirai'=>'*嫌い[きらい]', // dislike habitual
'kirei'=>'*綺麗[きれい]', // pretty, clean
'kireru'=>'*切れる[きれる]', // cut well, be sharp
'kiru'=>'*切る[きる]', // cut
'kiru'=>'*着る[きる]', // wear, put on
'kisetsu'=>'*季節[きせつ]', // season
'kita'=>'*北[きた]', // north
'kitanai'=>'*汚い[きたない]', // dirty
'kitte'=>'*切手[きって]', // postage stamp
'kiwotsukeru'=>'*気を付ける[きをつける]', // be careful about, pay attention to
'ko'=>'*子[こ]', // young child, kid
'ko-hi-'=>'*コーヒー', // coffee
'ko-su'=>'*コース', // course, route
'koboreru'=>'*こぼれる', // spill, overflow
'kochi'=>'*こっち', // here, this way casual
'kochira'=>'*こちら', // here, this way, this one, this person
'kodomo'=>'*子供[こども]', // child
'koe'=>'*声[こえ]', // voice, sound
'koko'=>'*ここ', // here
'kokonoka'=>'*九日[ここのか]', // nine days, ninth of the month
'kokonotsu'=>'*九つ[ここのつ]', // nine things
'kokosei'=>'*高校生[ここせい]', // high school student
'kokusai'=>'*国際[こくさい]', // international
'komakai'=>'*細かい[こまかい]', // minute, fine
'komaru'=>'*困る[こまる]', // be in trouble, not know what to do
'kome'=>'*米[こめ]', // rice grain
'konban'=>'*今晩[こんばん]', // this evening, tonight
'kondo'=>'*今度[こんど]', // this time, next time
'kongetsu'=>'*今月[こんげつ]', // this month
'konkai'=>'*今回[こんかい]', // this time
'konogoro'=>'*この頃[このごろ]', // these days, recently
'konpyu-ta-'=>'*コンピューター', // computer
'konshyu'=>'*今週[こん]sひゅ', // this week
'konya'=>'*今夜[こにゃ]', // tonight, this evening
'koppu'=>'*コップ', // cup, glass
'kore'=>'*これ', // this, this one
'korekara'=>'*これから', // from now on, after this
'korera'=>'*これら', // these
'korosu'=>'*殺す[ころす]', // kill
'koshi'=>'*腰[こし]', // waist, lower back
'koshou'=>'*故障[こしょう]', // malfunction, breakdown
'kotae'=>'*答え[こたえ]', // answer, solution
'kotaeru'=>'*答える[こたえる]', // give an answer
'kotoba'=>'*言葉[ことば]', // word, language
'kotoshi'=>'*今年[ことし]', // this year
'kou'=>'*こう', // like this, such
'kouen'=>'*公園[こうえん]', // park, public garden
'koukou'=>'*高校[こうこう]', // high school for short
'kowareru'=>'*壊れる[こわれる]', // break, break down
'kubi'=>'*首[くび]', // neck
'kuchi'=>'*口[くち]', // mouth
'kumo'=>'*雲[くも]', // cloud
'kumori'=>'*曇り[くもり]', // cloudy weather
'kumoru'=>'*曇る[くもる]', // become cloudy
'kuni'=>'*国[くに]', // country
'kuraberu'=>'*比べる[くらべる]', // compare, contrast
'kurai'=>'*暗い[くらい]', // dark, gloomy
'kurasu'=>'*クラス', // class in school
'kureru'=>'*くれる', // be given
'kuri-ningu'=>'*クリーニング', // dry cleaning
'kurikaesu'=>'*繰り返す[くりかえす]', // repeat
'kuroi'=>'*黒い[くろい]', // black, dark
'kuru'=>'*来る[くる]', // come
'kuruma'=>'*車[くるま]', // car, automobile
'kurushii'=>'*苦しい[くるしい]', // painful, agonizing
'kushi'=>'*くし', // comb
'kusuri'=>'*薬[くすり]', // drug, medicine
'kutsushita'=>'*靴下[くつした]', // socks
'kuuki'=>'*空気[くうき]', // air, atmosphere
'kuukou'=>'*空港[くうこう]', // airport for public transportation
'kuunin'=>'*九人[きゅうにん]',
'kuwashii'=>'*詳しい[くわしい]', // detailed
'kyaku'=>'*客[きゃく]:脚[きゃく]', // visitor, customer;脚 used for chairs and seats
'kyakuhon'=>'*脚本[きゃくほん]', // 
'kyakushoku'=>'*脚色[きゃくしょく]', // 
'kyoku'=>'*曲[きょく]', // piece of music
'kyonen'=>'*去年[きょねん]', // last year
'kyou'=>'*今日[きょう]', // today
'kyoudai'=>'*兄弟[きょうだい]', // sibling
'kyouju'=>'*教授[きょうじゅ]', // professor
'kyoukasho'=>'*教科書[きょうかしょ]', // textbook, schoolbook
'kyoushi'=>'*教師[きょうし]', // teacher, instructor
'kyoushitsu'=>'*教室[きょうしつ]', // classroom, class
'kyuu'=>'*九[きゅう]', // nine
'kyuu'=>'*九[きゅう]', // nine used before counter words
'kyuuni'=>'*急に[きゅうに]', // suddenly, unexpectedly
'kyuuryou'=>'*給料[きゅうりょう]', // salary, pay
'maamaa'=>'*まあまあ', // OK, not bad
'machi'=>'*町[まち]', // town, city
'machigaeru'=>'*間違える[まちがえる]', // make a mistake, fail at
'mada'=>'*まだ', // not yet, still
'mado'=>'*窓[まど]', // window
'mae'=>'*前[まえ]', // front, before
'magarikado'=>'*曲がり角[まがりかど]', // corner to turn
'magaru'=>'*曲がる[まがる]', // make a turn, turn
'mago'=>'*孫[まご]', // grandchild
'mai'=>'*枚[まい]',
'mainichi'=>'*毎日[まいにち]', // every day
'maitoshi/'=>'*毎年[まいとし]/[まいねん]', // every year
'maitsuki'=>'*毎月[まいつき]', // every month
'makeru'=>'*負ける[まける]', // lose
'makura'=>'*枕[まくら]', // pillow
'mama'=>'*まま', // as is, still in the current state
'mamoru'=>'*守る[まもる]', // protect, observe
'man'=>'*万[まん]', // ten thousand
'manichi'=>'*万一[まんいち]',
'mannaka'=>'*真ん中[まんなか]', // center, middle casual
'manshon'=>'*マンション', // apartment, residential building
'mata'=>'*また', // again, also, or
'matomeru'=>'*まとめる', // gather together, put in order
'matsu'=>'*待つ[まつ]', // wait, wait for
'mattaku'=>'*全く[まったく]', // entirely, truly
'mawaru'=>'*回る[まわる]', // turn round, go around
'mayu'=>'*眉[まゆ]', // eyebrow
'mazu'=>'*まず', // first of all, to begin with
'mazui'=>'*まずい', // bad taste, distasteful
'me'=>'*目[め]', // eye
'medatsu'=>'*目立つ[めだつ]', // stand out, be conspicuous
'megane'=>'*眼鏡[めがね]', // glasses
'menyu-'=>'*メニュー', // menu
'mezamashitokei'=>'*目覚まし時計[めざましとけい]', // alarm clock
'mezurashii'=>'*珍しい[めずらしい]', // rare, scarce
'mi-tingu'=>'*ミーティング', // meeting
'michi'=>'*道[みち]', // street, way
'midori'=>'*緑[みどり]', // green
'mieru'=>'*見える[みえる]', // be visible, can see
'migi'=>'*右[みぎ]', // right
'migigawa'=>'*右側[みぎがわ]', // right side
'mijikai'=>'*短い[みじかい]', // short, brief
'mikan'=>'*みかん', // tangerine
'mikata'=>'*見方[みかた]', // view, perspective
'mikka'=>'*三日[みっか]', // three days, third of the month
'mimi'=>'*耳[みみ]', // ear
'minami'=>'*南[みなみ]', // south
'minna'=>'*みんな', // everybody
'miru'=>'*見る[みる]', // see, look at
'mise'=>'*店[みせ]', // shop, store
'miseru'=>'*見せる[みせる]', // show
'mitsu'=>'*三つ[みつ]', // three things
'mitsukaru'=>'*見つかる[みつかる]', // be found, be caught
'mitsukeru'=>'*見つける[みつける]', // find
'mizu'=>'*水[みず]', // water
'mochiron'=>'*もちろん', // of course
'modoru'=>'*戻る[もどる]', // return to a point of departure
'mokuyoubi'=>'*木曜日[もくようび]', // Thursday
'mondai'=>'*問題[もんだい]', // problem, question
'morau'=>'*もらう', // receive
'mori'=>'*森[もり]', // forest
'moshi'=>'*もし', // if, in case of
'motsu'=>'*もつ', // last long, be durable
'motsu'=>'*持つ[もつ]', // have, possess
'motteiku'=>'*持って行く[もっていく]', // take, bring
'motto'=>'*もっと', // more
'mou'=>'*もう', // already, yet
'mou'=>'*もう', // another, again
'muika'=>'*六日[むいか]', // six days, sixth of the month
'mukaeru'=>'*迎える[むかえる]', // welcome, receive a visitor
'mukau'=>'*向かう[むかう]', // face, head toward
'mukou'=>'*向こう[むこう]', // over there, on the other side
'mune'=>'*胸[むね]', // chest, breast
'muri'=>'*無理[むり]', // unreasonable, impossible
'musuko'=>'*息子[むすこ]', // son
'musume'=>'*娘[むすめ]', // daughter, girl
'muttsu'=>'*六つ[むっつ]', // six things
'muzukashii'=>'*難しい[むずかしい]', // difficult
'myougonichi/asatte'=>'*明後日[みょうごにち]/あさっ て', // day after tomorrow
'myouji'=>'*名字[みょうじ]', // surname, family name
'nagai'=>'*長い[ながい]', // long
'nagareru'=>'*流れる[ながれる]', // flow, run
'nagasa'=>'*長さ[ながさ]', // length
'nai'=>'*無い[ない]', // to not be
'naka'=>'*中[なか]', // inside, middle
'nakanaka'=>'*なかなか', // rather, pretty
'nakunaru'=>'*亡くなる[なくんある]', // die, pass away
'nakusu'=>'*無くす[なくす]', // lose, get rid of
'namae'=>'*名前[なまえ]', // name
'namida'=>'*涙[なみだ]', // tear
'nana'=>'*七[なな]', // seven Japanese origin
'nana'=>'*七[なんあ]', // seven Chinese origin
'nanatsu'=>'*七つ[なんあつ]', // seven things
'nani'=>'*何[なに]', // what
'nani'=>'*何[なに]', // what
'nanika'=>'*何か[なにか]', // something, some
'nanoka'=>'*七日[なのか]', // seven days, seventh of the month
'nansai'=>'*何歳[なんさい]',
'naoru'=>'*治る[なおる]', // be cured, get well
'naoru'=>'*直る[なおる]', // be repaired, get fixed
'naosu'=>'*直す[なおす]', // repair, fix
'naraberu'=>'*並べる[ならべる]', // line up, arrange
'narabu'=>'*並ぶ[ならぶ]', // line up, be parallel
'nareru'=>'*慣れる[なれる]', // grow accustomed to, get used to
'naru'=>'*なる', // become
'naruhodo'=>'*なるほど', // I see, really
'nasu'=>'*ナス', // eggplant
'natsu'=>'*夏[なつ]', // summer
'naze'=>'*なぜ', // why
'nedan'=>'*値段[ねだん]', // price
'neesan'=>'*姉さん[ねえさん]', // one’s own older sister
'nemui'=>'*眠い[ねむい]', // sleepy
'nemuru'=>'*眠る[ねむる]', // sleep, lie idle
'nendo'=>'*年度[ねんど]', // year, school year
'nenkan'=>'*年間[ねんかん]', // period of one year
'neru'=>'*寝る[ねる]', // lie down and sleep, go to sleep
'netsu'=>'*熱[ねつ]', // heat, fever
'nichi'=>'*二[にち]', // two
'nichi'=>'*日[にち]', // counter for days
'nichiji'=>'*日時[にちじ]', // date and time
'nichiyoubi'=>'*日曜日[にちようび]', // Sunday
'nigeru'=>'*逃げる[にげる]', // escape, run away
'nigiyaka'=>'*賑やか[にぎやか]', // lively, exciting
'nihiki'=>'*二匹[にひき]',
'nihon'=>'*日本[にほん]',
'nihongo'=>'*日本語[にほんご]',
'nihonjin'=>'*日本人[にほんじん]',
'niisan'=>'*兄さん[にいさん]', // one’s own older brother
'nijuu'=>'*二十[にじゅう]', // 
'nikai'=>'*二階[にかい]', // second floor, upstairs
'nikki'=>'*日記[にっき]', // diary
'niku'=>'*肉[にく]', // flesh, meat
'ninjin'=>'*にんじん', // carrot
'ninki'=>'*人気[にんき]', // popularity
'nishi'=>'*西[にし]', // west, western
'niteiru'=>'*似ている[にている]', // look like, resemble
'niwa'=>'*庭[にわ]', // garden, yard
'nobiru'=>'*伸びる[のびる]', // stretch, grow
'noboru'=>'*上る[のぼる]', // go up, climb
'nokoru'=>'*残る[のこる]', // remain, be left over
'nokosu'=>'*残す[のこす]', // leave, leave undone
'nomimono'=>'*飲み物[のみもんお]', // beverage, drink
'nomu'=>'*飲む[のむ]', // drink
'norikaeru'=>'*乗り換える[のりかえる]', // change, transfer
'noru'=>'*乗る[のる]', // ride, take
'noseru'=>'*載せる[のせる]', // place, put on
'nurui'=>'*ぬるい', // tepid, lukewarm
'nyu-su'=>'*ニュース', // news
'nyuugaku'=>'*入学[にゅうがく]', // enter a school, matriculate
'nyuuin'=>'*入院[にゅういん]', // be hospitalized
'oba'=>'*おば', // one’s own aunt
'obaasan'=>'*お祖母さん[おばあさん]', // grandmother
'obasan'=>'*おばさん', // aunt
'oboeru'=>'*覚える[おぼえる]', // memorize, learn
'ocha'=>'*お茶[おちゃ]', // tea
'ochiru'=>'*落ちる[おちる]', // fall, come down
'odoroku'=>'*驚く[おどろく]', // be surprised, be startled
'odoru'=>'*踊る[おどる]', // dance
'ohayougozaimasu'=>'*おはようございます',
'oishasan'=>'*お医者さん[おいしゃさん]', // doctor
'oishi'=>'*美味しい[おいし]', // tasty
'oiwai'=>'*お祝い[おいわい]', // celebrate
'oji'=>'*おじ', // one’s own uncle
'ojiisan'=>'*お祖父さん[おじいさん]', // grandfather
'ojisan'=>'*おじさん', // uncle
'okaasan'=>'*お母さん[おかあさん]', // mother
'okashi'=>'*お菓子[おかし]', // sweets, snacks
'oki'=>'*大きい[おき]', // big
'okiru'=>'*起きる[おきる]', // get up, get out of bed
'okiru'=>'*起きる[おきる]', // occur, happen
'okoru'=>'*起こる[おこる]', // happen
'okosu'=>'*起こす[おこす]', // wake someone up
'oku'=>'*置く[おく]:億[おく]', // put, place
'okureru'=>'*遅れる[おくれる]', // be late
'okuru'=>'*贈る[おくる]', // offer, give
'okuru'=>'*送る[おくる]', // send
'omawarisan'=>'*お巡りさん[おまわりさん]', // police officer
'omiyage'=>'*お土産[おみやげ]', // souvenir
'omoi'=>'*重い[おもい]', // heavy
'omoidasu'=>'*思い出す[おもいだす]', // recollect, recall
'omoshiroi'=>'*面白い[おもしろい]', // interesting, amusing
'omou'=>'*思う[おもう]', // think
'onaji'=>'*同じ[おなじ]', // same, identical
'onaka'=>'*お腹[おなか]', // stomach, belly
'ondo'=>'*温度[おんど]', // temperature
'onegai'=>'*お願い[おねがい]', // favor
'onegaishimasu'=>'*お願[ねが]いします',
'onesan'=>'*お姉さん[おねさん]', // older sister
'ongaku'=>'*音楽[おんがく]', // music
'onisan'=>'*お兄さん[おにさん]', // older brother
'onna'=>'*女[おんな]', // woman
'onna'=>'*女の子[おんな][の][こ]', // little girl
'ooi'=>'*多い[おおい]', // a lot of, many
'ookisa'=>'*大きさ[おおきさ]', // size, dimension
'ooku'=>'*多く[おおく]', // much, largely
'oriru'=>'*下りる[おりる]', // go down, come down
'oriru'=>'*降りる[おりる]', // get off, land
'oshieru'=>'*教える[おしえる]', // teach, tell
'osoi'=>'*遅い[おそい]', // slow, late
'osu'=>'*押す[おす]', // push, press down
'otearai'=>'*お手洗い[おてあらい]', // toilet, bathroom
'oto'=>'*音[おと]', // sound, noise
'otoko'=>'*男[おとこ]', // man, male
'otoko'=>'*男の子[おとこ][の][こ]', // boy
'otona'=>'*大人[おとな]', // adult
'otonashii'=>'*大人しい[おとなしい]', // gentle, quiet
'otosu'=>'*落とす[おとす]', // drop
'ototoi'=>'*一昨日[おととい]', // the day before yesterday
'otousan'=>'*お父さん[おとうさん]', // father, dad
'otouto'=>'*弟[おとうと]', // younger brother
'otsuri'=>'*お釣り[おつり]', // change of money
'otto'=>'*夫[おっと]', // husband
'owari'=>'*終わり[おわり]', // end, conclusion
'owaru'=>'*終わる[おわる]', // finish, end
'oya'=>'*親[おや]', // parent
'pa-ti-'=>'*パーティー', // party
'pa-to'=>'*パート', // part-time
'pasokon'=>'*パソコン', // personal computer
'pasupo-to'=>'*パスポート', // passport
'pe-ji'=>'*ページ', // page
'posuto'=>'*ポスト', // postbox, mailbox
'puroguramu'=>'*プログラム', // program booklet
'raigetsu'=>'*来月[らいげつ]', // next month
'rainen'=>'*来年[らいねん]', // next year
'raishuu'=>'*来週[らいしゅう]', // next week
'rajio'=>'*ラジオ', // radio
'ranchi'=>'*ランチ', // lunch loan word
'rei'=>'*零[れい]:例[れい]', // zero
'reibun'=>'*例文[れいぶん]',
'reko-do'=>'*レコード', // record
'renshuu'=>'*練習[れんしゅう]',
'reshi-to'=>'*レシート', // receipt loan word
'ringo'=>'*りんご', // apple
'riyuu'=>'*理由[りゆう]', // reason, excuse
'roku'=>'*六[ろく]', // six
'rokunin'=>'*六人[ろくにん]',
'ryokou'=>'*旅行[りょこう]', // travel, trip
'ryouhou'=>'*両方[りょうほう]', // both
'ryouri'=>'*料理[りょうり]', // cooking
'ryoushin'=>'*両親[りょうしん]', // parents
'ryuugaku'=>'*留学[りゅうがく]', // study abroad
'sa-bisu'=>'*サービス', // service, on the house
'sagasu'=>'*探す[さがす]', // search for, look for
'sageru'=>'*下げる[さげる]', // lower, turn down
'sai'=>'*歳[さい]',
'saifu'=>'*財布[さいふ]', // purse, wallet
'saigo'=>'*最後[さいご]', // last
'saikin'=>'*最近[さいきん]', // recent, latest
'saisho'=>'*最初[さいしょ]', // first, outset
'sakana'=>'*魚[さかな]', // fish
'sake'=>'*酒[さけ]', // alcohol, rice wine
'saki'=>'*先[さき]', // ahead, first
'sakunen'=>'*昨年[さくねん]', // last year , often used in writing
'sakuya'=>'*昨夜[さくや]', // last night, last evening
'sameru'=>'*冷める[さめる]', // cool off
'samui'=>'*寒い[さむい]', // cold temperature of the air
'san'=>'*三[さん]:さん', // three
'sanbiki'=>'*三匹[さんびき]', // use ひき after 3
'sanjuu'=>'*三十[さんじゅう]', // 
'sannin'=>'*三人[さんにん]',
'sara'=>'*皿[さら]', // plate, counter for plates or helpings
'saraishuu'=>'*再来週[さらいしゅう]', // the week after next
'sarari-man'=>'*サラリーマン', // office worker, company employee
'satou'=>'*砂糖[さとう]', // sugar
'satsu'=>'*冊[さつ]',
'sawaru'=>'*触る[さわる]', // touch, feel
'se'=>'*背[せ]', // height, stature
'se-ta-'=>'*セーター', // sweater
'seikatsu'=>'*生活[せいかつ]', // life, living
'seikou'=>'*成功[せいこう]', // success
'seiseki'=>'*成績[せいせき]', // results, grade
'seito'=>'*生徒[せいと]', // pupil, student
'sekai'=>'*世界[せかい]', // world
'seki'=>'*世紀[せいき]:席[せき]', // century, seat, one’s place
'sekken'=>'*石鹸[せっけん]', // soap
'semai'=>'*狭い[せまい]', // narrow, small
'sen'=>'*千[せん]:線[せん]', // thousand,line
'sensei'=>'*先生[せんせい]', // teacher
'senshu'=>'*選手[せんしゅ]', // athlete, sports player
'senshuu'=>'*先週[せんしゅう]', // last week
'sentaku'=>'*洗濯[せんたく]', // laundry, washing
'setsumei'=>'*説明[せつめい]', // explanation, description
'shaberu'=>'*しゃべる', // chat, talk
'shain'=>'*社員[しゃいん]',
'shakai'=>'*社会[しゃかい]', // society
'shashin'=>'*写真[しゃしん]', // photograph
'shatsu'=>'*シャツ', // shirt
'shi'=>'*四[し]', // four Chinese origin
'shibaraku'=>'*しばらく', // a little while, a while
'shichi'=>'*七[しち]',
'shichinin'=>'*七人[しちにん]',
'shigoto'=>'*仕事[しごと]', // work, job
'shiken'=>'*試験[しけん]', // exam
'shima'=>'*島[しま]', // island Japanese origin
'shimaru'=>'*閉まる[しまる]', // be shut, be closed
'shimau'=>'*仕舞う[しまう]', // put away, put in
'shimei'=>'*氏名[しめい]', // full name
'shimeru'=>'*締める[しめる]', // tighten, fasten
'shimeru'=>'*閉める[しめる]', // shut, close doors, windows, etc.
'shinbun'=>'*新聞[しんぶん]', // newspaper
'shingou'=>'*信号[しんごう]', // signal, traffic light
'shinjiru'=>'*信じる[しんじる]', // believe, trust
'shinpai'=>'*心配[しんぱい]', // anxiety, worry
'shinu'=>'*死ぬ[しぬ]', // die
'shio'=>'*塩[しお]', // salt
'shiraberu'=>'*調べる[しらべる]', // investigate, check
'shiro'=>'*白[しろ]', // white
'shiroi'=>'*白い[しろい]', // white, blank
'shiru'=>'*知る[しる]', // know
'shita'=>'*下[した]', // under, below
'shitsumon'=>'*質問[しつもん]', // question
'shizen'=>'*自然[しぜん]', // natural
'shizen'=>'*自然[しぜん]', // nature
'shizuka'=>'*静か[しずか]', // quiet, tranquil
'shokuba'=>'*職場[しょくば]', // place of work, office
'shokuji'=>'*食事[しょくじ]', // meal
'shougakkou'=>'*小学校[しょうがっこう]', // elementary school
'shoukai'=>'*紹介[しょうかい]', // introduction
'shounen'=>'*少年[しょうねん]', // boy between and years old
'shousetsu'=>'*小説[しょうせつ]', // novel
'shouyu'=>'*醤油[しょうゆ]', // soy sauce
'shujutsu'=>'*手術[しゅじゅつ]', // surgical operation
'shukudai'=>'*宿題[しゅくだい]', // homework
'shuppatsu'=>'*出発[しゅっぱつ]', // departure, starting
'shurui'=>'*種類[しゅるい]', // kind, type
'shuu'=>'*週[しゅう]', // week
'shuumatsu'=>'*週末[しゅうまつ]', // weekend
'sisutemu'=>'*システム', // system loan word
'soba'=>'*そば', // side, vicinity
'sobo'=>'*祖母[そぼ]', // grandmother
'socchi'=>'*そっち', // there casual
'sochira'=>'*そちら', // there, that way
'sodateru'=>'*育てる[そだてる]', // bring up, raise
'sofu'=>'*祖父[そふ]', // grandfather
'soko'=>'*そこ', // there
'sonomama'=>'*そのまま', // as it is, just like that
'sora'=>'*空[そら]', // sky
'sore'=>'*それ', // that, that one
'soto'=>'*外[そと]', // outside, open air
'sotsugyou'=>'*卒業[そつぎょう]', // graduation
'sou'=>'*そう', // so, that way
'soudan'=>'*相談[そうだん]', // consultation, advice
'subarashii'=>'*素晴らしい[すばらしい]', // excellent, wonderful
'sugu'=>'*直ぐ[すぐ]', // at once, soon
'suiyoubi'=>'*水曜日[すいようび]', // Wednesday
'suki'=>'*好き[すき]', // favorite, liked
'sukoshi'=>'*少し[すこし]', // a bit, a little while
'suku'=>'*空く[すく]', // be empty, become less crowded
'sukunai'=>'*少ない[すくない]', // few, little
'sumu'=>'*住む[すむ]', // live, reside
'supo-tsu'=>'*スポーツ', // sport
'suppai'=>'*酸っぱい[すっぱい]', // sour
'supu-n'=>'*スプーン', // spoon
'suru'=>'*する', // do, make
'sushi'=>'*寿司[すし]', // sushi
'susumeru'=>'*進める[すすめる]', // go ahead, proceed
'susumu'=>'*進む[すすむ]', // advance, move forward
'suteru'=>'*捨てる[すてる]', // discard, abandon
'suu'=>'*数[すう]', // number
'suugaku'=>'*数学[すうがく]', // mathematics
'suuji'=>'*数字[すうじ]', // numeric characters
'suwaru'=>'*座る[すわる]', // sit, sit down
'suzushii'=>'*涼しい[すずしい]', // cool of temperature
'tabako'=>'*たばこ', // tobacco, cigarette
'tabemono'=>'*食べ物[たべもの]', // food
'taberu'=>'*食べる[たべる]', // eat
'tabun'=>'*多分[たぶん]', // probably, perhaps
'tada'=>'*ただ', // free
'tadashii'=>'*正しい[ただしい]', // correct, righteous
'taifuu'=>'*台風[たいふう]', // typhoon
'taihen'=>'*大変[たいへん]', // awful, hard
'taisetsu'=>'*大切[たいせつ]', // important, valuable
'taishikan'=>'*大使館[たいしかん]', // embassy
'taiwan'=>'*臺灣 [たいわん]',
'taiyou'=>'*太陽[たいよう]', // sun
'takai'=>'*高い[たかい]', // high, tall
'takasa'=>'*高さ[たかさ]', // height
'takusan'=>'*たくさん', // a lot, in large quantity
'takushi-'=>'*タクシー', // taxi
'tame'=>'*ため', // sake, purpose
'tanomu'=>'*頼む[たのむ]', // order, ask for
'tanoshii'=>'*楽しい[たのしい]', // fun, enjoyable
'tanoshimu'=>'*楽しむ[たのしむ]', // enjoy
'taoreru'=>'*倒れる[たおれる]', // fall over
'tashika'=>'*確か[たしか]', // for sure, for certain
'tasukeru'=>'*助ける[たすける]', // help, save
'tatemono'=>'*建物[たてもの]', // building, structure
'tateru'=>'*建てる[たてる]', // build, erect
'tateru'=>'*立てる[たてる]', // stand, set up
'tatoeba'=>'*例えば[たとえば]', // for example
'tatsu'=>'*立つ[たつ]', // stand, rise
'tazuneru'=>'*訪ねる[たずねる]', // visit, go to see
'te'=>'*手[て]', // hand
'te-buru'=>'*テーブル', // table
'tegami'=>'*手紙[てがみ]', // letter
'teian'=>'*提案[ていあん]', // proposition, proposal
'tempura'=>'*天ぷら[て]mぷら', // Japanese deep-fried food
'tenki'=>'*天気[てんき]', // weather
'terebi'=>'*テレビ', // television
'tesuto'=>'*テスト', // test
'tetsudau'=>'*手伝う[てつだう]', // help, assist
'tisshu'=>'*ティッシュ', // tissue
'to'=>'*戸[と]', // door, sliding door
'tobu'=>'*飛ぶ[とぶ]', // fly
'todoku'=>'*届く[とどく]', // reach, be received
'tojiru'=>'*閉じる[とじる]', // shut, close books, eyes, etc.
'tokei'=>'*時計[とけい]', // clock, watch
'toki'=>'*時[とき]', // time, moment
'tokidoki'=>'*時々[ときどき]', // sometimes
'tokoro'=>'*所[ところ]', // place
'tokubetsu'=>'*特別[とくべつ]', // special
'tokuni'=>'*特に[とくに]', // specially, particularly
'tomaru'=>'*止まる[とまる]', // come to a stop, cease
'tomaru'=>'*泊まる[とまる]', // stay overnight
'tomeru'=>'*止める[とめる]', // stop a car…. 止める yameru give up
'tomodachi'=>'*友達[ともだち]', // friend, companion
'tonari'=>'*隣[となり]', // next to, next door
'tooi'=>'*遠い[とおい]', // far, distant
'tooka'=>'*十日[とおか]', // ten days, tenth of the month
'tooku'=>'*遠く[とおく]', // far away, at a distance
'toori'=>'*通り[とおり]', // street, road
'tooru'=>'*通る[とおる]', // pass, go through
'torakku'=>'*トラック', // truck
'tori'=>'*鳥[とり]', // bird, poultry
'toru'=>'*取る[とる]', // take, get
'toru'=>'*撮る[とる]', // take a photograph, film
'toshi'=>'*年[とし]', // year, age
'toshiue'=>'*年上[としうえ]', // older, senior
'toshokan'=>'*図書館[としょかん]', // library
'totemo'=>'*とても', // very
'tou'=>'*頭[とう]', // cattle, horses
'toukyou'=>'*東京[とうきょう]',
'tsugi'=>'*次[つぎ]', // next
'tsuitachi'=>'*一日[ついたち]', // first of the month
'tsukau'=>'*使う[つかう]', // use, make use of
'tsukeru'=>'*つける', // switch on, turn on
'tsuki'=>'*月[つき]', // moon
'tsuku'=>'*つく', // be on, be switched on
'tsuku'=>'*着く[つく]', // arrive at, reach
'tsukue'=>'*机[つくえ]', // desk
'tsukuru'=>'*作る[つくる]', // make, create
'tsuma'=>'*妻[つま]', // woman
'tsumaranai'=>'*つまらない', // boring, dull
'tsumari'=>'*つまり', // in short, that is to say
'tsumetai'=>'*冷たい[つめたい]', // cold to touch
'tsumori'=>'*つもり', // intention, purpose
'tsureteiku'=>'*連れていく[つれていく]', // take along, bring along a person
'tsuretekuru'=>'*連れて来る[つれてくる]', // bring a person
'tsutaeru'=>'*伝える[つたえる]', // convey, transmit
'tsutomeru'=>'*勤める[つとめる]', // serve, hold a job
'tsuyoi'=>'*強い[つよい]', // strong
'tsuzukeru'=>'*続ける[つずける]', // continue, keep up
'tsuzuku'=>'*続く[つずく]', // continue, follow
'ude'=>'*腕[うで]', // arm
'ue'=>'*上[うえ]', // up, above
'ugokasu'=>'*動かす[うごかす]', // move something
'ugoku'=>'*動く[うごく]', // move
'uketoru'=>'*受け取る[うけとる]', // receive, get
'uma'=>'*馬[うま]', // horse
'umai'=>'*うまい', // good at
'umai'=>'*うまい', // sweet, delicious
'umareru'=>'*生まれる[うまれる]', // be born, come into existence
'umi'=>'*海[うみ]', // sea, ocean
'undou'=>'*運動[うんどう]', // movement, exercise
'unten'=>'*運転[うんてん]', // drive
'ura'=>'*裏[うら]', // the back, the reverse side
'ureru'=>'*売れる[うれる]', // sell, be in demand
'ureshii'=>'*嬉しい[うれしい]', // happy, glad
'urikire'=>'*売り切れ[うりきれ]', // sell out
'uru'=>'*売る[うる]', // sell
'urusai'=>'*うるさい', // noisy, annoying
'ushiro'=>'*後ろ[うしろ]', // back, behind
'usui'=>'*薄い[うすい]', // thin, weak
'uta'=>'*歌[うた]', // song
'utau'=>'*歌う[うたう]', // sing
'utsu'=>'*打つ[うつ]', // hit, strike
'utsukushii'=>'*美しい[うつくしい]', // beautiful
'utsusu'=>'*移す[うつす]', // move, transfer
'wakai'=>'*若い[わかい]', // young
'wakamono'=>'*若者[わかもの]', // young person, youth
'wakareru'=>'*分かれる[わかれる]', // be divided, split off
'wakaru'=>'*分かる[わかる]', // understand
'wakeru'=>'*分ける[わける]', // divide, share
'warau'=>'*笑う[わらう]', // laugh, smile
'warui'=>'*悪い[わるい]', // bad
'wasureru'=>'*忘れる[わすれる]', // forget, leave behind
'watashi'=>'*私[わたし]', // I
'watashitachi'=>'*私たち[わたしたち]', // we
'watasu'=>'*渡す[わたす]', // hand over, give
'we-ta-'=>'*ウェーター', // waiter
'we-toresu'=>'*ウェートレス', // waitress
'yahari'=>'*やはり', // as expected
'yakan'=>'*やかん', // kettle
'yakedo'=>'*火傷[やけど]', // burn
'yakusoku'=>'*約束[やくそく]', // promise, vow
'yakyuu'=>'*野球[やきゅう]', // baseball
'yama'=>'*山[やま]', // mountain
'yamu'=>'*止む[やむ]', // stop, cease
'yaru'=>'*やる', // do, give
'yaru'=>'*やる', // give to an inferior
'yasai'=>'*野菜[やさい]', // vegetable
'yasashi'=>'*易しい[やさし]', // easy, simple
'yasashii'=>'*優しい[やさしい]', // gentle, kind
'yasui'=>'*安い[やすい]', // cheap, inexpensive
'yasumi'=>'*休み[やすみ]', // holiday, break
'yasumu'=>'*休む[やすむ]', // take a rest, take a break
'yatto'=>'*やっと', // at last, finally
'yattsu'=>'*八つ[やっつ]', // eight things
'yobu'=>'*呼ぶ[よぶ]', // call, name
'yoi'=>'*良い[よい]', // good /written form
'yokka'=>'*四日[よっか]', // four days, fourth of the month
'yoko'=>'*横[よこ]', // side, width across
'yoku'=>'*よく', // often, well
'yomu'=>'*読む[よむ]', // read
'yon'=>'*四[よん]', // four Japanese origin
'yonaka'=>'*夜中[よなか]', // midnight
'yonin'=>'*四人[よにん]', // not よん
'yorokobu'=>'*喜ぶ[よろこぶ]', // be happy, be delighted
'yoroshiku'=>'*よろしく', // one’s regards
'yoru'=>'*夜[よる]', // night from sunset to sunrise
'yotei'=>'*予定[よてい]', // schedule, plan
'yotsu'=>'*四つ[よつ]', // four things
'yotsukado'=>'*四つ角[よつかど]', // intersection
'you'=>'*用[よう]', // things to do
'youbi'=>'*曜日[ようび]', // day of the week
'youi'=>'*用意[ようい]', // preparation
'youka'=>'*八日[ようか]', // eight days, eighth of the month
'youkoso'=>'*ようこそ', // welcome greeting
'yowai'=>'*弱い[よわい]', // weak
'yu'=>'*湯[ゆ]', // hot water
'yubi'=>'*指[ゆび]', // finger, toe
'yuki'=>'*雪[ゆき]', // snow, snowfall
'yukkuri'=>'*ゆっくり', // slowly
'yume'=>'*夢[ゆめ]', // dream
'yurui'=>'*緩い[ゆるい]', // slack, loose
'yurusu'=>'*許す[ゆるす]', // permit, forgive
'yuubinkyoku'=>'*郵便局[ゆうびんきょく]', // post office
'yuugata'=>'*夕方[ゆうがた]', // early evening, at dusk
'yuumei'=>'*有名[ゆうめい]', // famous
'yuushoku'=>'*夕食[ゆうしょく]', // supper, dinner
'zannen'=>'*残念[ざんねん]', // regretful, disappointing
'zasshi'=>'*雑誌[ざっし]', // magazine, journal
'zenbu'=>'*全部[ぜんぶ]', // all, whole
'zero'=>'*ゼロ',
'zettaini'=>'*絶対に[ぜったいに]', // absolutely, definitely
'zutto'=>'*ずっと', // all the time, all through
''=>'*[]',
''=>'*[]',
''=>'*[]',
);
?>