<?php
/*
key => : separated values
*/
$romaji_kanji = array(
'aa'=>'*ああ', // ➀ like that, that much
'abiru'=>'*浴びる[あびる]', // ⓪ take a shower
'abunai'=>'*危[あぶ]ない', // ⓪ dangerous
'abura'=>'*油[あぶら]', // ⓪ oil
'acchi'=>'*あっち', // ➂ other side, over there casual
'achikochi'=>'*あちこち', // ➁ち➁ all over, here and there
'achira'=>'*あちら', // ⓪ over there, that way
'adana'=>'*あだ名[な]', // ⓪ nickname
'adobaisu'=>'*アドバイス', // ➁ドバ➁ advice
'agaru'=>'*上[あ]がる', // ⓪ get nervous, go up, increase (in quality or quantity), go up, rise (physical movement)
'ageru'=>'*上[あ]げる', // ⓪ raise, lift, give, offer
'ago'=>'*顎[あご]', // ➂ jaw, chin
'ai'=>'*愛[あい]', // ➀ love
'aida'=>'*間[あいだ]', // ⓪ interval, space between things
'aidea'=>'*アイデア', // ➁イデ➁ idea
'aidoru'=>'*アイドル', // ➀ idol
'aikawarazu'=>'*相変[あいか]わらず', // ⓪ as usual, as before, still
'aimai'=>'*曖昧[あいまい]', // ⓪ ambiguous, vague
'ainiku'=>'*あいにく', // ⓪生憎 unfortunately, we are afraid that
'airon'=>'*アイロン', // ⓪ iron (for clothes)
'aisatsu'=>'*挨拶[あいさつ]', // ➀ greet, greeting
'aisu'=>'*アイス', // ➀ ice cream (for short)
'aisukoohii'=>'*アイスコーヒー', // ア➁イスコーヒ➁ー iced coffee
'aisukuriimu'=>'*アイスクリーム', // ア➁イスクリ➁ーム ice cream
'aisuru'=>'*愛[あい]する', // あ➁いす➁る love, care for
'aite'=>'*相手[あいて]', // ➂ opponent, the other party
'aji'=>'*味[あじ]', // ⓪ taste, flavor
'aka'=>'*赤[あか]', // ➀ red color
'akachan'=>'*赤[あか]ちゃん', // baby (colloquial)
'akai'=>'*赤い[あかい]', // ➂ red
'akaji'=>'*赤字[あかじ]', // ⓪ deficit, in the red
'akanbou'=>'*赤[あか]ん坊[ぼう]', // ⓪ (human) baby
'akarui'=>'*明るい[あかるい]', // ⓪ bright, cheerful
'akeru'=>'*開ける[あける]', // ⓪ open, unlock doors, windows, etc.
'aki'=>'*秋[あき]', // ➀ autumn, fall
'akiraka'=>'*明[あき]らか', // あ➁き➁らか clear, obvious
'akirameru'=>'*諦[あきら]める', // あ➁きらめ➁る abandon, give up
'akireru'=>'*呆[あき]れる', // ⓪ be amazed at, be stunned by (something negative)
'aku'=>'*空[あ]く', // ⓪ become available or vacant
'akubi'=>'*欠伸[あくび]', // ⓪ yawn
'akusesarii'=>'*アクセサリー', // ➀ accessories, jewelry
'akushu'=>'*握手[あくしゅ]', // ➀ handshake
'amai'=>'*甘い[あまい]', // ⓪ sweet
'amachua'=>'*アマチュア', // ⓪ amateur
'amari'=>'*余[あま]り', // ➂ not much
'amaru'=>'*余[あま]る', // あ➁ま➁る remain, be in excess
'ame'=>'*雨[あめ]:飴[あめ]', // ➀ rain ⓪ 飴
'amerika'=>'*アメリカ', // ⓪
'amerikajin'=>'*アメリカ人[じん]', // ア➁メリカ➁人
'amayakasu'=>'*甘[あま]やかす', // あ➁まやか➁す be indulgent to, spoil
'an'=>'*案[あん]', // ➀ plan, idea, proposal
'ana'=>'*穴[あな]', // ➂ hole, deficit, vacancy, flaw
'anata'=>'*貴方[あなた]', // あ➁な➁た you
'anaunsaa'=>'*アナウンサー', // ア➁ナウ➁ンサー announcer
'ane'=>'*姉[あね]', // ⓪ 姐 one’s own older sister
'ani'=>'*兄[あに]', // ➀ one’s own older brother
'ankeeto'=>'*アンケート', // ➀ questionnaire
'ankeetochousa'=>'*アンケート調査[ちょうさ]', // ア➁ンケートちょ➁うさ
'ankeetokekka'=>'*アンケート結果[けっか]', // ア➁ンケートけ➁っか
'anmari'=>'*余[あんま]り', // ➂ (not) that much, (not) so much, => 余[あま]り
'anohito'=>'*あの人[ひと]', // あ➁の➁ひと
'anokata'=>'*あの方[かた]', // ③
'anzen'=>'*安全[あんぜん]', // ⓪ safety, security
'annai'=>'*案内[あんない]', // あ➁んな➁い guide, guidance
'annani'=>'*あんなに', // that much, such, so, to that extent
'anshin'=>'*安心[あんしん]', // ⓪ peace of mind, relief
'antei'=>'*安定[あんてい]', // ⓪ stability, composure
'anzen'=>'*安全[あんぜん]', // ⓪ safety, security
'ao'=>'*青[あお]', // ➀ blue, green
'aoi'=>'*青い[あおい]', // あ➁お➁い blue
'aojiroi'=>'*青白[あおじろ]い', // あ➁おじろ➁い pale
'aozora'=>'*青空[あおぞら]', // あ➁おぞ➁ら blue sky
'apaato'=>'*アパート', // ア➁パ➁ート apartment, flat
'appu'=>'*アップ', // ➀ close-up
'araimono'=>'*洗[あら]い物[もの]', // ⓪ dishes to be washed, laundry
'arata'=>'*新[あら]た', // ➀ new, fresh
'arau'=>'*洗う[あらう]', // ➀ wash
'arawareru'=>'*現[あらわ]れる', // あ➁らわれ➁る appear, emerge
'are'=>'*あれ', // ⓪ that over there
'arekore'=>'*あれこれ[]', // あ➁れ➁これ this and that, one thing or another
'ari'=>'*蟻[あり]', // ⓪ ant
'arigatou'=>'*ありがとう', // あ➁り➁がとう
'arigatougozaimasu'=>'*ありがとうございます',
'arimasen'=>'*ありません', // 
'aru'=>'*有[あ]る:在[あ]る', // ➀ exist, there is
'aruku'=>'*歩く[あるく]', // walk, go on foot
'arubaito'=>'*アルバイト', // ア➁ルバ➁イト part-time job
'arubamu'=>'*アルバム', // ⓪ album
'arukooru'=>'*アルコール', // ⓪ alcohol, alcoholic beverage
'aruku'=>'*歩[ある]く', // あ➁る➁く walk, go on foot
'asa'=>'*朝[あさ]', // ➀ morning
'asagohan'=>'*朝[あさ]ご飯[はん]', // あ➁さご➁はん breakfast
'asai'=>'*浅[あさ]い', // ⓪ shallow, superficial
'ase'=>'*汗[あせ]', // ➀ sweat
'aseru'=>'*焦[あせ]る', // あ➁せ➁る feel pressured, feel hurried
'ashi'=>'*足[あし]', // ➂ leg, foot
'ashikubi'=>'*足首[あしくび]', // あ➁し➁くび ankle
'ashimoto'=>'*足元[あしもと]', // あ➁しも➁と step, under foot
'ashita'=>'*明日[あした]', // ➂ tomorrow
'asobi'=>'*遊[あそ]び', // ⓪ play, amusement
'asobinin'=>'*遊[あそ]び人[にん]', // ⓪ playboy, gambler
'asobu'=>'*遊[あそ]ぶ', // ⓪ play
'asoko'=>'*あそこ', // ⓪ over there
'assari'=>'*あっさり', // あ➁っさ➁り bluntly, easily, flatly
'asu'=>'*明日[あす]', // ➂ tomorrow (rather formal)
'ataeru'=>'*与[あた]える', // ⓪ give (formal)
'atama'=>'*頭[あたま]', // ➂ head
'atarashii'=>'*新[あたら]しい', // あ➁たらし➁い new
'atari'=>'*辺[あたり]', // ➀ vicinity, neighbourhood
'atarimae'=>'*当[あ]たり前[まえ]', // ⓪ no wonder, natural
'ataru'=>'*当[あ]たる', // ⓪ go straight and hit, strike
'atatakai'=>'*暖[あたた]かい', // あ➁たたか➁い warm
'atatamaru'=>'*暖[あたた]まる', // あ➁たたま➁る get warm
'atatameru'=>'*暖[あたた]める', // あ➁たため➁る warm (something) up
'atena'=>'*宛名[あてな]', // ⓪ name of recipient, addressee
'atesaki'=>'*宛先[あてさき]', // ⓪ recipient’s address
'atesakihenkou'=>'*あて先[さき]変更[へんこう]', // (computing) redirection
'ato'=>'*後[あと]', // ➀ after, behind, remainder
'atokatazuke'=>'*後片[あとかた]付[づ]け', // あ➁とか➁たづけ cleaning up
'atomodori'=>'*後戻[あともど]り', // あ➁とも➁どり turning back, retreat
'atsui'=>'*厚[あつ]い:暑[あつ]い:熱[あつ]い', // ⓪ thick, bulky; あ➁つ➁い hot of weather, hot to touch
'atsukau'=>'*扱[あつか]う', // ⓪ handle, deal with
'atsumaru'=>'*集まる[あつまる]', // あ➁つま➁る gather, be collected
'atsumeru'=>'*集める[あつめる]', // あ➁つめ➁る collect, gather
'atsusa'=>'*厚さ[あつさ]:暑さ[]', // ⓪ thickness; ➀ heat
'atsusaatari'=>'*暑さあたり', // あ➁つさ'あ➁たり heatstroke
'au'=>'*会[あ]う:合[あ]う:遭[あ]う:遇[あ]う', // ➀ meet; ➀ fit, match; ➀ meet, encounter, get caught in
'awaseru'=>'*合[あ]わせる', // あ➁わせ➁る match (something), adapt (oneself)
'awatadashii'=>'*慌[あわ]ただしい', // あ➁わただし➁い busy and hurried, rapid, sudden
'awateru'=>'*慌[あわ]てる', // ⓪ be flustered, be in a hurry
'ayamaru'=>'*謝[あやま]る', // あ➁やま➁る apologize, decline, be at a loss
'ayashii'=>'*怪[あや]しい', // ⓪ suspicious, dubious
'azukaru'=>'*預[あず]かる', // あ➁ずか➁る take care of, keep
'azukeru'=>'*預[あず]ける', // あ➁ずけ➁る deposit, leave (something) with (someone)
'ba'=>'*場[]', // occasion, situation
'baagen'=>'*バーゲン[]', // bargain sale
'baai'=>'*場合[ばあい]', // situation, case
'baggu'=>'*バッグ', // bag
'bai'=>'*倍[]', // double, times
'baiku'=>'*バイク[]', // motorcycle
'baiorin'=>'*バイオリン[]', // violin
'baiten'=>'*売店[]', // booth, shop
'baito'=>'*バイト[]', // part-time job
'bajji'=>'*バッジ[]', // badge
'baka'=>'*ばか[]', // foolish, stupid
'bakku'=>'*バック[]', // back, reverse
'ban'=>'*晩[ばん]:番[]', // evening; one’s turn, watch
'banana'=>'*バナナ[]', // banana
'bangou'=>'*番号[ばんごう]', // ➁んご➁ assigned number
'bangumi'=>'*番組[ばんぐみ]', // program
'Bara'=>'*ばら[]', // rose
'barabara'=>'*ばらばら[]', // separately, discretely
'baransu'=>'*バランス[]', // balance
'bareehooru'=>'*バレーボール[]', // volleyball
'basho'=>'*場所[ばしょ]', // place, space
'basu'=>'*バス', // bus
'basukettobo-ru'=>'*バスケットボール[]', // basketball
'basutei'=>'*バス停[ばすてい]', // bus stop
'bata-'=>'*バター[]', // butter
'batsu'=>'*バツ[]', // cross, x-mark (on errors, mistakes etc.)
'beddo'=>'*ベッド[]', // bed
'bengoshi'=>'*弁護士[]', // lawyer, attorney
'benkyou'=>'*勉強[べんきょう]', // study
'benri'=>'*便利[]', // convenience
'bentou'=>'*弁当[]', // boxed lunch
'beru'=>'*ベル[]', // bell
'beruto'=>'*ベルト[]', // belt
'besuto'=>'*ベスト[]', // best
'betabeta'=>'*べたべた[]', // stick together, sticky
'betsu'=>'*別[べつ]', // another, different
'betsubetsu'=>'*別々[]', // separately
'betsuni'=>'*別に[]', // particularly, not really

'bideo'=>'*ビデオ', // video
'biichi'=>'*ビーチ[]', // beach
'biiru'=>'*ビール', // beer
'bijin'=>'*美人[]', // beautiful woman
'bijinesu'=>'*ビジネス[]', // business
'bijutsukan'=>'*美術館[]', // art museum
'bikkurisuru'=>'*びっくりする[]', // be surprised, be startled (casual)
'bin'=>'*瓶[びん]', // bottle
'binbou'=>'*貧乏[]', // poverty, destitution
'biniiru'=>'*ビニール[]', // plastic, vinyl
'biru'=>'*ビル', // building
'bishobisho'=>'*びしょびしょ[]', // soaking wet, soaked
'bisshori'=>'*びっしょり[]', // drenched, soaked
'biza'=>'*ビザ[]', // visa
'boifurendo'=>'*ボーイフレンド[]', // boyfriend
'boku'=>'*僕[ぼく]', // ➀⓪ I, me usually used by young males
'bonyari'=>'*ぼんやり[]', // vacantly, absent-mindedly
'booru'=>'*ボール[]', // ball
'boorupan'=>'*ボールパン',
'booto'=>'*ボート[]', // light boat, small craft
'borupen'=>'*ボールペン', // ballpoint pen
'boryuumu'=>'*ボリューム[]', // volume
'botan'=>'*ボタン[]', // button
'boueki'=>'*貿易[]', // (export and import) trade
'bounenkai'=>'*忘年会[]', // year-end party
'bouryoku'=>'*暴力[]', // violence, force
'boushi'=>'*帽子[ぼうし]', // hat, cap
'bubun'=>'*部分[]', // part, section
'buchou'=>'*部長[]', // department head
'budou'=>'*ぶどう[]', // grapes
'bun'=>'*分[ぶん]:文[]', // amount, share
'bunbougu'=>'*文房具[]', // stationery, writing materials
'bunka'=>'*文化[ぶんか]', // culture
'bunkei'=>'*文型[ぶんけい]', // 
'bunseki'=>'*分析[]', // analysis
'bunshou'=>'*文章[ぶんしょう]', // sentence, writing
'bunya'=>'*分野[]', // field, area
'burabura'=>'*ぶらぶら[]', // wander, walk around
'burasagaru'=>'*ぶら下がる[]', // hang down, dangle
'burashi'=>'*ブラシ[]', // brush
'burausu'=>'*ブラウス', // blouse
'buruburu'=>'*ぶるぶる[]', // shivering, trembling
'byouin'=>'*病院[びょういん]', // hospital
'buta'=>'*豚[]', // pig
'butai'=>'*舞台[]', // stage, setting
'butaniku'=>'*豚肉[]', // pork
'butsubutsu'=>'*ぶつぶつ[]', // in a mutter, mumble
'butsukaru'=>'*ぶつかる[]', // hit, bump into
'buumu'=>'*ブーム[]', // fad, boom
'byouin'=>'*病院[]', // hospital
'byouin'=>'*美容院[]', // hair salon
'byouki'=>'*病気[びょうき]', // illness
'byounin'=>'*病人[]', // sick person
'cha'=>'*茶[]', // tea
'chairo'=>'*茶色[ちゃいろ]', // brown
'chan'=>'*ちゃん',
'channeru'=>'*チャンネル[]', // channel
'chansu'=>'*チャンス', // chance
'chanto'=>'*ちゃんと[]', // correctly, properly
'chawan'=>'*茶碗[ちゃわん]', // rice bowl
'chenji'=>'*チェンジ', // change, exchange
'chi'=>'*地[]:血[]', // ground, place; blood (colloquial)
'chichi'=>'*父[ちち]', // speaker’s father
'chichioya'=>'*父親[]', // father
'chigai'=>'*違[ちが]い', // ⓪ difference, mistake
'chigai'=>'*違[ちが]います', // That's wrong
'chigau'=>'*違う[ちがう]', // differ, be wrong
'chihou'=>'*地方[]', // local region
'chiiki'=>'*地域[]', // region, area
'chiimu'=>'*チーム[]', // team
'chiisai'=>'*小さい[]', // small
'chiizu'=>'*チーズ', // cheese
'chika'=>'*地下[]', // underground
'chikaduku'=>'*近付く[]', // approach, come close
'chikai'=>'*近い[ちかい]', // near, close
'chikaku'=>'*近く[ちかく]', // in the near future, before long, near, close to
'chikamichi'=>'*近道[]', // shortcut
'chikara'=>'*力[ちから]', // strength, power
'chikatetsu'=>'*地下鉄[]', // subway
'chikayoru'=>'*近寄る[]', // go near, approach
'chiketto'=>'*チケット[]', // ticket (loan word)
'chikoku'=>'*遅刻[]', // tardiness, lateness
'chikyuu'=>'*地球[]', // the earth
'chirakaru'=>'*散らかる[]', // be in a mess, lie scattered
'chirakasu'=>'*散らかす[]', // make a mess
'chiryou'=>'*治療[]', // medical treatment
'chisai'=>'*小さい[ちさい]', // small
'chishiki'=>'*知識[]', // knowledge
'chittomo'=>'*ちっとも[]', // not at all
'chizu'=>'*地図[ちず]', // map, atlas
'chokin'=>'*貯金[]', // savings, deposit
'chokoreeto'=>'*チョコレート:チョコ', // ➁コレ➁
'chokugo'=>'*直接[ちょくせつ]', // directly
'chokusetsu'=>'*直接[]', // directly
'chosha'=>'*著者[]', // author, writer
'chotto'=>'*ちょっと', // just a moment, just a little
'chou'=>'*朝[ちょう]', // ➀ dynasty, period
'chousen'=>'*朝鮮[ちょうせん]', // ちょ➁うせ➁ん
'choudo'=>'*ちょうど', // just, exactly
'choujo'=>'*長女[]', // eldest daughter
'choukan'=>'*朝刊[]', // morning edition paper
'chouki'=>'*長期[]', // long period
'chounan'=>'*長男[ちょうなん]', // eldest son
'chousei'=>'*調整[]', // regulation, adjustment
'choushoku'=>'*朝食[ちょうしょく]', // breakfast
'chuu'=>'*中[]', // middle, medium size
'chuudoku'=>'*中毒[]', // poisoning, addiction
'chuugakkou'=>'*中学校[ちゅうがっこう]', // junior high school
'chuugaku'=>'*中学[ちゅうがく]', // junior high
'chuugakusei'=>'*中学生[ちゅうがくせい]', // junior high school student
'chuugoku'=>'*中国[ちゅうごく]', // China
'chuugokujin'=>'*中国人[ちゅうごくじん]', // Chinese
'chuui'=>'*注意[ちゅうい]', // attention, care
'chuukyuu'=>'*中級[]', // middle-class, intermediate
'chuumoku'=>'*注目[]', // attention, notice
'chuumon'=>'*注文[]', // order
'chuuou'=>'*中央[]', // center, middle
'chuusha'=>'*注射[]', // injection, shot
'chuushajou'=>'*駐車場[]', // parking area, parking lot
'chuushi'=>'*中止[]', // suspension, cancellation
'chuushin'=>'*中心[]', // center (of a circle, etc.), core
'chuushoku'=>'*昼食[ちゅうしょく]', // lunch
'chuushouteki'=>'*抽象的[]', // abstract
'chyuushoku'=>'*昼食[]', // lunch
'dabudabu'=>'*だぶだぶ[]', // baggy, too big
'dai'=>'*大[]:第[だい]:台[だい]',
'daibu'=>'*大分[]', // greatly, fairly, highly
'daidokoro'=>'*台所[]', // kitchen
'daigaku'=>'*大学[だいがく]', // university, college
'daigakuin'=>'*大学院[]', // graduate school
'daigakusei'=>'*大学[だいがく]生[せい]', // university student
'daihyou'=>'*代表[]', // representative
'daiji'=>'*大事[だいじ]', // importance
'daijin'=>'*大臣[]', // minister
'daijoubu'=>'*大丈夫[だいじょうぶ]', // all right, OK
'daikirai'=>'*大嫌い[だいきらい]', // hate
'daikon'=>'*大根[]', // oriental radish
'daisuki'=>'*大好き[だいすき]', // like something a lot
'daitai'=>'*大体[]', // about, anyway
'Daitouryou'=>'*大統領[]', // president (of a country)
'dame'=>'*駄目[だめ]', // no good
'danbou'=>'*暖房[]', // heating
'dandan'=>'*段々[]', // gradually, little by little
'dankai'=>'*段階[]', // stage, phase
'dansei'=>'*男性[]', // male, man
'dansu'=>'*ダンス[]', // dance, dancing (loan word)
'dantai'=>'*団体[]', // group, organization
'darashinai'=>'*だらしない[]', // untidy, sloppy
'dare'=>'*誰[だれ]', // who
'dareka'=>'*誰か[だれか]', // someone
'darui'=>'*だるい[]', // feel run-down, weary
'dasu'=>'*出す[だす]', // take out
'deeto'=>'*デート[]', // date, romantic meeting
'deau'=>'*出会う[]', // meet, encounter
'deeta'=>'*データ[]', // data
'deguchi'=>'*出口[]', // exit
'deiriguchi'=>'*出入り口[]', // doorway, gateway
'dekakeru'=>'*出掛ける[]', // go out, leave home
'dekiru'=>'*できる', // can do, be good at
'dekirudake'=>'*できるだけ[]', // as (much) as possible
'dekoboko'=>'*でこぼこ[]', // unevenness, bumpiness
'denchi'=>'*電池[]', // battery
'dengon'=>'*伝言[]', // message
'denki'=>'*電気[でんき]', // electricity, electric light
'densha'=>'*電車[でんしゃ]', // train
'denshi'=>'*電子[]', // electron, electronic
'dentou'=>'*伝統[]', // tradition
'denwa'=>'*電話[でんわ]', // telephone, phone call
'denwachou'=>'*電話帳[]', // telephone book
'depaato'=>'*デパート[]', // department store (loan word)
'deru'=>'*出る[でる]', // go out, leave
'desu'=>'*です',
'desuka'=>'*ですか',
'desuku'=>'*デスク',

'dezaato'=>'*デザート[]', // dessert
'dezain'=>'*デザイン[]', // design


'doa'=>'*ドア', // door loan word
'docchi'=>'*どっち', // which casual
'dochira'=>'*どちら', // which
'Dokidoki'=>'*どきどき[]', // feel excited, feel nervous
'dokitto'=>'*どきっと[]', // surprised, shocked
'doko'=>'*どこ', // where
'doku'=>'*どく[]', // get out of the way, step aside
'dokuritsu'=>'*独立[]', // independence, self-reliance
'dokusha'=>'*読者[]', // reader
'dokushin'=>'*独身[]', // single, unmarried
'dokusho'=>'*読書[]', // reading books
'donata'=>'*どなた', // who
'dondon'=>'*どんどん', // knock, bang, quickly, rapidly
'dono'=>'*何[ど]の', // ➀ which
'doraibu'=>'*ドライブ[]', // drive (loan word)
'dorama'=>'*ドラマ[]', // drama
'dore'=>'*どれ', // what, which
'doresu'=>'*ドレス[]', // formal dress
'dorobou'=>'*泥棒[]', // thief, burglar
'doru'=>'*ドル', // dollar
'doryoku'=>'*努力[どりょく]', // endeavor, effort
'dou'=>'*どう', // how, what
'doubutsu'=>'*動物[どうぶつ]', // animal
'doubutsuen'=>'*動物園[]', // zoo
'doujou'=>'*同情[]', // sympathy, compassion
'doumo'=>'*どうも', // for no special reason, somehow; Bitte sehr!
'dounika'=>'*どうにか[]', // somehow
'douro'=>'*道路[どうろ]', // road
'douse'=>'*どうせ[]', // anyway
'doushite'=>'*どうして', // how come
'doushitemo'=>'*どうしても[]', // by any means, really
'douyou'=>'*同様[]', // similar, the same as
'douzo'=>'*どうぞ', // please, here you are
'doyoubi'=>'*土曜日[どようび]', // Saturday
'douzoyoroshiku'=>'*どうぞよろしく:どうぞよろしくお願い[おねがい]', // please to meet you; please be nice to me

'eiga'=>'*映画[えいが]', // movie
'eigo'=>'*英語[えいご]', // English
'eki'=>'*駅[えき]', // train station
'en'=>'*円[えん]', // circle, Japanese yen
'enjinia'=>'*エンジニア', // エ➁ンジ➁ニア
'enjiniaringu'=>'*エンジニアリング', // エ➁ンジニ➁アリング
'enpitsu'=>'*鉛筆[えんぴつ]',
'erabu'=>'*選ぶ[えらぶ]', // choose, elect
'erebeetaa'=>'*エレベーター', // elevator
'fooku'=>'*フォーク', // fork
'fueru'=>'*増える[ふえる]', // increase, accrue
'fujidaigaku'=>'*富士[ふじ]大学[だいがく]',
'fukai'=>'*深い[ふかい]', // deep, profound
'fuku'=>'*服[ふく]', // clothes
'fukushuu'=>'*復習[ふくしゅう]', // review
'fukuzatsu'=>'*複雑[ふくざつ]', // complicated, intricate
'furo'=>'*風呂[ふろ]', // bath
'furu'=>'*振る[ふる]', // wave, shake
'furu'=>'*降る[ふる]', // fall, come down rain, snow, etc.
'furui'=>'*古い[ふるい]', // old
'futari'=>'*二人[ふたり]',
'futari'=>'*二人[ふたり]', // two persons
'futatsu'=>'*二つ[ふたつ]', // two things
'futoi'=>'*太い[ふとい]', // thick, fat
'futsuka'=>'*二日[ふつか]', // two days, second of the month
'futsuu'=>'*普通[ふつう]', // normal, regular
'fuufu'=>'*夫婦[ふうふ]', // husband and wife, married couple
'fuyasu'=>'*増やす[ふやす]', // increase
'fuyu'=>'*冬[ふゆ]', // winter
'gaikoku'=>'*外国[がいこく]', // foreign country
'gaikokujin'=>'*外国人[がいこくじん]', // foreigner
'gakkou'=>'*学校[がっこう]', // school
'gakusei'=>'*学生[がくせい]', // student
'ganbaru'=>'*頑張る[がんばる]', // work hard, do one’s best
'garasu'=>'*ガラス', // glass material
'gasu'=>'*ガス', // gas loan word
'geemu'=>'*ゲーム', // game
'genkan'=>'*玄関[げんかん]', // entrance, door
'genki'=>'*元気[げんき]', // healthy, energetic
'getsuyoubi'=>'*月曜日[げつようび]', // Monday
'gin'=>'*銀', // ➀
'ginkou'=>'*銀行[ぎんこう]', // bank
'ginkouin'=>'*銀行員[ぎんこういん]',
'go'=>'*五[ご]', // five
'gochisou'=>'*ごちそう', // feast, treat
'gochisousuru'=>'*ごちそうする', // treat, host a meal
'gogo'=>'*午後[ごご]', // afternoon, p.m.
'gohan'=>'*ご飯[ごはん]', // meal, cooked rice
'gonin'=>'*五人[ごにん]',
'gorufu'=>'*ゴルフ', // golf
'goshujin'=>'*ご主人[ごしゅじん]', // someone else’s husband
'goukaku'=>'*合格[ごうかく]', // pass an examination
'gozen'=>'*午前[ごぜん]', // morning, a.m.
'guruupu'=>'*グループ', // group
'gyuuniku'=>'*牛肉[ぎゅうにく]', // beef
'ha'=>'*は:歯[は]', // tooth
'haburashi'=>'*歯ブラシ[はぶらし]', // toothbrush
'hachi'=>'*八[はち]', // ➂ eight
'hachinin'=>'*八人[はちにん]',
'hagemasu'=>'*励ます[はげます]', // encourage, cheer up
'haha'=>'*母[は]hあ', // speaker’s mother
'hai'=>'*はい:杯[はい]',
'hairu'=>'*入る[はいる]', // enter
'hajimaru'=>'*始まる[はじまる]', // begin
'hajime'=>'*初め[はじめ]', // beginning
'hajimemashite'=>'*初[はじ]めまして', // I am meeting you for the first time
'hajimeru'=>'*始める[はじめる]', // start something
'hajimete'=>'*初めて[はじめて]', // for the first time
'hakkiri'=>'*はっきり', // clearly
'hakobu'=>'*運ぶ[はこぶ]', // carry, transport
'haku'=>'*履く[はく]', // put on shoes, wear pants, skirt
'hana'=>'*花[はな]', // flower
'hana'=>'*鼻[はな]', // nose
'hanashi'=>'*話[はなし]', // talk, story
'hanashiau'=>'*話し合う[はなしあう]', // discuss, talk over
'hanasu'=>'*話す[はなす]', // speak, talk
'hanbun'=>'*半分[はんぶん]', // half
'hankachi'=>'*ハンカチ', // handkerchief
'hannichi'=>'*半日[はんにち]', // half a day
'hantai'=>'*反対[はんたい]', // oppose, object
'hantsuki'=>'*半月[はんつき]', // half a month
'harau'=>'*払う[はらう]', // pay money, respect, attention, etc.
'hare'=>'*晴れ[はれ]', // fine weather, clear sky
'hareru'=>'*晴れる[はれる]', // be sunny, clear up
'haru'=>'*春[はる]', // spring
'hashi'=>'*橋[はし]:箸[はし]', // bridge
'hashiru'=>'*走る[はしる]', // run
'hataraku'=>'*働く[はたらく]', // work
'hatsuka'=>'*二十日[はつか]', // days, th of the month
'hayai'=>'*早い[はやい]', // early
'hayai'=>'*速い[はやい]', // fast
'hayaku'=>'*早く[はやく]', // early, soon
'hayaru'=>'*流行る[はやる]', // be in fashion, be popular
'heisei'=>'*平成[へいせい]', // Heisei era
'heiwa'=>'*平和[へいわ]', // peace, harmony
'henko'=>'*変更[へんこう]', // ⓪
'henji'=>'*返事[へんじ]', // reply, answer, response
'heru'=>'*減る[へる]', // decrease, diminish
'heta'=>'*下手[へた]', // not good at
'heya'=>'*部屋[へや]', // room
'hi'=>'*火[ひ]', // fire, flame
'hidari'=>'*左[ひだり]', // left
'hidarigawa'=>'*左側[ひだりがわ]', // left side
'higashi'=>'*東[ひがし]', // east, eastern
'hiji'=>'*肘[ひじ]', // elbow
'hijouni'=>'*非常に[ひじょうに]', // very, extremely
'hiki'=>'*匹[ひき]', // insects, cats, dogs, etc
'hikouki'=>'*飛行機[ひこうき]', // airplane
'hiku'=>'*引く[ひく]', // draw, pull
'hikui'=>'*低い[ひくい]', // low, short
'himitsu'=>'*秘密[ひみつ]', // secret, privacy
'hiragana'=>'*平仮名[ひらがな]', // hiragana
'hiraku'=>'*開く[ひらく]', // open
'hiraku'=>'*開く[ひらく]', // open books, eyes, etc.
'hiroi'=>'*広い[ひろい]', // wide, big
'hiru'=>'*昼[ひる]', // daytime, midday
'hiruma'=>'*昼間[ひるま]', // daytime, during the day
'hito'=>'*人[ひと]', // person
'hitori'=>'*一人[ひとり]', // one person
'hitoride'=>'*一人で[ひとりで]', // by oneself, alone
'hitotsu'=>'*一つ[ひとつ]', // one thing
'hitsuyou'=>'*必要[ひつよう]', // need, necessary
'hiza'=>'*膝[ひざ]', // knee
'hoka'=>'*他[ほか]', // other Japanese origin
'hon'=>'*本[ほん]', // book, volume
'honkon'=>'*ホンコン', // ①
'hontou'=>'*本当[ほんとう]', // reality, genuine
'hontouni'=>'*本当に[ほんとうに]', // really, truly
'honya'=>'*本屋[ほにゃ]', // bookstore
'hoshii'=>'*欲しい[ほしい]', // want, desire of the speaker
'hosoi'=>'*細い[ほそい]', // thin, slender
'hoteru'=>'*ホテル', // hotel
'hotondo'=>'*ほとんど', // almost, hardly
'hou'=>'*方[ほう]', // direction, side
'houkou'=>'*方向[ほうこう]', // direction, course
'hyaku'=>'*百[ひゃく]', // hundred
'ichi'=>'*一[いち]:位置[いち]', // ➂ one
'ichiban'=>'*一番[いちばん]', // most, best
'ichibu'=>'*一部[いちぶ]', // part
'ie'=>'*家[いえ]', // home, household
'ie'=>'*家[いえ]', // house, dwelling
'igai'=>'*以外[いがい]', // except for
'ii'=>'*いい', // good in/spoken form
'iie'=>'*いいえ', // good in/spoken form
'ijou'=>'*以上[いじょう]', // more than, not less than
'iken'=>'*意見[いけん]', // opinion
'ikiru'=>'*生きる[いきる]', // live one’s life
'iku'=>'*行く[いく]', // go
'ikura'=>'*いくら', // how much money
'ikutsu'=>'*幾[いく]つ', // how many, how old
'ima'=>'*今[いま]', // now
'imi'=>'*意味[いみ]', // meaning, sense
'imouto'=>'*妹[いもうと]', // younger sister
'inu'=>'*犬[いぬ]', // dog
'ippai'=>'*いっぱい', // full
'ippiki'=>'*一匹[いっぴき]',
'ireru'=>'*入れる[いれる]', // put in
'iro'=>'*色[いろ]', // color
'iroiro'=>'*色々[いろいろ]', // a variety of
'iru'=>'*いる', // be present, stay
'iru'=>'*要る[いる]', // need, require
'isha'=>'*医者[いしゃ]', // doctor
'isogashii'=>'*忙しい[いそがしい]', // busy, occupied
'isogu'=>'*急ぐ[いそぐ]', // hurry, do quickly
'issho'=>'*一緒[いっしょ]', // together, same
'issho'=>'*一緒に[いっしょ][に]', // together, at the same time
'isu'=>'*椅子[いす]', // chair
'itai'=>'*痛い[いたい]', // sore, painful
'itazura'=>'*いたずら', // mischief, prank
'itoko'=>'*いとこ', // cousin
'itsu'=>'*いつ', // when
'itsugoro'=>'*いつ頃[いつごろ]', // about when, about what time
'itsuka'=>'*いつか', // some time, some day
'itsuka'=>'*五日[いつか]', // five days, fifth of the month
'itsumo'=>'*いつも', // always
'itsusu'=>'*五[い]つす', // five things
'iu'=>'*言う[いう]', // say, tell
'iya'=>'*嫌[いや]/[きら]ーい', // dislike situational
'jaarimasen'=>'*じゃありません',
'jagaimo'=>'*ジャガイモ', // potato
'ji'=>'*字[じ]', // individual character, letter
'jibun'=>'*自分[じぶん]', // self, oneself
'jidai'=>'*時代[じだい]', // age, era
'jidousha'=>'*自動車[じどうしゃ]', // automobile
'jikan'=>'*時間[じかん]', // time, hour
'jiko'=>'*事故[じこ]', // accident, trouble
'jimusho'=>'*事務所[じむしょ]', // office, one’s place of business
'jin'=>'*人[じん]', // pitch becomes ➁
'jishin'=>'*地震[じしん]', // earthquake
'jisho'=>'*辞書[じしょ]', // dictionary category
'jissai'=>'*実際[じっさい]', // reality, actual state
'jitaku'=>'*自宅[じたく]', // one’s house, one’s home
'jitensha'=>'*自転車[じてんしゃ]', // bicycle
'jiyuu'=>'*自由[じゆう]', // freedom
'josei'=>'*女性[じょせい]', // woman, female
'joubu'=>'*丈夫[じょうぶ]', // healthy, sturdy
'jouzu'=>'*上手[じょうず]', // good, skilled
'junbi'=>'*準備[じゅんび]', // preparation, arrangement
'juu'=>'*よん四十[よんじゅう]', // 
'juu'=>'*七十[ななじゅう]', // 
'juu'=>'*九十[きゅうじゅう]', // 
'juu'=>'*五十[ごじゅう]', // 
'juu'=>'*八十[はちじゅう]', // 
'juu'=>'*六十[ろくじゅう]', // 
'juu'=>'*十[じゅう]', // ten
'juubun'=>'*十分[じゅうぶん]', // enough plentiful
'juugo'=>'*十五[じゅうご]', // 
'juugyo'=>'*授業[じゅうぎょ]', // class session, lecture
'juuhachi'=>'*十八[じゅうはち]', // 
'juuichi'=>'*十一[じゅういち]', // 
'juuini'=>'*十二[じゅうに]', // 
'juukyuo'=>'*十九[じゅうきゅう]', // 
'juunana'=>'*十七[じゅうなな]', // 
'juunin'=>'*十人[じゅうにん]',
'juuroku'=>'*十六[じゅうろく]', // 
'juusan'=>'*十三[じゅうさん]', // 
'juushi'=>'*十四[じゅうし]', // 
'juushichi'=>'*十七[じゅうしち]', // 
'juusho'=>'*住所[じゅうしょ]', // address
'juuyon'=>'*十四[じゅうよん]', // 
'ka'=>'*か:課[か]',
'kaado'=>'*',
'kaban'=>'*鞄[かばん]', // bag, handbag
'kabe'=>'*壁[かべ]', // wall, partition
'kaburu'=>'*被る[かぶる]', // wear, put on on one’s head
'kadai'=>'*課題[かだい]', // task, assignment
'kaeru'=>'*変える[かえる]', // change something, alter
'kaeru'=>'*帰る[かえる]', // go back home
'kaesu'=>'*返す[かえす]', // return, repay
'kagaku'=>'*科学[かがく]', // science
'kagi'=>'*鍵[かぎ]', // key, lock
'kai'=>'*会[かい]:階[かい]',
'kaigai'=>'*海外[かいがい]', // overseas, abroad
'kaigan'=>'*海岸[かいがん]', // seashore, coast
'kaigi'=>'*会議[かいぎ]', // conference, meeting
'kaimono'=>'*買い物[かいもの]', // shopping, purchase
'kaisatsuguchi'=>'*改札口[かいさつぐち]', // ticket gate
'kaisha'=>'*会社[かいしゃ]', // company, corporation
'kaishain'=>'*会社員[かいしゃいん]', // company employee
'kaiwa'=>'*会話[かいわ]',
'kakeru'=>'*掛ける[かける]', // hang, put on
'kaku'=>'*書く[かく]', // write
'kakunin'=>'*確認[かくにん]', // confirmation
'kamera'=>'*カメラ', // camera
'kami'=>'*紙[かみ]', // paper
'kami'=>'*髪[かみ]', // hair, hairstyle
'kaminoke'=>'*髪の毛[かみのけ]', // hair, each single hair
'kanarazu'=>'*必ず[かならず]', // without exception, always
'kanari'=>'*かなり', // fairly, rather
'kanashii'=>'*悲しい[かなしい]', // sad
'kane'=>'*金[かね]', // money
'kangae'=>'*考え[かんがえ]', // thought, idea
'kangaeru'=>'*考える[かんがえる]', // think, consider
'kanji'=>'*漢字[かんじ]', // Chinese character
'kanjiru'=>'*感じる[かんじる]', // feel, sense
'kanojo'=>'*彼女[かのじょ]', // she, one’s girlfriend
'kantan'=>'*簡単[かんたん]', // simple, easy
'kao'=>'*顔[かお]', // face
'kara'=>'*から', // アメリカから，これから
'karada'=>'*体[からだ]', // body, physique
'karai'=>'*辛い[からい]', // spicy, hot
'kare'=>'*彼[かれ]', // he, one’s boyfriend
'karera'=>'*彼ら[かれら]', // they
'kariru'=>'*借りる[かりる]', // borrow
'karui'=>'*軽い[かるい]', // light of weight
'kasa'=>'*傘[かさ]', // umbrella, parasol
'kata'=>'*方[かた]:肩[かた]', // direction, person, shoulder
'katai'=>'*固い[かたい]', // stiff, tight
'katakana'=>'*カタカナ', // katakana
'katei'=>'*家庭[かてい]', // home, family
'katsu'=>'*勝つ[かつ]', // win
'kau'=>'*買う[かう]', // buy
'kawa'=>'*川[かわ]', // river, stream
'kawaii'=>'*可愛い[かわいい]', // ➁わい➁ cute, sweet
'kawaku'=>'*乾く[かわく]', // become dry
'kawaku'=>'*渇く[かわく]', // be thirsty
'kawaru'=>'*代わる[かわる]', // substitute, be substituted for
'kawaru'=>'*変わる[かわる]', // change, turn into
'kayou'=>'*通う[かよう]', // go to and from, frequent a place
'kayoubi'=>'*火曜日[かようび]', // Tuesday
'kazaru'=>'*飾る[かざる]', // decorate
'kaze'=>'*風[かぜ]', // wind
'kaze'=>'*風邪[かぜ]', // cold illness
'kazegusuri'=>'*風邪薬[かぜぐすり]', // cold medicine
'kazoku'=>'*家族[かぞく]', // family, household
'kei'=>'*兄[けい]', // ➀
'keiken'=>'*経験[けいけん]', // experience, knowledge
'keisatsu'=>'*警察[けいさつ]', // police
'keitaidenwa'=>'*携帯電話[けいたいでんわ]', // cellular phone
'kekkon'=>'*結婚[けっこん]', // marriage
'kenka'=>'*喧嘩[けんか]', // fight, argument
'kenkou'=>'*健康[けんこう]', // health
'kenkyuusha'=>'*研究者[けんきゅうしゃ]',
'kesa'=>'*今朝[けさ]', // this morning
'kesu'=>'*消す[けす]', // switch off, turn off
'ki'=>'*木[き]', // tree, wood
'kibishii'=>'*厳しい[きびしい]', // strict, severe
'kieru'=>'*消える[きえる]', // be extinguished, disappear
'kigaeru'=>'*着替える[きがえる]', // change clothes
'kihon'=>'*基本[きほん]', // basics
'kiiro'=>'*黄色[きいろ]', // yellow color
'kiiro'=>'*黄色い[きいろ]', // yellow
'kikai'=>'*機械[きかい]', // machine
'kikan'=>'*期間[きかん]', // term, period
'kiken'=>'*危険[きけん]', // danger, dangerous
'kikoeru'=>'*聞こえる[きこえる]', // hear, be heard
'kikoku'=>'*帰国[きこく]', // return to one’s country
'kiku'=>'*聞く[きく]', // hear, ask
'kimaru'=>'*決まる[きまる]', // be decided
'kimeru'=>'*決める[きめる]', // decide, agree upon
'kimashita'=>'*来[き]ました',
'kimi'=>'*君[きみ]:気味[きみ]:黄身[きみ]:鬼魅[きみ]', // egg yolk
'kimitsu'=>'*機密[きみつ]',
'kimochi'=>'*気持ち[きもち]', // feeling, sensation
'kino'=>'*昨日[きのう]', // yesterday
'kinyoubi'=>'*金曜日[きにょうび]', // Friday
'kirai'=>'*嫌い[きらい]', // dislike habitual
'kirei'=>'*綺麗[きれい]', // pretty, clean
'kireru'=>'*切れる[きれる]', // cut well, be sharp
'kiru'=>'*切る[きる]', // cut
'kiru'=>'*着る[きる]', // wear, put on
'kisetsu'=>'*季節[きせつ]', // season
'kita'=>'*北[きた]', // north
'kitanai'=>'*汚い[きたない]', // dirty
'kitte'=>'*切手[きって]', // postage stamp
'kiwotsukeru'=>'*気を付ける[きをつける]', // be careful about, pay attention to
'ko'=>'*子[こ]', // young child, kid
'koboreru'=>'*こぼれる', // spill, overflow
'kochi'=>'*こっち', // here, this way casual
'kochira'=>'*こちら', // here, this way, this one, this person
'kochirakoso'=>'*こちらこそ', // it is I who should say so
'kodomo'=>'*子供[こども]', // child
'koe'=>'*声[こえ]', // voice, sound
'koko'=>'*ここ', // here
'kokonoka'=>'*九日[ここのか]', // nine days, ninth of the month
'kokonotsu'=>'*九つ[ここのつ]', // nine things
'kokosei'=>'*高校生[ここせい]', // high school student
'kokusai'=>'*国際[こくさい]', // international
'komakai'=>'*細かい[こまかい]', // minute, fine
'komaru'=>'*困る[こまる]', // be in trouble, not know what to do
'kome'=>'*米[こめ]', // rice grain
'konban'=>'*今晩[こんばん]', // this evening, tonight
'kondo'=>'*今度[こんど]', // this time, next time
'kongetsu'=>'*今月[こんげつ]', // this month
'konichiwa'=>'*こんにちは',
'konkai'=>'*今回[こんかい]', // this time
'kono'=>'*この', // ⓪
'konogoro'=>'*この頃[このごろ]', // these days, recently
'konpuutaa'=>'*コンピューター',
'konpyuutaa'=>'*コンピューター', // computer
'konshyu'=>'*今週[こん]sひゅ', // this week
'konya'=>'*今夜[こにゃ]', // tonight, this evening
'koohii'=>'*コーヒー', // coffee
'koosu'=>'*コース', // course, route
'koppu'=>'*コップ', // cup, glass
'kore'=>'*これ', // this, this one
'korekara'=>'*此[こ]れから', // from now on, after this
'korera'=>'*これら', // these
'korosu'=>'*殺す[ころす]', // kill
'koshi'=>'*腰[こし]', // waist, lower back
'koshou'=>'*故障[こしょう]', // malfunction, breakdown
'kotae'=>'*答え[こたえ]', // answer, solution
'kotaeru'=>'*答える[こたえる]', // give an answer
'kotoba'=>'*言葉[ことば]', // word, language
'kotoshi'=>'*今年[ことし]', // this year
'kou'=>'*こう', // like this, such
'kouen'=>'*公園[こうえん]', // park, public garden
'koukou'=>'*高校[こうこう]', // high school for short
'kowareru'=>'*壊れる[こわれる]', // break, break down
'ku'=>'*く:九[く]',
'kubi'=>'*首[くび]', // neck
'kuchi'=>'*口[くち]', // mouth
'kumo'=>'*雲[くも]', // cloud
'kumori'=>'*曇り[くもり]', // cloudy weather
'kumoru'=>'*曇る[くもる]', // become cloudy
'kuni'=>'*国[くに]', // country
'kuraberu'=>'*比べる[くらべる]', // compare, contrast
'kurai'=>'*暗い[くらい]', // dark, gloomy
'kurasu'=>'*クラス', // class in school
'kureru'=>'*くれる', // be given
'kuriiningu'=>'*クリーニング', // dry cleaning
'kurikaesu'=>'*繰り返す[くりかえす]', // repeat
'kuroi'=>'*黒い[くろい]', // black, dark
'kuru'=>'*来る[くる]', // come
'kuruma'=>'*車[くるま]', // car, automobile
'kurushii'=>'*苦しい[くるしい]', // painful, agonizing
'kushi'=>'*くし', // comb
'kusuri'=>'*薬[くすり]', // drug, medicine
'kutsushita'=>'*靴下[くつした]', // socks
'kuuki'=>'*空気[くうき]', // air, atmosphere
'kuukou'=>'*空港[くうこう]', // ⓪ airport for public transportation
'kuunin'=>'*九人[きゅうにん]',
'kuwashii'=>'*詳しい[くわしい]', // detailed
'kyaku'=>'*客[きゃく]:脚[きゃく]', // visitor, customer;脚 used for chairs and seats
'kyakuhon'=>'*脚本[きゃくほん]', // 
'kyakushoku'=>'*脚色[きゃくしょく]', // 
'kyoku'=>'*曲[きょく]', // piece of music
'kyonen'=>'*去年[きょねん]', // last year
'kyou'=>'*今日[きょう]', // today
'kyoudai'=>'*兄弟[きょうだい]', // sibling
'kyouju'=>'*教授[きょうじゅ]', // professor
'kyoukasho'=>'*教科書[きょうかしょ]', // textbook, schoolbook
'kyoushi'=>'*教師[きょうし]', // teacher, instructor
'kyoushitsu'=>'*教室[きょうしつ]', // classroom, class
'kyuu'=>'*九[きゅう]', // nine
'kyuu'=>'*九[きゅう]', // nine used before counter words
'kyuuni'=>'*急に[きゅうに]', // suddenly, unexpectedly
'kyuuryou'=>'*給料[きゅうりょう]', // salary, pay
'maamaa'=>'*まあまあ', // OK, not bad
'machi'=>'*町[まち]', // town, city
'machigaeru'=>'*間違える[まちがえる]', // make a mistake, fail at
'mada'=>'*まだ', // not yet, still
'mado'=>'*窓[まど]', // window
'mae'=>'*前[まえ]', // front, before
'magarikado'=>'*曲がり角[まがりかど]', // corner to turn
'magaru'=>'*曲がる[まがる]', // make a turn, turn
'mago'=>'*孫[まご]', // grandchild
'mai'=>'*枚[まい]',
'mainichi'=>'*毎日[まいにち]', // every day
'maitoshi/'=>'*毎年[まいとし]/[まいねん]', // every year
'maitsuki'=>'*毎月[まいつき]', // every month
'makao'=>'*マカオ', // ➀ Macao
'makeru'=>'*負ける[まける]', // lose
'makura'=>'*枕[まくら]', // pillow
'mama'=>'*まま', // as is, still in the current state
'mamoru'=>'*守る[まもる]', // protect, observe
'man'=>'*万[まん]', // ten thousand
'manichi'=>'*万一[まんいち]',
'mannaka'=>'*真ん中[まんなか]', // center, middle casual
'manshon'=>'*マンション', // apartment, residential building
'marumaru'=>'*◯◯[まるまる]', //
'mata'=>'*また', // again, also, or
'matomeru'=>'*まとめる', // gather together, put in order
'matsu'=>'*待つ[まつ]', // wait, wait for
'mattaku'=>'*全く[まったく]', // entirely, truly
'mawaru'=>'*回る[まわる]', // turn round, go around
'mayu'=>'*眉[まゆ]', // eyebrow
'mazu'=>'*まず', // first of all, to begin with
'mazui'=>'*まずい', // bad taste, distasteful
'me'=>'*目[め]', // eye
'medatsu'=>'*目立つ[めだつ]', // stand out, be conspicuous
'megane'=>'*眼鏡[めがね]', // glasses
'meishi'=>'*名刺[めいし]',
'menyuu'=>'*メニュー', // menu
'mezamashitokei'=>'*目覚まし時計[めざましとけい]', // alarm clock
'mezurashii'=>'*珍しい[めずらしい]', // rare, scarce
'michi'=>'*道[みち]', // street, way
'midori'=>'*緑[みどり]', // green
'mieru'=>'*見える[みえる]', // be visible, can see
'migi'=>'*右[みぎ]', // right
'migigawa'=>'*右側[みぎがわ]', // right side
'miitingu'=>'*ミーティング', // meeting
'mijikai'=>'*短い[みじかい]', // short, brief
'mikan'=>'*みかん', // tangerine
'mikata'=>'*見方[みかた]', // view, perspective
'mikka'=>'*三日[みっか]', // three days, third of the month
'mimi'=>'*耳[みみ]', // ear
'minami'=>'*南[みなみ]', // south
'minna'=>'*みんな', // everybody
'miru'=>'*見る[みる]', // see, look at
'mise'=>'*店[みせ]', // shop, store
'miseru'=>'*見せる[みせる]', // show
'mitsu'=>'*三つ[みつ]', // three things
'mitsukaru'=>'*見つかる[みつかる]', // be found, be caught
'mitsukeru'=>'*見つける[みつける]', // find
'mizu'=>'*水[みず]', // water
'mochiron'=>'*もちろん', // of course
'modoru'=>'*戻る[もどる]', // return to a point of departure
'mokuyoubi'=>'*木曜日[もくようび]', // Thursday
'mondai'=>'*問題[もんだい]', // ⓪ problem, question
'mondainai'=>'*問題[もんだい]ない', // no problem
'morau'=>'*もらう', // receive
'mori'=>'*森[もり]', // forest
'moshi'=>'*もし', // if, in case of
'motsu'=>'*もつ', // last long, be durable
'motsu'=>'*持つ[もつ]', // have, possess
'motteiku'=>'*持って行く[もっていく]', // take, bring
'motto'=>'*もっと', // more
'mou'=>'*もう', // already, yet
'mou'=>'*もう', // another, again
'muika'=>'*六日[むいか]', // six days, sixth of the month
'mukaeru'=>'*迎える[むかえる]', // welcome, receive a visitor
'mukau'=>'*向かう[むかう]', // face, head toward
'mukou'=>'*向こう[むこう]', // over there, on the other side
'mune'=>'*胸[むね]', // chest, breast
'muri'=>'*無理[むり]', // unreasonable, impossible
'musuko'=>'*息子[むすこ]', // son
'musume'=>'*娘[むすめ]', // daughter, girl
'muttsu'=>'*六つ[むっつ]', // six things
'muzukashii'=>'*難しい[むずかしい]', // difficult
'myougonichi/asatte'=>'*明後日[みょうごにち]/あさっ て', // day after tomorrow
'myouji'=>'*名字[みょうじ]', // surname, family name
'nagai'=>'*長い[ながい]', // long
'nagareru'=>'*流れる[ながれる]', // flow, run
'nagasa'=>'*長さ[ながさ]', // length
'nai'=>'*無い[ない]', // to not be
'naka'=>'*中[なか]', // inside, middle
'nakanaka'=>'*なかなか', // rather, pretty
'nakunaru'=>'*亡くなる[なくんある]', // die, pass away
'nakusu'=>'*無くす[なくす]', // lose, get rid of
'namae'=>'*名前[なまえ]', // name
'namida'=>'*涙[なみだ]', // tear
'nan'=>'*何[なん]',
'nana'=>'*七[なな]', // seven Japanese origin
'nana'=>'*七[なんあ]', // ➀ seven Chinese origin
'nanatsu'=>'*七つ[なんあつ]', // seven things
'nani'=>'*何[なに]', // what
'nanika'=>'*何か[なにか]', // something, some
'nanoka'=>'*七日[なのか]', // seven days, seventh of the month
'nansai'=>'*何歳[なんさい]',
'naoru'=>'*治る[なおる]', // be cured, get well
'naoru'=>'*直る[なおる]', // be repaired, get fixed
'naosu'=>'*直す[なおす]', // repair, fix
'naraberu'=>'*並べる[ならべる]', // line up, arrange
'narabu'=>'*並ぶ[ならぶ]', // line up, be parallel
'narau'=>'*習[なら]う', // な➁ら➁う to take lessons in, to study
'nareru'=>'*慣れる[なれる]', // grow accustomed to, get used to
'narimasu'=>'*成[な]ります', // become
'naru'=>'*成[な]る', // become
'naruhodo'=>'*なるほど', // I see, really
'nasu'=>'*ナス', // eggplant
'natsu'=>'*夏[なつ]', // summer
'naze'=>'*なぜ', // why
'nedan'=>'*値段[ねだん]', // price
'neesan'=>'*姉さん[ねえさん]', // one’s own older sister
'nemui'=>'*眠い[ねむい]', // sleepy
'nemuru'=>'*眠る[ねむる]', // sleep, lie idle
'nendo'=>'*年度[ねんど]', // year, school year
'nenkan'=>'*年間[ねんかん]', // period of one year
'neru'=>'*寝る[ねる]', // lie down and sleep, go to sleep
'netsu'=>'*熱[ねつ]', // heat, fever
'nichi'=>'*二[にち]', // two
'nichi'=>'*日[にち]', // counter for days
'nichiji'=>'*日時[にちじ]', // date and time
'nichiyoubi'=>'*日曜日[にちようび]', // Sunday
'nigeru'=>'*逃げる[にげる]', // escape, run away
'nigiyaka'=>'*賑やか[にぎやか]', // lively, exciting
'nihiki'=>'*二匹[にひき]',
'nihon'=>'*日本[にほん]',
'nihongo'=>'*日本語[にほんご]',
'nihonjin'=>'*日本人[にほんじん]',
'niisan'=>'*兄さん[にいさん]', // one’s own older brother
'nijuu'=>'*二十[にじゅう]', // 
'nikai'=>'*二階[にかい]', // second floor, upstairs
'nikki'=>'*日記[にっき]', // diary
'niku'=>'*肉[にく]', // flesh, meat
'ninjin'=>'*にんじん', // carrot
'ninki'=>'*人気[にんき]', // popularity
'nishi'=>'*西[にし]', // west, western
'niteiru'=>'*似ている[にている]', // look like, resemble
'niwa'=>'*庭[にわ]', // garden, yard
'nobiru'=>'*伸びる[のびる]', // stretch, grow
'noboru'=>'*上る[のぼる]', // go up, climb
'nokoru'=>'*残る[のこる]', // remain, be left over
'nokosu'=>'*残す[のこす]', // leave, leave undone
'nomimono'=>'*飲み物[のみもんお]', // beverage, drink
'nomu'=>'*飲む[のむ]', // drink
'nooto'=>'*ノート',
'norikaeru'=>'*乗り換える[のりかえる]', // change, transfer
'noru'=>'*乗る[のる]', // ride, take
'noseru'=>'*載せる[のせる]', // place, put on
'nurui'=>'*ぬるい', // tepid, lukewarm
'nyuugaku'=>'*入学[にゅうがく]', // enter a school, matriculate
'nyuuin'=>'*入院[にゅういん]', // be hospitalized
'nyuusu'=>'*ニュース', // news
'oba'=>'*おば', // one’s own aunt
'obaasan'=>'*お祖母さん[おばあさん]', // grandmother
'obake'=>'*お化[ば]け', // ghost
'obasan'=>'*おばさん', // aunt
'oboeru'=>'*覚える[おぼえる]', // memorize, learn
'ocha'=>'*お茶[おちゃ]', // tea
'ochiru'=>'*落ちる[おちる]', // fall, come down
'odoroku'=>'*驚く[おどろく]', // be surprised, be startled
'odoru'=>'*踊る[おどる]', // dance
'ohayougozaimasu'=>'*おはようございます',
'oishasan'=>'*お医者さん[おいしゃさん]', // doctor
'oishi'=>'*美味しい[おいし]', // tasty
'oiwai'=>'*お祝い[おいわい]', // celebrate
'oji'=>'*おじ', // one’s own uncle
'ojiisan'=>'*お祖父さん[おじいさん]', // grandfather
'ojisan'=>'*おじさん', // uncle
'okaasan'=>'*お母さん[おかあさん]', // mother
'okashi'=>'*お菓子[おかし]', // sweets, snacks
'oki'=>'*大きい[おき]', // big
'okiru'=>'*起きる[おきる]', // get up, get out of bed
'okiru'=>'*起きる[おきる]', // occur, happen
'okoru'=>'*起こる[おこる]', // happen
'okosu'=>'*起こす[おこす]', // wake someone up
'oku'=>'*置く[おく]:億[おく]', // put, place
'okureru'=>'*遅れる[おくれる]', // be late
'okuru'=>'*贈る[おくる]', // offer, give
'okuru'=>'*送る[おくる]', // send
'omawarisan'=>'*お巡りさん[おまわりさん]', // police officer
'omiyage'=>'*お土産[みやげ]', // ⓪ souvenir, gift
'omoi'=>'*重い[おもい]', // heavy
'omoidasu'=>'*思い出す[おもいだす]', // recollect, recall
'omoshiroi'=>'*面白い[おもしろい]', // interesting, amusing
'omou'=>'*思う[おもう]', // think
'onaji'=>'*同じ[おなじ]', // same, identical
'onaka'=>'*お腹[おなか]', // stomach, belly
'ondo'=>'*温度[おんど]', // temperature
'onegai'=>'*お願い[おねがい]', // favor
'onegaishimasu'=>'*お願[ねが]いします', // please
'onesan'=>'*お姉さん[おねさん]', // older sister
'ongaku'=>'*音楽[おんがく]', // music
'onisan'=>'*お兄さん[おにさん]', // older brother
'onna'=>'*女[おんな]', // woman
'onna'=>'*女の子[おんな][の][こ]', // little girl
'ooi'=>'*多い[おおい]', // a lot of, many
'ookisa'=>'*大きさ[おおきさ]', // size, dimension
'ooku'=>'*多く[おおく]', // much, largely
'oriru'=>'*下りる[おりる]', // go down, come down
'oriru'=>'*降りる[おりる]', // get off, land
'osenwaninarimasu'=>'*お世話[せわ]になります', // Vielen Dank für Ihre Unterstützung.
'oshieru'=>'*教える[おしえる]', // teach, tell
'osoi'=>'*遅い[おそい]', // slow, late
'osu'=>'*押す[おす]', // push, press down
'otearai'=>'*お手洗い[おてあらい]', // toilet, bathroom
'oto'=>'*音[おと]', // sound, noise
'otoko'=>'*男[おとこ]', // man, male
'otoko'=>'*男の子[おとこ][の][こ]', // boy
'otona'=>'*大人[おとな]', // adult
'otonashii'=>'*大人しい[おとなしい]', // gentle, quiet
'otosu'=>'*落とす[おとす]', // drop
'ototoi'=>'*一昨日[おととい]', // the day before yesterday
'otousan'=>'*お父さん[おとうさん]', // father, dad
'otouto'=>'*弟[おとうと]', // younger brother
'otsuri'=>'*お釣り[おつり]', // change of money
'otto'=>'*夫[おっと]', // husband
'owari'=>'*終わり[おわり]', // end, conclusion
'owaru'=>'*終わる[おわる]', // finish, end
'oya'=>'*親[おや]', // parent
'paatii'=>'*パーティー', // party
'paato'=>'*パート', // part-time
'pasokon'=>'*パソコン', // personal computer
'pasupooto'=>'*パスポート', // passport
'peeji'=>'*ページ', // page
'posuto'=>'*ポスト', // postbox, mailbox
'puroguramu'=>'*プログラム', // program booklet
'raigetsu'=>'*来月[らいげつ]', // next month
'rainen'=>'*来年[らいねん]', // next year
'raishuu'=>'*来週[らいしゅう]', // next week
'rajio'=>'*ラジオ', // radio
'ranchi'=>'*ランチ', // lunch loan word
'rei'=>'*零[れい]:例[れい]', // ➀ zero
'reibun'=>'*例文[れいぶん]',
'rekoodo'=>'*レコード', // record
'renshuu'=>'*練習[れんしゅう]',
'reshiito'=>'*レシート', // receipt loan word
'ringo'=>'*りんご', // apple
'riyuu'=>'*理由[りゆう]', // reason, excuse
'roku'=>'*六[ろく]', // ➂ six
'rokunin'=>'*六人[ろくにん]',
'ryokou'=>'*旅行[りょこう]', // travel, trip
'ryouhou'=>'*両方[りょうほう]', // both
'ryouri'=>'*料理[りょうり]', // cooking
'ryoushin'=>'*両親[りょうしん]', // parents
'ryuugaku'=>'*留学[りゅうがく]', // study abroad
'saabisu'=>'*サービス', // service, on the house
'sagasu'=>'*探す[さがす]', // search for, look for
'sageru'=>'*下げる[さげる]', // lower, turn down
'sai'=>'*歳[さい]',
'saifu'=>'*財布[さいふ]', // purse, wallet
'saigo'=>'*最後[さいご]', // last
'saikin'=>'*最近[さいきん]', // recent, latest
'saisho'=>'*最初[さいしょ]', // first, outset
'sakana'=>'*魚[さかな]', // fish
'sake'=>'*酒[さけ]', // alcohol, rice wine
'saki'=>'*先[さき]', // ahead, first
'sakunen'=>'*昨年[さくねん]', // last year , often used in writing
'sakuya'=>'*昨夜[さくや]', // last night, last evening
'sameru'=>'*冷める[さめる]', // cool off
'samui'=>'*寒い[さむい]', // cold temperature of the air
'san'=>'*三[さん]:さん', // three
'sanbiki'=>'*三匹[さんびき]', // use ひき after 3
'sanjuu'=>'*三十[さんじゅう]', // 
'sannin'=>'*三人[さんにん]',
'sara'=>'*皿[さら]', // plate, counter for plates or helpings
'saraishuu'=>'*再来週[さらいしゅう]', // the week after next
'sarariiman'=>'*サラリーマン', // office worker, company employee
'satou'=>'*砂糖[さとう]', // sugar
'satsu'=>'*冊[さつ]',
'sawaru'=>'*触る[さわる]', // touch, feel
'se'=>'*背[せ]', // height, stature
'seetaa'=>'*セーター', // sweater
'seikatsu'=>'*生活[せいかつ]', // life, living
'seikou'=>'*成功[せいこう]', // success
'seiseki'=>'*成績[せいせき]', // results, grade
'seito'=>'*生徒[せいと]', // pupil, student
'sekai'=>'*世界[せかい]', // world
'seki'=>'*世紀[せいき]:席[せき]', // century, seat, one’s place
'sekken'=>'*石鹸[せっけん]', // soap
'semai'=>'*狭い[せまい]', // narrow, small
'sen'=>'*千[せん]:線[せん]', // thousand,line
'sensei'=>'*先生[せんせい]', // teacher
'senshu'=>'*選手[せんしゅ]', // athlete, sports player
'senshuu'=>'*先週[せんしゅう]', // last week
'sentaku'=>'*洗濯[せんたく]', // laundry, washing
'setsu'=>'*説[せつ]', // ➀ theory, opinion, rumour
'setsumei'=>'*説明[せつめい]', // ⓪ explanation, description
'sha'=>'*車[]しゃ', // 
'shako'=>'*車庫[しゃこ]', // ➀
'shaberu'=>'*しゃべる', // chat, talk
'shain'=>'*社員[しゃいん]',
'shakai'=>'*社会[しゃかい]', // ➀ society
'shasetsu'=>'*社説[しゃせつ]', // ⓪
'shashin'=>'*写真[しゃしん]', // photograph
'shatsu'=>'*シャツ', // ➀ shirt
'shi'=>'*四[し]', // four Chinese origin
'shibaraku'=>'*しばらく', // a little while, a while
'shichi'=>'*七[しち]', // ➂
'shichinin'=>'*七人[しちにん]',
'shigoto'=>'*仕事[しごと]', // ⓪ work, job
'shiken'=>'*試験[しけん]', // exam
'shima'=>'*島[しま]', // island Japanese origin
'shimaru'=>'*閉まる[しまる]', // be shut, be closed
'shimau'=>'*仕舞う[しまう]', // put away, put in
'shimei'=>'*氏名[しめい]', // full name
'shimeru'=>'*締める[しめる]', // tighten, fasten
'shimeru'=>'*閉める[しめる]', // shut, close doors, windows, etc.
'shinbun'=>'*新聞[しんぶん]', // newspaper
'shingou'=>'*信号[しんごう]', // signal, traffic light
'shinjiru'=>'*信じる[しんじる]', // believe, trust
'shinpai'=>'*心配[しんぱい]', // anxiety, worry
'shinu'=>'*死ぬ[しぬ]', // die
'shio'=>'*塩[しお]', // salt
'shiraberu'=>'*調べる[しらべる]', // investigate, check
'shiro'=>'*白[しろ]', // white
'shiroi'=>'*白い[しろい]', // white, blank
'shiru'=>'*知る[しる]', // know
'shita'=>'*下[した]', // under, below
'shitsumon'=>'*質問[しつもん]', // question
'shitsurei'=>'*失礼[しつれい]',
'shizen'=>'*自然[しぜん]', // natural
'shizen'=>'*自然[しぜん]', // nature
'shizuka'=>'*静か[しずか]', // quiet, tranquil
'shokuba'=>'*職場[しょくば]', // place of work, office
'shokuji'=>'*食事[しょくじ]', // meal
'shougakkou'=>'*小学校[しょうがっこう]', // elementary school
'shoukai'=>'*紹介[しょうかい]', // introduction
'shounen'=>'*少年[しょうねん]', // boy between and years old
'shousetsu'=>'*小説[しょうせつ]', // novel
'shouyu'=>'*醤油[しょうゆ]', // soy sauce
'shujutsu'=>'*手術[しゅじゅつ]', // surgical operation
'shukudai'=>'*宿題[しゅくだい]', // homework
'shuppatsu'=>'*出発[しゅっぱつ]', // departure, starting
'shurui'=>'*種類[しゅるい]', // kind, type
'shusseki'=>'*出席[しゅっせき]',
'shuu'=>'*週[しゅう]', // week
'shuukan'=>'*習慣[しゅうかん]', // ⓪
'shuumatsu'=>'*週末[しゅうまつ]', // weekend
'sisutemu'=>'*システム', // system loan word
'soba'=>'*そば', // side, vicinity
'sobo'=>'*祖母[そぼ]', // grandmother
'socchi'=>'*そっち', // there casual
'sochira'=>'*そちら', // there, that way
'sodateru'=>'*育てる[そだてる]', // bring up, raise
'sofu'=>'*祖父[そふ]', // grandfather
'soko'=>'*そこ', // there
'sonomama'=>'*そのまま', // as it is, just like that
'sora'=>'*空[そら]', // sky
'sore'=>'*それ', // that, that one
'soto'=>'*外[そと]', // outside, open air
'sotsugyou'=>'*卒業[そつぎょう]', // graduation
'sou'=>'*そう', // so, that way
'soudan'=>'*相談[そうだん]', // consultation, advice
'soudesu'=>'*そうです', // that's right
'soudesuka'=>'*そうですか', // ↗ Is that right? ↘ Oh, I see.
'subarashii'=>'*素晴らしい[すばらしい]', // excellent, wonderful
'sushi'=>'*寿司[すし]', // ➂, ➁お寿司
'sugu'=>'*直ぐ[すぐ]', // at once, soon
'suiyoubi'=>'*水曜日[すいようび]', // Wednesday
'suki'=>'*好き[すき]', // favorite, liked
'sukoshi'=>'*少し[すこし]', // a bit, a little while
'suku'=>'*空く[すく]', // be empty, become less crowded
'sukunai'=>'*少ない[すくない]', // few, little
'suimasen'=>'*すいません',
'sumimasen'=>'*すみません',
'sumu'=>'*住む[すむ]', // live, reside
'supootsu'=>'*スポーツ', // sport
'suppai'=>'*酸っぱい[すっぱい]', // sour
'supuun'=>'*スプーン', // spoon
'suru'=>'*する', // do, make
'sushi'=>'*寿司[すし]', // sushi
'susumeru'=>'*進める[すすめる]', // go ahead, proceed
'susumu'=>'*進む[すすむ]', // advance, move forward
'suteru'=>'*捨てる[すてる]', // discard, abandon
'suu'=>'*数[すう]', // number
'suugaku'=>'*数学[すうがく]', // mathematics
'suuji'=>'*数字[すうじ]', // numeric characters
'suwaru'=>'*座る[すわる]', // sit, sit down
'suzushii'=>'*涼しい[すずしい]', // cool of temperature
'tabako'=>'*たばこ', // tobacco, cigarette
'tabemono'=>'*食べ物[たべもの]', // food
'taberu'=>'*食べる[たべる]', // eat
'tabun'=>'*多分[たぶん]', // probably, perhaps
'tada'=>'*ただ', // free
'tadashii'=>'*正しい[ただしい]', // correct, righteous
'taifuu'=>'*台風[たいふう]', // typhoon
'taihen'=>'*大変[たいへん]', // awful, hard
'taijin'=>'*タイ人[じん]', // ➁イ➁
'taisetsu'=>'*大切[たいせつ]', // important, valuable
'taishikan'=>'*大使館[たいしかん]', // embassy
'taiwan'=>'*臺灣 [たいわん]',
'taiyou'=>'*太陽[たいよう]', // sun
'takai'=>'*高い[たかい]', // high, tall
'takasa'=>'*高さ[たかさ]', // height
'takusan'=>'*たくさん', // a lot, in large quantity
'takushii'=>'*タクシー', // taxi
'tame'=>'*ため', // sake, purpose
'tanomu'=>'*頼む[たのむ]', // order, ask for
'tanoshii'=>'*楽しい[たのしい]', // fun, enjoyable
'tanoshimu'=>'*楽しむ[たのしむ]', // enjoy
'taoreru'=>'*倒れる[たおれる]', // fall over
'tashika'=>'*確か[たしか]', // for sure, for certain
'tasukeru'=>'*助ける[たすける]', // help, save
'tatemono'=>'*建物[たてもの]', // building, structure
'tateru'=>'*建てる[たてる]', // build, erect
'tateru'=>'*立てる[たてる]', // stand, set up
'tatoeba'=>'*例えば[たとえば]', // for example
'tatsu'=>'*立つ[たつ]', // stand, rise
'tazuneru'=>'*訪ねる[たずねる]', // visit, go to see
'te'=>'*手[て]', // hand
'techou'=>'*手帳[てちょう]',
'teeburu'=>'*テーブル', // table
'teepu'=>'*テープ',
'tegami'=>'*手紙[てがみ]', // letter
'teian'=>'*提案[ていあん]', // proposition, proposal
'tempura'=>'*天ぷら[て]mぷら', // Japanese deep-fried food
'tenki'=>'*天気[てんき]', // weather
'terebi'=>'*テレビ', // television
'tesuto'=>'*テスト', // test
'tetsudau'=>'*手伝う[てつだう]', // help, assist
'tisshu'=>'*ティッシュ', // tissue
'to'=>'*戸[と]', // door, sliding door
'tobu'=>'*飛ぶ[とぶ]', // fly
'todoku'=>'*届く[とどく]', // reach, be received
'tojiru'=>'*閉じる[とじる]', // shut, close books, eyes, etc.
'tokei'=>'*時計[とけい]', // clock, watch
'toki'=>'*時[とき]', // time, moment
'tokidoki'=>'*時々[ときどき]', // sometimes
'tokoro'=>'*所[ところ]', // place
'tokubetsu'=>'*特別[とくべつ]', // special
'tokuni'=>'*特に[とくに]', // specially, particularly
'tomaru'=>'*止まる[とまる]', // come to a stop, cease
'tomaru'=>'*泊まる[とまる]', // stay overnight
'tomeru'=>'*止める[とめる]', // stop a car…. 止める yameru give up
'tomodachi'=>'*友達[ともだち]', // friend, companion
'tonari'=>'*隣[となり]', // next to, next door
'tooi'=>'*遠い[とおい]', // far, distant
'tooka'=>'*十日[とおか]', // ten days, tenth of the month
'tooku'=>'*遠く[とおく]', // far away, at a distance
'toori'=>'*通り[とおり]', // street, road
'tooru'=>'*通る[とおる]', // pass, go through
'torakku'=>'*トラック', // truck
'tori'=>'*鳥[とり]', // bird, poultry
'toru'=>'*取る[とる]', // take, get
'toru'=>'*撮る[とる]', // take a photograph, film
'toshi'=>'*年[とし]', // year, age
'toshiue'=>'*年上[としうえ]', // older, senior
'toshokan'=>'*図書館[としょかん]', // library
'totemo'=>'*とても', // very
'tou'=>'*頭[とう]', // ➀ cattle, horses; head
'toukyou'=>'*東京[とうきょう]',
'tsugi'=>'*次[つぎ]', // next
'tsuitachi'=>'*一日[ついたち]', // first of the month
'tsukau'=>'*使[つか]う', // use, make use of
'tsukeru'=>'*つける', // switch on, turn on
'tsuki'=>'*月[つき]', // moon
'tsuku'=>'*つく', // be on, be switched on
'tsuku'=>'*着く[つく]', // arrive at, reach
'tsukue'=>'*机[つくえ]', // desk
'tsukuru'=>'*作る[つくる]', // make, create
'tsuma'=>'*妻[つま]', // woman
'tsumaranai'=>'*つまらない', // boring, dull
'tsumari'=>'*つまり', // in short, that is to say
'tsumetai'=>'*冷たい[つめたい]', // cold to touch
'tsumori'=>'*つもり', // intention, purpose
'tsureteiku'=>'*連れていく[つれていく]', // take along, bring along a person
'tsuretekuru'=>'*連れて来る[つれてくる]', // bring a person
'tsutaeru'=>'*伝える[つたえる]', // convey, transmit
'tsutomeru'=>'*勤める[つとめる]', // serve, hold a job
'tsuyoi'=>'*強い[つよい]', // strong
'tsuzukeru'=>'*続ける[つずける]', // continue, keep up
'tsuzuku'=>'*続く[つずく]', // continue, follow
'ude'=>'*腕[うで]', // arm
'udedokei'=>'*腕[うで]時計[どけい]', // wristwatch
'ue'=>'*上[うえ]', // up, above
'ugokasu'=>'*動かす[うごかす]', // move something
'ugoku'=>'*動く[うごく]', // move
'uketoru'=>'*受け取る[うけとる]', // receive, get
'uma'=>'*馬[うま]', // horse
'umai'=>'*うまい', // good at, sweet, delicious
'umareru'=>'*生まれる[うまれる]', // be born, come into existence
'umi'=>'*海[うみ]', // sea, ocean
'un'=>'*うん', // casual yes
'uun'=>'*ううん', // casual no
'undou'=>'*運動[うんどう]', // movement, exercise
'unten'=>'*運転[うんてん]', // drive
'ura'=>'*裏[うら]', // the back, the reverse side
'ureru'=>'*売れる[うれる]', // sell, be in demand
'ureshii'=>'*嬉しい[うれしい]', // happy, glad
'urikire'=>'*売り切れ[うりきれ]', // sell out
'uru'=>'*売る[うる]', // sell
'urusai'=>'*うるさい', // noisy, annoying
'ushiro'=>'*後ろ[うしろ]', // back, behind
'usui'=>'*薄い[うすい]', // thin, weak
'uta'=>'*歌[うた]', // song
'utau'=>'*歌う[うたう]', // sing
'utsu'=>'*打つ[うつ]', // hit, strike
'utsukushii'=>'*美しい[うつくしい]', // beautiful
'utsusu'=>'*移す[うつす]', // move, transfer
'wakai'=>'*若い[わかい]', // young
'wakamono'=>'*若者[わかもの]', // young person, youth
'wakareru'=>'*分かれる[わかれる]', // be divided, split off
'wakaru'=>'*分かる[わかる]', // understand
'wakeru'=>'*分ける[わける]', // divide, share
'warau'=>'*笑う[わらう]', // laugh, smile
'warui'=>'*悪い[わるい]', // bad
'wasureru'=>'*忘れる[わすれる]', // forget, leave behind
'watashi'=>'*私[わたし]', // I
'watashitachi'=>'*私たち[わたしたち]', // we
'watasu'=>'*渡す[わたす]', // hand over, give
'weetaa'=>'*ウェーター', // waiter
'weetoresu'=>'*ウェートレス', // waitress
'yahari'=>'*やはり', // as expected
'yakan'=>'*やかん', // kettle
'yakedo'=>'*火傷[やけど]', // burn
'yakusoku'=>'*約束[やくそく]', // promise, vow
'yakyuu'=>'*野球[やきゅう]', // baseball
'yama'=>'*山[やま]', // mountain
'yamai'=>'*病[やまい]', // ➀
'yamu'=>'*止む[やむ]', // stop, cease
'yaru'=>'*やる', // do, give
'yaru'=>'*やる', // give to an inferior
'yasai'=>'*野菜[やさい]', // vegetable
'yasashi'=>'*易しい[やさし]', // easy, simple
'yasashii'=>'*優しい[やさしい]', // gentle, kind
'yasui'=>'*安い[やすい]', // cheap, inexpensive
'yasumi'=>'*休み[やすみ]', // holiday, break
'yasumu'=>'*休む[やすむ]', // take a rest, take a break
'yatto'=>'*やっと', // at last, finally
'yattsu'=>'*八つ[やっつ]', // eight things
'yobu'=>'*呼ぶ[よぶ]', // call, name
'yoi'=>'*良い[よい]', // good /written form
'yokka'=>'*四日[よっか]', // four days, fourth of the month
'yoko'=>'*横[よこ]', // side, width across
'yoku'=>'*よく', // often, well
'yomu'=>'*読む[よむ]', // read
'yon'=>'*四[よん]', // four Japanese origin
'yonaka'=>'*夜中[よなか]', // midnight
'yonin'=>'*四人[よにん]', // not よん
'yorokobu'=>'*喜ぶ[よろこぶ]', // be happy, be delighted
'yoroshiku'=>'*よろしく', // one’s regards
'yoru'=>'*夜[よる]', // night from sunset to sunrise
'yotei'=>'*予定[よてい]', // schedule, plan
'yotsu'=>'*四つ[よつ]', // four things
'yotsukado'=>'*四つ角[よつかど]', // intersection
'you'=>'*用[よう]', // things to do
'youbi'=>'*曜日[ようび]', // day of the week
'youi'=>'*用意[ようい]', // preparation
'youka'=>'*八日[ようか]', // eight days, eighth of the month
'youkoso'=>'*ようこそ', // welcome greeting
'yowai'=>'*弱い[よわい]', // weak
'yu'=>'*湯[ゆ]', // hot water
'yubi'=>'*指[ゆび]', // finger, toe
'yuki'=>'*雪[ゆき]', // snow, snowfall
'yukkuri'=>'*ゆっくり', // slowly
'yume'=>'*夢[ゆめ]', // dream
'yurui'=>'*緩い[ゆるい]', // slack, loose
'yuu'=>'*夕[ゆう]', // ⓪ evening ➀ name
'yurusu'=>'*許す[ゆるす]', // permit, forgive
'yuubinkyoku'=>'*郵便局[ゆうびんきょく]', // post office
'yuugata'=>'*夕方[ゆうがた]', // early evening, at dusk
'yuumei'=>'*有名[ゆうめい]', // famous
'yuushoku'=>'*夕食[ゆうしょく]', // supper, dinner
'zannen'=>'*残念[ざんねん]', // regretful, disappointing
'zasshi'=>'*雑誌[ざっし]', // magazine, journal
'zenbu'=>'*全部[ぜんぶ]', // all, whole
'zero'=>'*ゼロ', // ➀
'zettaini'=>'*絶対に[ぜったいに]', // absolutely, definitely
'zutto'=>'*ずっと', // all the time, all through
''=>'*[]',
''=>'*[]',
''=>'*[]',
);
?>